/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.smallest.resources.atoms.agents.requests;

import ai.smallest.core.ObjectMappers;
import ai.smallest.resources.atoms.agents.types.UpdateWorkflowConfigurationAgentsRequestWorkflowGraph;
import ai.smallest.resources.atoms.types.SinglePromptConfig;
import ai.smallest.resources.atoms.types.WorkflowType;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = UpdateWorkflowConfigurationAgentsRequest.Builder.class
)
public final class UpdateWorkflowConfigurationAgentsRequest {
  private final WorkflowType type;

  private final Optional<UpdateWorkflowConfigurationAgentsRequestWorkflowGraph> workflowGraph;

  private final Optional<SinglePromptConfig> singlePromptConfig;

  private final Map<String, Object> additionalProperties;

  private UpdateWorkflowConfigurationAgentsRequest(WorkflowType type,
      Optional<UpdateWorkflowConfigurationAgentsRequestWorkflowGraph> workflowGraph,
      Optional<SinglePromptConfig> singlePromptConfig, Map<String, Object> additionalProperties) {
    this.type = type;
    this.workflowGraph = workflowGraph;
    this.singlePromptConfig = singlePromptConfig;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("type")
  public WorkflowType getType() {
    return type;
  }

  /**
   * @return Required when <code>type = workflow_graph</code>. Exactly one of <code>workflowGraph</code> or <code>singlePromptConfig</code> must be provided.
   */
  @JsonProperty("workflowGraph")
  public Optional<UpdateWorkflowConfigurationAgentsRequestWorkflowGraph> getWorkflowGraph() {
    return workflowGraph;
  }

  @JsonProperty("singlePromptConfig")
  public Optional<SinglePromptConfig> getSinglePromptConfig() {
    return singlePromptConfig;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof UpdateWorkflowConfigurationAgentsRequest && equalTo((UpdateWorkflowConfigurationAgentsRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(UpdateWorkflowConfigurationAgentsRequest other) {
    return type.equals(other.type) && workflowGraph.equals(other.workflowGraph) && singlePromptConfig.equals(other.singlePromptConfig);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.type, this.workflowGraph, this.singlePromptConfig);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static TypeStage builder() {
    return new Builder();
  }

  public interface TypeStage {
    _FinalStage type(@NotNull WorkflowType type);

    Builder from(UpdateWorkflowConfigurationAgentsRequest other);
  }

  public interface _FinalStage {
    UpdateWorkflowConfigurationAgentsRequest build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /**
     * <p>Required when <code>type = workflow_graph</code>. Exactly one of <code>workflowGraph</code> or <code>singlePromptConfig</code> must be provided.</p>
     */
    _FinalStage workflowGraph(
        Optional<UpdateWorkflowConfigurationAgentsRequestWorkflowGraph> workflowGraph);

    _FinalStage workflowGraph(UpdateWorkflowConfigurationAgentsRequestWorkflowGraph workflowGraph);

    _FinalStage singlePromptConfig(Optional<SinglePromptConfig> singlePromptConfig);

    _FinalStage singlePromptConfig(SinglePromptConfig singlePromptConfig);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements TypeStage, _FinalStage {
    private WorkflowType type;

    private Optional<SinglePromptConfig> singlePromptConfig = Optional.empty();

    private Optional<UpdateWorkflowConfigurationAgentsRequestWorkflowGraph> workflowGraph = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(UpdateWorkflowConfigurationAgentsRequest other) {
      type(other.getType());
      workflowGraph(other.getWorkflowGraph());
      singlePromptConfig(other.getSinglePromptConfig());
      return this;
    }

    @java.lang.Override
    @JsonSetter("type")
    public _FinalStage type(@NotNull WorkflowType type) {
      this.type = Objects.requireNonNull(type, "type must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage singlePromptConfig(SinglePromptConfig singlePromptConfig) {
      this.singlePromptConfig = Optional.ofNullable(singlePromptConfig);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "singlePromptConfig",
        nulls = Nulls.SKIP
    )
    public _FinalStage singlePromptConfig(Optional<SinglePromptConfig> singlePromptConfig) {
      this.singlePromptConfig = singlePromptConfig;
      return this;
    }

    /**
     * <p>Required when <code>type = workflow_graph</code>. Exactly one of <code>workflowGraph</code> or <code>singlePromptConfig</code> must be provided.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage workflowGraph(
        UpdateWorkflowConfigurationAgentsRequestWorkflowGraph workflowGraph) {
      this.workflowGraph = Optional.ofNullable(workflowGraph);
      return this;
    }

    /**
     * <p>Required when <code>type = workflow_graph</code>. Exactly one of <code>workflowGraph</code> or <code>singlePromptConfig</code> must be provided.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "workflowGraph",
        nulls = Nulls.SKIP
    )
    public _FinalStage workflowGraph(
        Optional<UpdateWorkflowConfigurationAgentsRequestWorkflowGraph> workflowGraph) {
      this.workflowGraph = workflowGraph;
      return this;
    }

    @java.lang.Override
    public UpdateWorkflowConfigurationAgentsRequest build() {
      return new UpdateWorkflowConfigurationAgentsRequest(type, workflowGraph, singlePromptConfig, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
