/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.smallest.resources.atoms.conversations.requests;

import ai.smallest.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = CancelConversationsRequest.Builder.class
)
public final class CancelConversationsRequest {
  private final String callId;

  private final Optional<String> reason;

  private final Map<String, Object> additionalProperties;

  private CancelConversationsRequest(String callId, Optional<String> reason,
      Map<String, Object> additionalProperties) {
    this.callId = callId;
    this.reason = reason;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return The <code>callId</code> returned by <code>POST /conversation/outbound</code> or visible in <code>GET /conversation</code>.
   */
  @JsonProperty("callId")
  public String getCallId() {
    return callId;
  }

  /**
   * @return Optional free-text reason for cancellation. Logged for support / audit.
   */
  @JsonProperty("reason")
  public Optional<String> getReason() {
    return reason;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof CancelConversationsRequest && equalTo((CancelConversationsRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(CancelConversationsRequest other) {
    return callId.equals(other.callId) && reason.equals(other.reason);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.callId, this.reason);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static CallIdStage builder() {
    return new Builder();
  }

  public interface CallIdStage {
    /**
     * <p>The <code>callId</code> returned by <code>POST /conversation/outbound</code> or visible in <code>GET /conversation</code>.</p>
     */
    _FinalStage callId(@NotNull String callId);

    Builder from(CancelConversationsRequest other);
  }

  public interface _FinalStage {
    CancelConversationsRequest build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /**
     * <p>Optional free-text reason for cancellation. Logged for support / audit.</p>
     */
    _FinalStage reason(Optional<String> reason);

    _FinalStage reason(String reason);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements CallIdStage, _FinalStage {
    private String callId;

    private Optional<String> reason = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(CancelConversationsRequest other) {
      callId(other.getCallId());
      reason(other.getReason());
      return this;
    }

    /**
     * <p>The <code>callId</code> returned by <code>POST /conversation/outbound</code> or visible in <code>GET /conversation</code>.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("callId")
    public _FinalStage callId(@NotNull String callId) {
      this.callId = Objects.requireNonNull(callId, "callId must not be null");
      return this;
    }

    /**
     * <p>Optional free-text reason for cancellation. Logged for support / audit.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage reason(String reason) {
      this.reason = Optional.ofNullable(reason);
      return this;
    }

    /**
     * <p>Optional free-text reason for cancellation. Logged for support / audit.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "reason",
        nulls = Nulls.SKIP
    )
    public _FinalStage reason(Optional<String> reason) {
      this.reason = reason;
      return this;
    }

    @java.lang.Override
    public CancelConversationsRequest build() {
      return new CancelConversationsRequest(callId, reason, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
