/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.smallest.resources.atoms.organization.types;

import ai.smallest.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = GetOrganizationResponseData.Builder.class
)
public final class GetOrganizationResponseData {
  private final Optional<String> id;

  private final Optional<String> name;

  private final Optional<List<GetOrganizationResponseDataMembersItem>> members;

  private final Optional<GetOrganizationResponseDataSubscription> subscription;

  private final Map<String, Object> additionalProperties;

  private GetOrganizationResponseData(Optional<String> id, Optional<String> name,
      Optional<List<GetOrganizationResponseDataMembersItem>> members,
      Optional<GetOrganizationResponseDataSubscription> subscription,
      Map<String, Object> additionalProperties) {
    this.id = id;
    this.name = name;
    this.members = members;
    this.subscription = subscription;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return The organization ID
   */
  @JsonProperty("_id")
  public Optional<String> getId() {
    return id;
  }

  /**
   * @return The organization name
   */
  @JsonProperty("name")
  public Optional<String> getName() {
    return name;
  }

  @JsonProperty("members")
  public Optional<List<GetOrganizationResponseDataMembersItem>> getMembers() {
    return members;
  }

  @JsonProperty("subscription")
  public Optional<GetOrganizationResponseDataSubscription> getSubscription() {
    return subscription;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof GetOrganizationResponseData && equalTo((GetOrganizationResponseData) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(GetOrganizationResponseData other) {
    return id.equals(other.id) && name.equals(other.name) && members.equals(other.members) && subscription.equals(other.subscription);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.id, this.name, this.members, this.subscription);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<String> id = Optional.empty();

    private Optional<String> name = Optional.empty();

    private Optional<List<GetOrganizationResponseDataMembersItem>> members = Optional.empty();

    private Optional<GetOrganizationResponseDataSubscription> subscription = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(GetOrganizationResponseData other) {
      id(other.getId());
      name(other.getName());
      members(other.getMembers());
      subscription(other.getSubscription());
      return this;
    }

    /**
     * <p>The organization ID</p>
     */
    @JsonSetter(
        value = "_id",
        nulls = Nulls.SKIP
    )
    public Builder id(Optional<String> id) {
      this.id = id;
      return this;
    }

    public Builder id(String id) {
      this.id = Optional.ofNullable(id);
      return this;
    }

    /**
     * <p>The organization name</p>
     */
    @JsonSetter(
        value = "name",
        nulls = Nulls.SKIP
    )
    public Builder name(Optional<String> name) {
      this.name = name;
      return this;
    }

    public Builder name(String name) {
      this.name = Optional.ofNullable(name);
      return this;
    }

    @JsonSetter(
        value = "members",
        nulls = Nulls.SKIP
    )
    public Builder members(Optional<List<GetOrganizationResponseDataMembersItem>> members) {
      this.members = members;
      return this;
    }

    public Builder members(List<GetOrganizationResponseDataMembersItem> members) {
      this.members = Optional.ofNullable(members);
      return this;
    }

    @JsonSetter(
        value = "subscription",
        nulls = Nulls.SKIP
    )
    public Builder subscription(Optional<GetOrganizationResponseDataSubscription> subscription) {
      this.subscription = subscription;
      return this;
    }

    public Builder subscription(GetOrganizationResponseDataSubscription subscription) {
      this.subscription = Optional.ofNullable(subscription);
      return this;
    }

    public GetOrganizationResponseData build() {
      return new GetOrganizationResponseData(id, name, members, subscription, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
