/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.smallest.resources.atoms.callactions.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class CreateCallActionRequestActionType {
  public static final CreateCallActionRequestActionType UPDATE = new CreateCallActionRequestActionType(Value.UPDATE, "update");

  public static final CreateCallActionRequestActionType CREATE = new CreateCallActionRequestActionType(Value.CREATE, "create");

  private final Value value;

  private final String string;

  CreateCallActionRequestActionType(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof CreateCallActionRequestActionType && this.string.equals(((CreateCallActionRequestActionType) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case UPDATE:
        return visitor.visitUpdate();
      case CREATE:
        return visitor.visitCreate();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static CreateCallActionRequestActionType valueOf(String value) {
    switch (value) {
      case "update":
        return UPDATE;
      case "create":
        return CREATE;
      default:
        return new CreateCallActionRequestActionType(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    CREATE,

    UPDATE,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitCreate();

    T visitUpdate();

    T visitUnknown(String unknownType);
  }
}
