/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.smallest.resources.atoms.agents.types;

import ai.smallest.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = CreateAgentRequestPreCallApiResponseVariablesItem.Builder.class
)
public final class CreateAgentRequestPreCallApiResponseVariablesItem {
  private final String variableName;

  private final String jsonPath;

  private final Map<String, Object> additionalProperties;

  private CreateAgentRequestPreCallApiResponseVariablesItem(String variableName, String jsonPath,
      Map<String, Object> additionalProperties) {
    this.variableName = variableName;
    this.jsonPath = jsonPath;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return The name of the variable to inject into the agent prompt.
   */
  @JsonProperty("variableName")
  public String getVariableName() {
    return variableName;
  }

  /**
   * @return JSON path expression to extract the value from the API response.
   */
  @JsonProperty("jsonPath")
  public String getJsonPath() {
    return jsonPath;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof CreateAgentRequestPreCallApiResponseVariablesItem && equalTo((CreateAgentRequestPreCallApiResponseVariablesItem) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(CreateAgentRequestPreCallApiResponseVariablesItem other) {
    return variableName.equals(other.variableName) && jsonPath.equals(other.jsonPath);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.variableName, this.jsonPath);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static VariableNameStage builder() {
    return new Builder();
  }

  public interface VariableNameStage {
    /**
     * <p>The name of the variable to inject into the agent prompt.</p>
     */
    JsonPathStage variableName(@NotNull String variableName);

    Builder from(CreateAgentRequestPreCallApiResponseVariablesItem other);
  }

  public interface JsonPathStage {
    /**
     * <p>JSON path expression to extract the value from the API response.</p>
     */
    _FinalStage jsonPath(@NotNull String jsonPath);
  }

  public interface _FinalStage {
    CreateAgentRequestPreCallApiResponseVariablesItem build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements VariableNameStage, JsonPathStage, _FinalStage {
    private String variableName;

    private String jsonPath;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(CreateAgentRequestPreCallApiResponseVariablesItem other) {
      variableName(other.getVariableName());
      jsonPath(other.getJsonPath());
      return this;
    }

    /**
     * <p>The name of the variable to inject into the agent prompt.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("variableName")
    public JsonPathStage variableName(@NotNull String variableName) {
      this.variableName = Objects.requireNonNull(variableName, "variableName must not be null");
      return this;
    }

    /**
     * <p>JSON path expression to extract the value from the API response.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("jsonPath")
    public _FinalStage jsonPath(@NotNull String jsonPath) {
      this.jsonPath = Objects.requireNonNull(jsonPath, "jsonPath must not be null");
      return this;
    }

    @java.lang.Override
    public CreateAgentRequestPreCallApiResponseVariablesItem build() {
      return new CreateAgentRequestPreCallApiResponseVariablesItem(variableName, jsonPath, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
