/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.smallest.resources.atoms.agents.types;

import ai.smallest.core.Nullable;
import ai.smallest.core.NullableNonemptyFilter;
import ai.smallest.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Boolean;
import java.lang.Double;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = GetAgentWidgetConfigResponseData.Builder.class
)
public final class GetAgentWidgetConfigResponseData {
  private final Optional<String> assistantId;

  private final Optional<GetAgentWidgetConfigResponseDataPosition> position;

  private final Optional<GetAgentWidgetConfigResponseDataSize> size;

  private final Optional<Double> borderRadius;

  private final Optional<GetAgentWidgetConfigResponseDataMode> mode;

  private final Optional<GetAgentWidgetConfigResponseDataTheme> theme;

  private final Optional<String> baseColor;

  private final Optional<String> accentColor;

  private final Optional<String> title;

  private final Optional<String> startButtonText;

  private final Optional<String> endButtonText;

  private final Optional<String> avatarUrl;

  private final Optional<Boolean> voiceShowTranscript;

  private final Optional<Boolean> consentRequired;

  private final Map<String, Object> additionalProperties;

  private GetAgentWidgetConfigResponseData(Optional<String> assistantId,
      Optional<GetAgentWidgetConfigResponseDataPosition> position,
      Optional<GetAgentWidgetConfigResponseDataSize> size, Optional<Double> borderRadius,
      Optional<GetAgentWidgetConfigResponseDataMode> mode,
      Optional<GetAgentWidgetConfigResponseDataTheme> theme, Optional<String> baseColor,
      Optional<String> accentColor, Optional<String> title, Optional<String> startButtonText,
      Optional<String> endButtonText, Optional<String> avatarUrl,
      Optional<Boolean> voiceShowTranscript, Optional<Boolean> consentRequired,
      Map<String, Object> additionalProperties) {
    this.assistantId = assistantId;
    this.position = position;
    this.size = size;
    this.borderRadius = borderRadius;
    this.mode = mode;
    this.theme = theme;
    this.baseColor = baseColor;
    this.accentColor = accentColor;
    this.title = title;
    this.startButtonText = startButtonText;
    this.endButtonText = endButtonText;
    this.avatarUrl = avatarUrl;
    this.voiceShowTranscript = voiceShowTranscript;
    this.consentRequired = consentRequired;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Same as the agent ID — convenience field for the widget embed code
   */
  @JsonProperty("assistantId")
  public Optional<String> getAssistantId() {
    return assistantId;
  }

  @JsonProperty("position")
  public Optional<GetAgentWidgetConfigResponseDataPosition> getPosition() {
    return position;
  }

  @JsonProperty("size")
  public Optional<GetAgentWidgetConfigResponseDataSize> getSize() {
    return size;
  }

  @JsonProperty("borderRadius")
  public Optional<Double> getBorderRadius() {
    return borderRadius;
  }

  @JsonProperty("mode")
  public Optional<GetAgentWidgetConfigResponseDataMode> getMode() {
    return mode;
  }

  @JsonProperty("theme")
  public Optional<GetAgentWidgetConfigResponseDataTheme> getTheme() {
    return theme;
  }

  @JsonProperty("baseColor")
  public Optional<String> getBaseColor() {
    return baseColor;
  }

  @JsonProperty("accentColor")
  public Optional<String> getAccentColor() {
    return accentColor;
  }

  @JsonProperty("title")
  public Optional<String> getTitle() {
    return title;
  }

  @JsonProperty("startButtonText")
  public Optional<String> getStartButtonText() {
    return startButtonText;
  }

  @JsonProperty("endButtonText")
  public Optional<String> getEndButtonText() {
    return endButtonText;
  }

  @JsonIgnore
  public Optional<String> getAvatarUrl() {
    if (avatarUrl == null) {
      return Optional.empty();
    }
    return avatarUrl;
  }

  @JsonProperty("voiceShowTranscript")
  public Optional<Boolean> getVoiceShowTranscript() {
    return voiceShowTranscript;
  }

  @JsonProperty("consentRequired")
  public Optional<Boolean> getConsentRequired() {
    return consentRequired;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("avatarUrl")
  private Optional<String> _getAvatarUrl() {
    return avatarUrl;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof GetAgentWidgetConfigResponseData && equalTo((GetAgentWidgetConfigResponseData) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(GetAgentWidgetConfigResponseData other) {
    return assistantId.equals(other.assistantId) && position.equals(other.position) && size.equals(other.size) && borderRadius.equals(other.borderRadius) && mode.equals(other.mode) && theme.equals(other.theme) && baseColor.equals(other.baseColor) && accentColor.equals(other.accentColor) && title.equals(other.title) && startButtonText.equals(other.startButtonText) && endButtonText.equals(other.endButtonText) && avatarUrl.equals(other.avatarUrl) && voiceShowTranscript.equals(other.voiceShowTranscript) && consentRequired.equals(other.consentRequired);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.assistantId, this.position, this.size, this.borderRadius, this.mode, this.theme, this.baseColor, this.accentColor, this.title, this.startButtonText, this.endButtonText, this.avatarUrl, this.voiceShowTranscript, this.consentRequired);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<String> assistantId = Optional.empty();

    private Optional<GetAgentWidgetConfigResponseDataPosition> position = Optional.empty();

    private Optional<GetAgentWidgetConfigResponseDataSize> size = Optional.empty();

    private Optional<Double> borderRadius = Optional.empty();

    private Optional<GetAgentWidgetConfigResponseDataMode> mode = Optional.empty();

    private Optional<GetAgentWidgetConfigResponseDataTheme> theme = Optional.empty();

    private Optional<String> baseColor = Optional.empty();

    private Optional<String> accentColor = Optional.empty();

    private Optional<String> title = Optional.empty();

    private Optional<String> startButtonText = Optional.empty();

    private Optional<String> endButtonText = Optional.empty();

    private Optional<String> avatarUrl = Optional.empty();

    private Optional<Boolean> voiceShowTranscript = Optional.empty();

    private Optional<Boolean> consentRequired = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(GetAgentWidgetConfigResponseData other) {
      assistantId(other.getAssistantId());
      position(other.getPosition());
      size(other.getSize());
      borderRadius(other.getBorderRadius());
      mode(other.getMode());
      theme(other.getTheme());
      baseColor(other.getBaseColor());
      accentColor(other.getAccentColor());
      title(other.getTitle());
      startButtonText(other.getStartButtonText());
      endButtonText(other.getEndButtonText());
      avatarUrl(other.getAvatarUrl());
      voiceShowTranscript(other.getVoiceShowTranscript());
      consentRequired(other.getConsentRequired());
      return this;
    }

    /**
     * <p>Same as the agent ID — convenience field for the widget embed code</p>
     */
    @JsonSetter(
        value = "assistantId",
        nulls = Nulls.SKIP
    )
    public Builder assistantId(Optional<String> assistantId) {
      this.assistantId = assistantId;
      return this;
    }

    public Builder assistantId(String assistantId) {
      this.assistantId = Optional.ofNullable(assistantId);
      return this;
    }

    @JsonSetter(
        value = "position",
        nulls = Nulls.SKIP
    )
    public Builder position(Optional<GetAgentWidgetConfigResponseDataPosition> position) {
      this.position = position;
      return this;
    }

    public Builder position(GetAgentWidgetConfigResponseDataPosition position) {
      this.position = Optional.ofNullable(position);
      return this;
    }

    @JsonSetter(
        value = "size",
        nulls = Nulls.SKIP
    )
    public Builder size(Optional<GetAgentWidgetConfigResponseDataSize> size) {
      this.size = size;
      return this;
    }

    public Builder size(GetAgentWidgetConfigResponseDataSize size) {
      this.size = Optional.ofNullable(size);
      return this;
    }

    @JsonSetter(
        value = "borderRadius",
        nulls = Nulls.SKIP
    )
    public Builder borderRadius(Optional<Double> borderRadius) {
      this.borderRadius = borderRadius;
      return this;
    }

    public Builder borderRadius(Double borderRadius) {
      this.borderRadius = Optional.ofNullable(borderRadius);
      return this;
    }

    @JsonSetter(
        value = "mode",
        nulls = Nulls.SKIP
    )
    public Builder mode(Optional<GetAgentWidgetConfigResponseDataMode> mode) {
      this.mode = mode;
      return this;
    }

    public Builder mode(GetAgentWidgetConfigResponseDataMode mode) {
      this.mode = Optional.ofNullable(mode);
      return this;
    }

    @JsonSetter(
        value = "theme",
        nulls = Nulls.SKIP
    )
    public Builder theme(Optional<GetAgentWidgetConfigResponseDataTheme> theme) {
      this.theme = theme;
      return this;
    }

    public Builder theme(GetAgentWidgetConfigResponseDataTheme theme) {
      this.theme = Optional.ofNullable(theme);
      return this;
    }

    @JsonSetter(
        value = "baseColor",
        nulls = Nulls.SKIP
    )
    public Builder baseColor(Optional<String> baseColor) {
      this.baseColor = baseColor;
      return this;
    }

    public Builder baseColor(String baseColor) {
      this.baseColor = Optional.ofNullable(baseColor);
      return this;
    }

    @JsonSetter(
        value = "accentColor",
        nulls = Nulls.SKIP
    )
    public Builder accentColor(Optional<String> accentColor) {
      this.accentColor = accentColor;
      return this;
    }

    public Builder accentColor(String accentColor) {
      this.accentColor = Optional.ofNullable(accentColor);
      return this;
    }

    @JsonSetter(
        value = "title",
        nulls = Nulls.SKIP
    )
    public Builder title(Optional<String> title) {
      this.title = title;
      return this;
    }

    public Builder title(String title) {
      this.title = Optional.ofNullable(title);
      return this;
    }

    @JsonSetter(
        value = "startButtonText",
        nulls = Nulls.SKIP
    )
    public Builder startButtonText(Optional<String> startButtonText) {
      this.startButtonText = startButtonText;
      return this;
    }

    public Builder startButtonText(String startButtonText) {
      this.startButtonText = Optional.ofNullable(startButtonText);
      return this;
    }

    @JsonSetter(
        value = "endButtonText",
        nulls = Nulls.SKIP
    )
    public Builder endButtonText(Optional<String> endButtonText) {
      this.endButtonText = endButtonText;
      return this;
    }

    public Builder endButtonText(String endButtonText) {
      this.endButtonText = Optional.ofNullable(endButtonText);
      return this;
    }

    @JsonSetter(
        value = "avatarUrl",
        nulls = Nulls.SKIP
    )
    public Builder avatarUrl(Optional<String> avatarUrl) {
      this.avatarUrl = avatarUrl;
      return this;
    }

    public Builder avatarUrl(String avatarUrl) {
      this.avatarUrl = Optional.ofNullable(avatarUrl);
      return this;
    }

    public Builder avatarUrl(Nullable<String> avatarUrl) {
      if (avatarUrl.isNull()) {
        this.avatarUrl = null;
      }
      else if (avatarUrl.isEmpty()) {
        this.avatarUrl = Optional.empty();
      }
      else {
        this.avatarUrl = Optional.of(avatarUrl.get());
      }
      return this;
    }

    @JsonSetter(
        value = "voiceShowTranscript",
        nulls = Nulls.SKIP
    )
    public Builder voiceShowTranscript(Optional<Boolean> voiceShowTranscript) {
      this.voiceShowTranscript = voiceShowTranscript;
      return this;
    }

    public Builder voiceShowTranscript(Boolean voiceShowTranscript) {
      this.voiceShowTranscript = Optional.ofNullable(voiceShowTranscript);
      return this;
    }

    @JsonSetter(
        value = "consentRequired",
        nulls = Nulls.SKIP
    )
    public Builder consentRequired(Optional<Boolean> consentRequired) {
      this.consentRequired = consentRequired;
      return this;
    }

    public Builder consentRequired(Boolean consentRequired) {
      this.consentRequired = Optional.ofNullable(consentRequired);
      return this;
    }

    public GetAgentWidgetConfigResponseData build() {
      return new GetAgentWidgetConfigResponseData(assistantId, position, size, borderRadius, mode, theme, baseColor, accentColor, title, startButtonText, endButtonText, avatarUrl, voiceShowTranscript, consentRequired, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
