/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.smallest.resources.atoms.agents.types;

import ai.smallest.core.ObjectMappers;
import ai.smallest.resources.atoms.types.AgentDto;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Double;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = ListAgentsAgentsResponseData.Builder.class
)
public final class ListAgentsAgentsResponseData {
  private final Optional<List<AgentDto>> agents;

  private final Optional<Double> total;

  private final Map<String, Object> additionalProperties;

  private ListAgentsAgentsResponseData(Optional<List<AgentDto>> agents, Optional<Double> total,
      Map<String, Object> additionalProperties) {
    this.agents = agents;
    this.total = total;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("agents")
  public Optional<List<AgentDto>> getAgents() {
    return agents;
  }

  /**
   * @return Total number of agents
   */
  @JsonProperty("total")
  public Optional<Double> getTotal() {
    return total;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof ListAgentsAgentsResponseData && equalTo((ListAgentsAgentsResponseData) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(ListAgentsAgentsResponseData other) {
    return agents.equals(other.agents) && total.equals(other.total);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.agents, this.total);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<List<AgentDto>> agents = Optional.empty();

    private Optional<Double> total = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(ListAgentsAgentsResponseData other) {
      agents(other.getAgents());
      total(other.getTotal());
      return this;
    }

    @JsonSetter(
        value = "agents",
        nulls = Nulls.SKIP
    )
    public Builder agents(Optional<List<AgentDto>> agents) {
      this.agents = agents;
      return this;
    }

    public Builder agents(List<AgentDto> agents) {
      this.agents = Optional.ofNullable(agents);
      return this;
    }

    /**
     * <p>Total number of agents</p>
     */
    @JsonSetter(
        value = "total",
        nulls = Nulls.SKIP
    )
    public Builder total(Optional<Double> total) {
      this.total = total;
      return this;
    }

    public Builder total(Double total) {
      this.total = Optional.ofNullable(total);
      return this;
    }

    public ListAgentsAgentsResponseData build() {
      return new ListAgentsAgentsResponseData(agents, total, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
