/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.smallest.resources.waves.pulsesttstreaming;

import ai.smallest.core.ClientOptions;
import ai.smallest.resources.waves.pulsesttstreaming.websocket.PulseSttStreamingWebSocketClient;

public class AsyncPulseSttStreamingClient {
  protected final ClientOptions clientOptions;

  public AsyncPulseSttStreamingClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
  }

  /**
   * Creates a new WebSocket client for the pulseSttStreaming channel.
   */
  public PulseSttStreamingWebSocketClient pulseSttStreamingWebSocket() {
    return new PulseSttStreamingWebSocketClient(clientOptions);
  }
}
