/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.smallest.resources.atoms.analytics.types;

import ai.smallest.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Double;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = GetAttemptCohortResponseDataCohortsItem.Builder.class
)
public final class GetAttemptCohortResponseDataCohortsItem {
  private final Optional<Double> attemptNumber;

  private final Optional<Double> totalCalls;

  private final Optional<Double> answeredCalls;

  private final Optional<Double> pickupRate;

  private final Optional<Double> cumulativeAnswered;

  private final Optional<Double> cumulativeRate;

  private final Optional<Double> marginalGain;

  private final Map<String, Object> additionalProperties;

  private GetAttemptCohortResponseDataCohortsItem(Optional<Double> attemptNumber,
      Optional<Double> totalCalls, Optional<Double> answeredCalls, Optional<Double> pickupRate,
      Optional<Double> cumulativeAnswered, Optional<Double> cumulativeRate,
      Optional<Double> marginalGain, Map<String, Object> additionalProperties) {
    this.attemptNumber = attemptNumber;
    this.totalCalls = totalCalls;
    this.answeredCalls = answeredCalls;
    this.pickupRate = pickupRate;
    this.cumulativeAnswered = cumulativeAnswered;
    this.cumulativeRate = cumulativeRate;
    this.marginalGain = marginalGain;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("attemptNumber")
  public Optional<Double> getAttemptNumber() {
    return attemptNumber;
  }

  @JsonProperty("totalCalls")
  public Optional<Double> getTotalCalls() {
    return totalCalls;
  }

  @JsonProperty("answeredCalls")
  public Optional<Double> getAnsweredCalls() {
    return answeredCalls;
  }

  @JsonProperty("pickupRate")
  public Optional<Double> getPickupRate() {
    return pickupRate;
  }

  @JsonProperty("cumulativeAnswered")
  public Optional<Double> getCumulativeAnswered() {
    return cumulativeAnswered;
  }

  @JsonProperty("cumulativeRate")
  public Optional<Double> getCumulativeRate() {
    return cumulativeRate;
  }

  @JsonProperty("marginalGain")
  public Optional<Double> getMarginalGain() {
    return marginalGain;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof GetAttemptCohortResponseDataCohortsItem && equalTo((GetAttemptCohortResponseDataCohortsItem) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(GetAttemptCohortResponseDataCohortsItem other) {
    return attemptNumber.equals(other.attemptNumber) && totalCalls.equals(other.totalCalls) && answeredCalls.equals(other.answeredCalls) && pickupRate.equals(other.pickupRate) && cumulativeAnswered.equals(other.cumulativeAnswered) && cumulativeRate.equals(other.cumulativeRate) && marginalGain.equals(other.marginalGain);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.attemptNumber, this.totalCalls, this.answeredCalls, this.pickupRate, this.cumulativeAnswered, this.cumulativeRate, this.marginalGain);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<Double> attemptNumber = Optional.empty();

    private Optional<Double> totalCalls = Optional.empty();

    private Optional<Double> answeredCalls = Optional.empty();

    private Optional<Double> pickupRate = Optional.empty();

    private Optional<Double> cumulativeAnswered = Optional.empty();

    private Optional<Double> cumulativeRate = Optional.empty();

    private Optional<Double> marginalGain = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(GetAttemptCohortResponseDataCohortsItem other) {
      attemptNumber(other.getAttemptNumber());
      totalCalls(other.getTotalCalls());
      answeredCalls(other.getAnsweredCalls());
      pickupRate(other.getPickupRate());
      cumulativeAnswered(other.getCumulativeAnswered());
      cumulativeRate(other.getCumulativeRate());
      marginalGain(other.getMarginalGain());
      return this;
    }

    @JsonSetter(
        value = "attemptNumber",
        nulls = Nulls.SKIP
    )
    public Builder attemptNumber(Optional<Double> attemptNumber) {
      this.attemptNumber = attemptNumber;
      return this;
    }

    public Builder attemptNumber(Double attemptNumber) {
      this.attemptNumber = Optional.ofNullable(attemptNumber);
      return this;
    }

    @JsonSetter(
        value = "totalCalls",
        nulls = Nulls.SKIP
    )
    public Builder totalCalls(Optional<Double> totalCalls) {
      this.totalCalls = totalCalls;
      return this;
    }

    public Builder totalCalls(Double totalCalls) {
      this.totalCalls = Optional.ofNullable(totalCalls);
      return this;
    }

    @JsonSetter(
        value = "answeredCalls",
        nulls = Nulls.SKIP
    )
    public Builder answeredCalls(Optional<Double> answeredCalls) {
      this.answeredCalls = answeredCalls;
      return this;
    }

    public Builder answeredCalls(Double answeredCalls) {
      this.answeredCalls = Optional.ofNullable(answeredCalls);
      return this;
    }

    @JsonSetter(
        value = "pickupRate",
        nulls = Nulls.SKIP
    )
    public Builder pickupRate(Optional<Double> pickupRate) {
      this.pickupRate = pickupRate;
      return this;
    }

    public Builder pickupRate(Double pickupRate) {
      this.pickupRate = Optional.ofNullable(pickupRate);
      return this;
    }

    @JsonSetter(
        value = "cumulativeAnswered",
        nulls = Nulls.SKIP
    )
    public Builder cumulativeAnswered(Optional<Double> cumulativeAnswered) {
      this.cumulativeAnswered = cumulativeAnswered;
      return this;
    }

    public Builder cumulativeAnswered(Double cumulativeAnswered) {
      this.cumulativeAnswered = Optional.ofNullable(cumulativeAnswered);
      return this;
    }

    @JsonSetter(
        value = "cumulativeRate",
        nulls = Nulls.SKIP
    )
    public Builder cumulativeRate(Optional<Double> cumulativeRate) {
      this.cumulativeRate = cumulativeRate;
      return this;
    }

    public Builder cumulativeRate(Double cumulativeRate) {
      this.cumulativeRate = Optional.ofNullable(cumulativeRate);
      return this;
    }

    @JsonSetter(
        value = "marginalGain",
        nulls = Nulls.SKIP
    )
    public Builder marginalGain(Optional<Double> marginalGain) {
      this.marginalGain = marginalGain;
      return this;
    }

    public Builder marginalGain(Double marginalGain) {
      this.marginalGain = Optional.ofNullable(marginalGain);
      return this;
    }

    public GetAttemptCohortResponseDataCohortsItem build() {
      return new GetAttemptCohortResponseDataCohortsItem(attemptNumber, totalCalls, answeredCalls, pickupRate, cumulativeAnswered, cumulativeRate, marginalGain, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
