/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.smallest.resources.atoms.analytics.types;

import ai.smallest.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Boolean;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = GetCallCountsLogResponse.Builder.class
)
public final class GetCallCountsLogResponse {
  private final Optional<Boolean> success;

  private final Optional<GetCallCountsLogResponseData> data;

  private final Map<String, Object> additionalProperties;

  private GetCallCountsLogResponse(Optional<Boolean> success,
      Optional<GetCallCountsLogResponseData> data, Map<String, Object> additionalProperties) {
    this.success = success;
    this.data = data;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("success")
  public Optional<Boolean> getSuccess() {
    return success;
  }

  @JsonProperty("data")
  public Optional<GetCallCountsLogResponseData> getData() {
    return data;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof GetCallCountsLogResponse && equalTo((GetCallCountsLogResponse) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(GetCallCountsLogResponse other) {
    return success.equals(other.success) && data.equals(other.data);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.success, this.data);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<Boolean> success = Optional.empty();

    private Optional<GetCallCountsLogResponseData> data = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(GetCallCountsLogResponse other) {
      success(other.getSuccess());
      data(other.getData());
      return this;
    }

    @JsonSetter(
        value = "success",
        nulls = Nulls.SKIP
    )
    public Builder success(Optional<Boolean> success) {
      this.success = success;
      return this;
    }

    public Builder success(Boolean success) {
      this.success = Optional.ofNullable(success);
      return this;
    }

    @JsonSetter(
        value = "data",
        nulls = Nulls.SKIP
    )
    public Builder data(Optional<GetCallCountsLogResponseData> data) {
      this.data = data;
      return this;
    }

    public Builder data(GetCallCountsLogResponseData data) {
      this.data = Optional.ofNullable(data);
      return this;
    }

    public GetCallCountsLogResponse build() {
      return new GetCallCountsLogResponse(success, data, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
