/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.smallest.resources.atoms.analytics.types;

import ai.smallest.core.ObjectMappers;
import ai.smallest.resources.atoms.types.AnalyticsDateRange;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = GetWeeklyTrendsResponseData.Builder.class
)
public final class GetWeeklyTrendsResponseData {
  private final Optional<String> orgId;

  private final Optional<List<GetWeeklyTrendsResponseDataWeeksItem>> weeks;

  private final Optional<AnalyticsDateRange> period;

  private final Map<String, Object> additionalProperties;

  private GetWeeklyTrendsResponseData(Optional<String> orgId,
      Optional<List<GetWeeklyTrendsResponseDataWeeksItem>> weeks,
      Optional<AnalyticsDateRange> period, Map<String, Object> additionalProperties) {
    this.orgId = orgId;
    this.weeks = weeks;
    this.period = period;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("orgId")
  public Optional<String> getOrgId() {
    return orgId;
  }

  @JsonProperty("weeks")
  public Optional<List<GetWeeklyTrendsResponseDataWeeksItem>> getWeeks() {
    return weeks;
  }

  @JsonProperty("period")
  public Optional<AnalyticsDateRange> getPeriod() {
    return period;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof GetWeeklyTrendsResponseData && equalTo((GetWeeklyTrendsResponseData) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(GetWeeklyTrendsResponseData other) {
    return orgId.equals(other.orgId) && weeks.equals(other.weeks) && period.equals(other.period);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.orgId, this.weeks, this.period);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<String> orgId = Optional.empty();

    private Optional<List<GetWeeklyTrendsResponseDataWeeksItem>> weeks = Optional.empty();

    private Optional<AnalyticsDateRange> period = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(GetWeeklyTrendsResponseData other) {
      orgId(other.getOrgId());
      weeks(other.getWeeks());
      period(other.getPeriod());
      return this;
    }

    @JsonSetter(
        value = "orgId",
        nulls = Nulls.SKIP
    )
    public Builder orgId(Optional<String> orgId) {
      this.orgId = orgId;
      return this;
    }

    public Builder orgId(String orgId) {
      this.orgId = Optional.ofNullable(orgId);
      return this;
    }

    @JsonSetter(
        value = "weeks",
        nulls = Nulls.SKIP
    )
    public Builder weeks(Optional<List<GetWeeklyTrendsResponseDataWeeksItem>> weeks) {
      this.weeks = weeks;
      return this;
    }

    public Builder weeks(List<GetWeeklyTrendsResponseDataWeeksItem> weeks) {
      this.weeks = Optional.ofNullable(weeks);
      return this;
    }

    @JsonSetter(
        value = "period",
        nulls = Nulls.SKIP
    )
    public Builder period(Optional<AnalyticsDateRange> period) {
      this.period = period;
      return this;
    }

    public Builder period(AnalyticsDateRange period) {
      this.period = Optional.ofNullable(period);
      return this;
    }

    public GetWeeklyTrendsResponseData build() {
      return new GetWeeklyTrendsResponseData(orgId, weeks, period, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
