/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.smallest.resources.atoms.compliance;

import ai.smallest.core.ClientOptions;
import ai.smallest.core.RequestOptions;
import ai.smallest.resources.atoms.compliance.requests.GetComplianceRequirementsRequest;
import ai.smallest.resources.atoms.compliance.requests.GetComplianceStatusRequest;
import ai.smallest.resources.atoms.compliance.requests.PostComplianceApplicationsIdRefreshRequest;
import ai.smallest.resources.atoms.compliance.requests.ResubmitComplianceRequest;
import ai.smallest.resources.atoms.compliance.requests.SubmitComplianceRequest;
import ai.smallest.resources.atoms.compliance.types.GetComplianceRequirementsResponse;
import ai.smallest.resources.atoms.compliance.types.GetComplianceStatusResponse;
import ai.smallest.resources.atoms.compliance.types.PostComplianceApplicationsIdRefreshResponse;
import ai.smallest.resources.atoms.compliance.types.ResubmitComplianceResponse;
import ai.smallest.resources.atoms.compliance.types.SubmitComplianceResponse;
import java.io.File;
import java.lang.String;

public class ComplianceClient {
  protected final ClientOptions clientOptions;

  private final RawComplianceClient rawClient;

  public ComplianceClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new RawComplianceClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public RawComplianceClient withRawResponse() {
    return this.rawClient;
  }

  /**
   * Returns the current compliance status for a given country, number type, and user type.
   * This is the single endpoint the frontend uses to determine which step to render
   * (form, submitted, accepted, rejected, expired, or suspended).
   */
  public GetComplianceStatusResponse getComplianceStatus(GetComplianceStatusRequest request) {
    return this.rawClient.getComplianceStatus(request).body();
  }

  /**
   * Returns the current compliance status for a given country, number type, and user type.
   * This is the single endpoint the frontend uses to determine which step to render
   * (form, submitted, accepted, rejected, expired, or suspended).
   */
  public GetComplianceStatusResponse getComplianceStatus(GetComplianceStatusRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.getComplianceStatus(request, requestOptions).body();
  }

  /**
   * Discover what documents are required for a given country, number type, and user type.
   * Results are cached for 1 hour. Returns an empty <code>documentTypes</code> array if no compliance
   * is needed for the given combination.
   */
  public GetComplianceRequirementsResponse getComplianceRequirements(
      GetComplianceRequirementsRequest request) {
    return this.rawClient.getComplianceRequirements(request).body();
  }

  /**
   * Discover what documents are required for a given country, number type, and user type.
   * Results are cached for 1 hour. Returns an empty <code>documentTypes</code> array if no compliance
   * is needed for the given combination.
   */
  public GetComplianceRequirementsResponse getComplianceRequirements(
      GetComplianceRequirementsRequest request, RequestOptions requestOptions) {
    return this.rawClient.getComplianceRequirements(request, requestOptions).body();
  }

  /**
   * Submit a new compliance application with end-user details and supporting documents.
   * One application is allowed per organization per country per number type per user type.
   * <p>The request uses <code>multipart/form-data</code> because documents are uploaded inline.
   * The <code>endUser</code> and <code>documents</code> fields are JSON strings embedded in the form data.</p>
   */
  public SubmitComplianceResponse submit(File files, SubmitComplianceRequest request) {
    return this.rawClient.submit(files, request).body();
  }

  /**
   * Submit a new compliance application with end-user details and supporting documents.
   * One application is allowed per organization per country per number type per user type.
   * <p>The request uses <code>multipart/form-data</code> because documents are uploaded inline.
   * The <code>endUser</code> and <code>documents</code> fields are JSON strings embedded in the form data.</p>
   */
  public SubmitComplianceResponse submit(File files, SubmitComplianceRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.submit(files, request, requestOptions).body();
  }

  /**
   * Resubmit a previously rejected compliance application with corrected documents.
   * Only applications in <code>rejected</code> status can be resubmitted. All documents must be
   * re-uploaded — partial updates are not supported.
   * <p>File/document count must match exactly. Mismatch returns 400 with message <code>&quot;Expected X files, got Y&quot;</code>.</p>
   */
  public ResubmitComplianceResponse resubmit(String id, File files,
      ResubmitComplianceRequest request) {
    return this.rawClient.resubmit(id, files, request).body();
  }

  /**
   * Resubmit a previously rejected compliance application with corrected documents.
   * Only applications in <code>rejected</code> status can be resubmitted. All documents must be
   * re-uploaded — partial updates are not supported.
   * <p>File/document count must match exactly. Mismatch returns 400 with message <code>&quot;Expected X files, got Y&quot;</code>.</p>
   */
  public ResubmitComplianceResponse resubmit(String id, File files,
      ResubmitComplianceRequest request, RequestOptions requestOptions) {
    return this.rawClient.resubmit(id, files, request, requestOptions).body();
  }

  /**
   * Manually poll Plivo for the latest status of a compliance application.
   * Use this as a fallback when webhooks are delayed. The frontend enforces a
   * 60-second cooldown between refreshes.
   */
  public PostComplianceApplicationsIdRefreshResponse refreshComplianceApplicationStatus(String id) {
    return this.rawClient.refreshComplianceApplicationStatus(id).body();
  }

  /**
   * Manually poll Plivo for the latest status of a compliance application.
   * Use this as a fallback when webhooks are delayed. The frontend enforces a
   * 60-second cooldown between refreshes.
   */
  public PostComplianceApplicationsIdRefreshResponse refreshComplianceApplicationStatus(String id,
      RequestOptions requestOptions) {
    return this.rawClient.refreshComplianceApplicationStatus(id, requestOptions).body();
  }

  /**
   * Manually poll Plivo for the latest status of a compliance application.
   * Use this as a fallback when webhooks are delayed. The frontend enforces a
   * 60-second cooldown between refreshes.
   */
  public PostComplianceApplicationsIdRefreshResponse refreshComplianceApplicationStatus(String id,
      PostComplianceApplicationsIdRefreshRequest request) {
    return this.rawClient.refreshComplianceApplicationStatus(id, request).body();
  }

  /**
   * Manually poll Plivo for the latest status of a compliance application.
   * Use this as a fallback when webhooks are delayed. The frontend enforces a
   * 60-second cooldown between refreshes.
   */
  public PostComplianceApplicationsIdRefreshResponse refreshComplianceApplicationStatus(String id,
      PostComplianceApplicationsIdRefreshRequest request, RequestOptions requestOptions) {
    return this.rawClient.refreshComplianceApplicationStatus(id, request, requestOptions).body();
  }
}
