/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.smallest.resources.waves.tts.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class TtsRequestMessageNumberPronunciationLanguage {
  public static final TtsRequestMessageNumberPronunciationLanguage EN = new TtsRequestMessageNumberPronunciationLanguage(Value.EN, "en");

  public static final TtsRequestMessageNumberPronunciationLanguage ZH = new TtsRequestMessageNumberPronunciationLanguage(Value.ZH, "zh");

  public static final TtsRequestMessageNumberPronunciationLanguage HI = new TtsRequestMessageNumberPronunciationLanguage(Value.HI, "hi");

  public static final TtsRequestMessageNumberPronunciationLanguage ML = new TtsRequestMessageNumberPronunciationLanguage(Value.ML, "ml");

  public static final TtsRequestMessageNumberPronunciationLanguage GU = new TtsRequestMessageNumberPronunciationLanguage(Value.GU, "gu");

  public static final TtsRequestMessageNumberPronunciationLanguage OR = new TtsRequestMessageNumberPronunciationLanguage(Value.OR, "or");

  public static final TtsRequestMessageNumberPronunciationLanguage ID = new TtsRequestMessageNumberPronunciationLanguage(Value.ID, "id");

  public static final TtsRequestMessageNumberPronunciationLanguage TR = new TtsRequestMessageNumberPronunciationLanguage(Value.TR, "tr");

  public static final TtsRequestMessageNumberPronunciationLanguage FI = new TtsRequestMessageNumberPronunciationLanguage(Value.FI, "fi");

  public static final TtsRequestMessageNumberPronunciationLanguage ES = new TtsRequestMessageNumberPronunciationLanguage(Value.ES, "es");

  public static final TtsRequestMessageNumberPronunciationLanguage PL = new TtsRequestMessageNumberPronunciationLanguage(Value.PL, "pl");

  public static final TtsRequestMessageNumberPronunciationLanguage DE = new TtsRequestMessageNumberPronunciationLanguage(Value.DE, "de");

  public static final TtsRequestMessageNumberPronunciationLanguage KN = new TtsRequestMessageNumberPronunciationLanguage(Value.KN, "kn");

  public static final TtsRequestMessageNumberPronunciationLanguage MS = new TtsRequestMessageNumberPronunciationLanguage(Value.MS, "ms");

  public static final TtsRequestMessageNumberPronunciationLanguage MR = new TtsRequestMessageNumberPronunciationLanguage(Value.MR, "mr");

  public static final TtsRequestMessageNumberPronunciationLanguage TA = new TtsRequestMessageNumberPronunciationLanguage(Value.TA, "ta");

  public static final TtsRequestMessageNumberPronunciationLanguage RU = new TtsRequestMessageNumberPronunciationLanguage(Value.RU, "ru");

  public static final TtsRequestMessageNumberPronunciationLanguage JA = new TtsRequestMessageNumberPronunciationLanguage(Value.JA, "ja");

  public static final TtsRequestMessageNumberPronunciationLanguage KO = new TtsRequestMessageNumberPronunciationLanguage(Value.KO, "ko");

  public static final TtsRequestMessageNumberPronunciationLanguage TE = new TtsRequestMessageNumberPronunciationLanguage(Value.TE, "te");

  public static final TtsRequestMessageNumberPronunciationLanguage VI = new TtsRequestMessageNumberPronunciationLanguage(Value.VI, "vi");

  public static final TtsRequestMessageNumberPronunciationLanguage PT = new TtsRequestMessageNumberPronunciationLanguage(Value.PT, "pt");

  public static final TtsRequestMessageNumberPronunciationLanguage AR = new TtsRequestMessageNumberPronunciationLanguage(Value.AR, "ar");

  public static final TtsRequestMessageNumberPronunciationLanguage FR = new TtsRequestMessageNumberPronunciationLanguage(Value.FR, "fr");

  public static final TtsRequestMessageNumberPronunciationLanguage NO = new TtsRequestMessageNumberPronunciationLanguage(Value.NO, "no");

  public static final TtsRequestMessageNumberPronunciationLanguage PA = new TtsRequestMessageNumberPronunciationLanguage(Value.PA, "pa");

  public static final TtsRequestMessageNumberPronunciationLanguage BN = new TtsRequestMessageNumberPronunciationLanguage(Value.BN, "bn");

  public static final TtsRequestMessageNumberPronunciationLanguage IT = new TtsRequestMessageNumberPronunciationLanguage(Value.IT, "it");

  public static final TtsRequestMessageNumberPronunciationLanguage EL = new TtsRequestMessageNumberPronunciationLanguage(Value.EL, "el");

  private final Value value;

  private final String string;

  TtsRequestMessageNumberPronunciationLanguage(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof TtsRequestMessageNumberPronunciationLanguage && this.string.equals(((TtsRequestMessageNumberPronunciationLanguage) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case EN:
        return visitor.visitEn();
      case ZH:
        return visitor.visitZh();
      case HI:
        return visitor.visitHi();
      case ML:
        return visitor.visitMl();
      case GU:
        return visitor.visitGu();
      case OR:
        return visitor.visitOr();
      case ID:
        return visitor.visitId();
      case TR:
        return visitor.visitTr();
      case FI:
        return visitor.visitFi();
      case ES:
        return visitor.visitEs();
      case PL:
        return visitor.visitPl();
      case DE:
        return visitor.visitDe();
      case KN:
        return visitor.visitKn();
      case MS:
        return visitor.visitMs();
      case MR:
        return visitor.visitMr();
      case TA:
        return visitor.visitTa();
      case RU:
        return visitor.visitRu();
      case JA:
        return visitor.visitJa();
      case KO:
        return visitor.visitKo();
      case TE:
        return visitor.visitTe();
      case VI:
        return visitor.visitVi();
      case PT:
        return visitor.visitPt();
      case AR:
        return visitor.visitAr();
      case FR:
        return visitor.visitFr();
      case NO:
        return visitor.visitNo();
      case PA:
        return visitor.visitPa();
      case BN:
        return visitor.visitBn();
      case IT:
        return visitor.visitIt();
      case EL:
        return visitor.visitEl();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static TtsRequestMessageNumberPronunciationLanguage valueOf(String value) {
    switch (value) {
      case "en":
        return EN;
      case "zh":
        return ZH;
      case "hi":
        return HI;
      case "ml":
        return ML;
      case "gu":
        return GU;
      case "or":
        return OR;
      case "id":
        return ID;
      case "tr":
        return TR;
      case "fi":
        return FI;
      case "es":
        return ES;
      case "pl":
        return PL;
      case "de":
        return DE;
      case "kn":
        return KN;
      case "ms":
        return MS;
      case "mr":
        return MR;
      case "ta":
        return TA;
      case "ru":
        return RU;
      case "ja":
        return JA;
      case "ko":
        return KO;
      case "te":
        return TE;
      case "vi":
        return VI;
      case "pt":
        return PT;
      case "ar":
        return AR;
      case "fr":
        return FR;
      case "no":
        return NO;
      case "pa":
        return PA;
      case "bn":
        return BN;
      case "it":
        return IT;
      case "el":
        return EL;
      default:
        return new TtsRequestMessageNumberPronunciationLanguage(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    EN,

    HI,

    MR,

    KN,

    TA,

    BN,

    GU,

    TE,

    ML,

    PA,

    OR,

    ES,

    DE,

    FR,

    IT,

    PT,

    RU,

    EL,

    FI,

    NO,

    PL,

    AR,

    ZH,

    ID,

    JA,

    KO,

    MS,

    TR,

    VI,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitEn();

    T visitHi();

    T visitMr();

    T visitKn();

    T visitTa();

    T visitBn();

    T visitGu();

    T visitTe();

    T visitMl();

    T visitPa();

    T visitOr();

    T visitEs();

    T visitDe();

    T visitFr();

    T visitIt();

    T visitPt();

    T visitRu();

    T visitEl();

    T visitFi();

    T visitNo();

    T visitPl();

    T visitAr();

    T visitZh();

    T visitId();

    T visitJa();

    T visitKo();

    T visitMs();

    T visitTr();

    T visitVi();

    T visitUnknown(String unknownType);
  }
}
