/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.smallest.resources.atoms.campaigns.types;

import ai.smallest.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = CreateCampaignsResponseData.Builder.class
)
public final class CreateCampaignsResponseData {
  private final Optional<String> id;

  private final Optional<String> name;

  private final Optional<String> description;

  private final Optional<String> organization;

  private final Optional<String> agentId;

  private final Optional<String> createdBy;

  private final Optional<String> audienceId;

  private final Optional<Integer> participantsCount;

  private final Optional<OffsetDateTime> scheduledAt;

  private final Optional<Integer> maxRetries;

  private final Optional<Integer> retryDelay;

  private final Optional<Integer> retryAttempts;

  private final Optional<CreateCampaignsResponseDataStatus> status;

  private final Optional<OffsetDateTime> createdAt;

  private final Optional<OffsetDateTime> updatedAt;

  private final Map<String, Object> additionalProperties;

  private CreateCampaignsResponseData(Optional<String> id, Optional<String> name,
      Optional<String> description, Optional<String> organization, Optional<String> agentId,
      Optional<String> createdBy, Optional<String> audienceId, Optional<Integer> participantsCount,
      Optional<OffsetDateTime> scheduledAt, Optional<Integer> maxRetries,
      Optional<Integer> retryDelay, Optional<Integer> retryAttempts,
      Optional<CreateCampaignsResponseDataStatus> status, Optional<OffsetDateTime> createdAt,
      Optional<OffsetDateTime> updatedAt, Map<String, Object> additionalProperties) {
    this.id = id;
    this.name = name;
    this.description = description;
    this.organization = organization;
    this.agentId = agentId;
    this.createdBy = createdBy;
    this.audienceId = audienceId;
    this.participantsCount = participantsCount;
    this.scheduledAt = scheduledAt;
    this.maxRetries = maxRetries;
    this.retryDelay = retryDelay;
    this.retryAttempts = retryAttempts;
    this.status = status;
    this.createdAt = createdAt;
    this.updatedAt = updatedAt;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return The unique identifier for the campaign
   */
  @JsonProperty("_id")
  public Optional<String> getId() {
    return id;
  }

  /**
   * @return The name of the campaign
   */
  @JsonProperty("name")
  public Optional<String> getName() {
    return name;
  }

  /**
   * @return The description of the campaign
   */
  @JsonProperty("description")
  public Optional<String> getDescription() {
    return description;
  }

  /**
   * @return The ID of the organization
   */
  @JsonProperty("organization")
  public Optional<String> getOrganization() {
    return organization;
  }

  /**
   * @return Raw ObjectId of the agent (not a nested object)
   */
  @JsonProperty("agentId")
  public Optional<String> getAgentId() {
    return agentId;
  }

  /**
   * @return The ID of the user who created the campaign
   */
  @JsonProperty("createdBy")
  public Optional<String> getCreatedBy() {
    return createdBy;
  }

  /**
   * @return Raw ObjectId of the audience (not a nested object)
   */
  @JsonProperty("audienceId")
  public Optional<String> getAudienceId() {
    return audienceId;
  }

  /**
   * @return The number of participants in the campaign
   */
  @JsonProperty("participantsCount")
  public Optional<Integer> getParticipantsCount() {
    return participantsCount;
  }

  /**
   * @return The scheduled start time, if provided at creation.
   */
  @JsonProperty("scheduledAt")
  public Optional<OffsetDateTime> getScheduledAt() {
    return scheduledAt;
  }

  /**
   * @return Maximum retries per failed call (echoes request).
   */
  @JsonProperty("maxRetries")
  public Optional<Integer> getMaxRetries() {
    return maxRetries;
  }

  /**
   * @return Delay in minutes between retry attempts (echoes request).
   */
  @JsonProperty("retryDelay")
  public Optional<Integer> getRetryDelay() {
    return retryDelay;
  }

  /**
   * @return Number of retries attempted so far across the campaign.
   */
  @JsonProperty("retryAttempts")
  public Optional<Integer> getRetryAttempts() {
    return retryAttempts;
  }

  /**
   * @return Current campaign status.
   */
  @JsonProperty("status")
  public Optional<CreateCampaignsResponseDataStatus> getStatus() {
    return status;
  }

  /**
   * @return The date and time when the campaign was created
   */
  @JsonProperty("createdAt")
  public Optional<OffsetDateTime> getCreatedAt() {
    return createdAt;
  }

  /**
   * @return The date and time when the campaign was last updated
   */
  @JsonProperty("updatedAt")
  public Optional<OffsetDateTime> getUpdatedAt() {
    return updatedAt;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof CreateCampaignsResponseData && equalTo((CreateCampaignsResponseData) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(CreateCampaignsResponseData other) {
    return id.equals(other.id) && name.equals(other.name) && description.equals(other.description) && organization.equals(other.organization) && agentId.equals(other.agentId) && createdBy.equals(other.createdBy) && audienceId.equals(other.audienceId) && participantsCount.equals(other.participantsCount) && scheduledAt.equals(other.scheduledAt) && maxRetries.equals(other.maxRetries) && retryDelay.equals(other.retryDelay) && retryAttempts.equals(other.retryAttempts) && status.equals(other.status) && createdAt.equals(other.createdAt) && updatedAt.equals(other.updatedAt);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.id, this.name, this.description, this.organization, this.agentId, this.createdBy, this.audienceId, this.participantsCount, this.scheduledAt, this.maxRetries, this.retryDelay, this.retryAttempts, this.status, this.createdAt, this.updatedAt);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<String> id = Optional.empty();

    private Optional<String> name = Optional.empty();

    private Optional<String> description = Optional.empty();

    private Optional<String> organization = Optional.empty();

    private Optional<String> agentId = Optional.empty();

    private Optional<String> createdBy = Optional.empty();

    private Optional<String> audienceId = Optional.empty();

    private Optional<Integer> participantsCount = Optional.empty();

    private Optional<OffsetDateTime> scheduledAt = Optional.empty();

    private Optional<Integer> maxRetries = Optional.empty();

    private Optional<Integer> retryDelay = Optional.empty();

    private Optional<Integer> retryAttempts = Optional.empty();

    private Optional<CreateCampaignsResponseDataStatus> status = Optional.empty();

    private Optional<OffsetDateTime> createdAt = Optional.empty();

    private Optional<OffsetDateTime> updatedAt = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(CreateCampaignsResponseData other) {
      id(other.getId());
      name(other.getName());
      description(other.getDescription());
      organization(other.getOrganization());
      agentId(other.getAgentId());
      createdBy(other.getCreatedBy());
      audienceId(other.getAudienceId());
      participantsCount(other.getParticipantsCount());
      scheduledAt(other.getScheduledAt());
      maxRetries(other.getMaxRetries());
      retryDelay(other.getRetryDelay());
      retryAttempts(other.getRetryAttempts());
      status(other.getStatus());
      createdAt(other.getCreatedAt());
      updatedAt(other.getUpdatedAt());
      return this;
    }

    /**
     * <p>The unique identifier for the campaign</p>
     */
    @JsonSetter(
        value = "_id",
        nulls = Nulls.SKIP
    )
    public Builder id(Optional<String> id) {
      this.id = id;
      return this;
    }

    public Builder id(String id) {
      this.id = Optional.ofNullable(id);
      return this;
    }

    /**
     * <p>The name of the campaign</p>
     */
    @JsonSetter(
        value = "name",
        nulls = Nulls.SKIP
    )
    public Builder name(Optional<String> name) {
      this.name = name;
      return this;
    }

    public Builder name(String name) {
      this.name = Optional.ofNullable(name);
      return this;
    }

    /**
     * <p>The description of the campaign</p>
     */
    @JsonSetter(
        value = "description",
        nulls = Nulls.SKIP
    )
    public Builder description(Optional<String> description) {
      this.description = description;
      return this;
    }

    public Builder description(String description) {
      this.description = Optional.ofNullable(description);
      return this;
    }

    /**
     * <p>The ID of the organization</p>
     */
    @JsonSetter(
        value = "organization",
        nulls = Nulls.SKIP
    )
    public Builder organization(Optional<String> organization) {
      this.organization = organization;
      return this;
    }

    public Builder organization(String organization) {
      this.organization = Optional.ofNullable(organization);
      return this;
    }

    /**
     * <p>Raw ObjectId of the agent (not a nested object)</p>
     */
    @JsonSetter(
        value = "agentId",
        nulls = Nulls.SKIP
    )
    public Builder agentId(Optional<String> agentId) {
      this.agentId = agentId;
      return this;
    }

    public Builder agentId(String agentId) {
      this.agentId = Optional.ofNullable(agentId);
      return this;
    }

    /**
     * <p>The ID of the user who created the campaign</p>
     */
    @JsonSetter(
        value = "createdBy",
        nulls = Nulls.SKIP
    )
    public Builder createdBy(Optional<String> createdBy) {
      this.createdBy = createdBy;
      return this;
    }

    public Builder createdBy(String createdBy) {
      this.createdBy = Optional.ofNullable(createdBy);
      return this;
    }

    /**
     * <p>Raw ObjectId of the audience (not a nested object)</p>
     */
    @JsonSetter(
        value = "audienceId",
        nulls = Nulls.SKIP
    )
    public Builder audienceId(Optional<String> audienceId) {
      this.audienceId = audienceId;
      return this;
    }

    public Builder audienceId(String audienceId) {
      this.audienceId = Optional.ofNullable(audienceId);
      return this;
    }

    /**
     * <p>The number of participants in the campaign</p>
     */
    @JsonSetter(
        value = "participantsCount",
        nulls = Nulls.SKIP
    )
    public Builder participantsCount(Optional<Integer> participantsCount) {
      this.participantsCount = participantsCount;
      return this;
    }

    public Builder participantsCount(Integer participantsCount) {
      this.participantsCount = Optional.ofNullable(participantsCount);
      return this;
    }

    /**
     * <p>The scheduled start time, if provided at creation.</p>
     */
    @JsonSetter(
        value = "scheduledAt",
        nulls = Nulls.SKIP
    )
    public Builder scheduledAt(Optional<OffsetDateTime> scheduledAt) {
      this.scheduledAt = scheduledAt;
      return this;
    }

    public Builder scheduledAt(OffsetDateTime scheduledAt) {
      this.scheduledAt = Optional.ofNullable(scheduledAt);
      return this;
    }

    /**
     * <p>Maximum retries per failed call (echoes request).</p>
     */
    @JsonSetter(
        value = "maxRetries",
        nulls = Nulls.SKIP
    )
    public Builder maxRetries(Optional<Integer> maxRetries) {
      this.maxRetries = maxRetries;
      return this;
    }

    public Builder maxRetries(Integer maxRetries) {
      this.maxRetries = Optional.ofNullable(maxRetries);
      return this;
    }

    /**
     * <p>Delay in minutes between retry attempts (echoes request).</p>
     */
    @JsonSetter(
        value = "retryDelay",
        nulls = Nulls.SKIP
    )
    public Builder retryDelay(Optional<Integer> retryDelay) {
      this.retryDelay = retryDelay;
      return this;
    }

    public Builder retryDelay(Integer retryDelay) {
      this.retryDelay = Optional.ofNullable(retryDelay);
      return this;
    }

    /**
     * <p>Number of retries attempted so far across the campaign.</p>
     */
    @JsonSetter(
        value = "retryAttempts",
        nulls = Nulls.SKIP
    )
    public Builder retryAttempts(Optional<Integer> retryAttempts) {
      this.retryAttempts = retryAttempts;
      return this;
    }

    public Builder retryAttempts(Integer retryAttempts) {
      this.retryAttempts = Optional.ofNullable(retryAttempts);
      return this;
    }

    /**
     * <p>Current campaign status.</p>
     */
    @JsonSetter(
        value = "status",
        nulls = Nulls.SKIP
    )
    public Builder status(Optional<CreateCampaignsResponseDataStatus> status) {
      this.status = status;
      return this;
    }

    public Builder status(CreateCampaignsResponseDataStatus status) {
      this.status = Optional.ofNullable(status);
      return this;
    }

    /**
     * <p>The date and time when the campaign was created</p>
     */
    @JsonSetter(
        value = "createdAt",
        nulls = Nulls.SKIP
    )
    public Builder createdAt(Optional<OffsetDateTime> createdAt) {
      this.createdAt = createdAt;
      return this;
    }

    public Builder createdAt(OffsetDateTime createdAt) {
      this.createdAt = Optional.ofNullable(createdAt);
      return this;
    }

    /**
     * <p>The date and time when the campaign was last updated</p>
     */
    @JsonSetter(
        value = "updatedAt",
        nulls = Nulls.SKIP
    )
    public Builder updatedAt(Optional<OffsetDateTime> updatedAt) {
      this.updatedAt = updatedAt;
      return this;
    }

    public Builder updatedAt(OffsetDateTime updatedAt) {
      this.updatedAt = Optional.ofNullable(updatedAt);
      return this;
    }

    public CreateCampaignsResponseData build() {
      return new CreateCampaignsResponseData(id, name, description, organization, agentId, createdBy, audienceId, participantsCount, scheduledAt, maxRetries, retryDelay, retryAttempts, status, createdAt, updatedAt, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
