/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.smallest.resources.atoms.campaigns.types;

import ai.smallest.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = StartOrResumeCampaignsResponseData.Builder.class
)
public final class StartOrResumeCampaignsResponseData {
  private final Optional<String> message;

  private final Optional<String> taskId;

  private final Optional<String> campaignId;

  private final Map<String, Object> additionalProperties;

  private StartOrResumeCampaignsResponseData(Optional<String> message, Optional<String> taskId,
      Optional<String> campaignId, Map<String, Object> additionalProperties) {
    this.message = message;
    this.taskId = taskId;
    this.campaignId = campaignId;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("message")
  public Optional<String> getMessage() {
    return message;
  }

  /**
   * @return Internal task identifier for the queued job
   */
  @JsonProperty("taskId")
  public Optional<String> getTaskId() {
    return taskId;
  }

  /**
   * @return The ID of the campaign
   */
  @JsonProperty("campaignId")
  public Optional<String> getCampaignId() {
    return campaignId;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof StartOrResumeCampaignsResponseData && equalTo((StartOrResumeCampaignsResponseData) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(StartOrResumeCampaignsResponseData other) {
    return message.equals(other.message) && taskId.equals(other.taskId) && campaignId.equals(other.campaignId);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.message, this.taskId, this.campaignId);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<String> message = Optional.empty();

    private Optional<String> taskId = Optional.empty();

    private Optional<String> campaignId = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(StartOrResumeCampaignsResponseData other) {
      message(other.getMessage());
      taskId(other.getTaskId());
      campaignId(other.getCampaignId());
      return this;
    }

    @JsonSetter(
        value = "message",
        nulls = Nulls.SKIP
    )
    public Builder message(Optional<String> message) {
      this.message = message;
      return this;
    }

    public Builder message(String message) {
      this.message = Optional.ofNullable(message);
      return this;
    }

    /**
     * <p>Internal task identifier for the queued job</p>
     */
    @JsonSetter(
        value = "taskId",
        nulls = Nulls.SKIP
    )
    public Builder taskId(Optional<String> taskId) {
      this.taskId = taskId;
      return this;
    }

    public Builder taskId(String taskId) {
      this.taskId = Optional.ofNullable(taskId);
      return this;
    }

    /**
     * <p>The ID of the campaign</p>
     */
    @JsonSetter(
        value = "campaignId",
        nulls = Nulls.SKIP
    )
    public Builder campaignId(Optional<String> campaignId) {
      this.campaignId = campaignId;
      return this;
    }

    public Builder campaignId(String campaignId) {
      this.campaignId = Optional.ofNullable(campaignId);
      return this;
    }

    public StartOrResumeCampaignsResponseData build() {
      return new StartOrResumeCampaignsResponseData(message, taskId, campaignId, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
