/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.smallest.resources.waves.speechtospeech.types;

import ai.smallest.core.ObjectMappers;
import ai.smallest.resources.waves.types.ConversationItem;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = ConversationItemAdded.Builder.class
)
public final class ConversationItemAdded {
  private final Optional<ConversationItemAddedType> type;

  private final Optional<String> eventId;

  private final Optional<String> previousItemId;

  private final Optional<ConversationItem> item;

  private final Map<String, Object> additionalProperties;

  private ConversationItemAdded(Optional<ConversationItemAddedType> type, Optional<String> eventId,
      Optional<String> previousItemId, Optional<ConversationItem> item,
      Map<String, Object> additionalProperties) {
    this.type = type;
    this.eventId = eventId;
    this.previousItemId = previousItemId;
    this.item = item;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("type")
  public Optional<ConversationItemAddedType> getType() {
    return type;
  }

  @JsonProperty("event_id")
  public Optional<String> getEventId() {
    return eventId;
  }

  /**
   * @return ID of the item immediately preceding this one in the conversation log.
   */
  @JsonProperty("previous_item_id")
  public Optional<String> getPreviousItemId() {
    return previousItemId;
  }

  @JsonProperty("item")
  public Optional<ConversationItem> getItem() {
    return item;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof ConversationItemAdded && equalTo((ConversationItemAdded) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(ConversationItemAdded other) {
    return type.equals(other.type) && eventId.equals(other.eventId) && previousItemId.equals(other.previousItemId) && item.equals(other.item);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.type, this.eventId, this.previousItemId, this.item);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<ConversationItemAddedType> type = Optional.empty();

    private Optional<String> eventId = Optional.empty();

    private Optional<String> previousItemId = Optional.empty();

    private Optional<ConversationItem> item = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(ConversationItemAdded other) {
      type(other.getType());
      eventId(other.getEventId());
      previousItemId(other.getPreviousItemId());
      item(other.getItem());
      return this;
    }

    @JsonSetter(
        value = "type",
        nulls = Nulls.SKIP
    )
    public Builder type(Optional<ConversationItemAddedType> type) {
      this.type = type;
      return this;
    }

    public Builder type(ConversationItemAddedType type) {
      this.type = Optional.ofNullable(type);
      return this;
    }

    @JsonSetter(
        value = "event_id",
        nulls = Nulls.SKIP
    )
    public Builder eventId(Optional<String> eventId) {
      this.eventId = eventId;
      return this;
    }

    public Builder eventId(String eventId) {
      this.eventId = Optional.ofNullable(eventId);
      return this;
    }

    /**
     * <p>ID of the item immediately preceding this one in the conversation log.</p>
     */
    @JsonSetter(
        value = "previous_item_id",
        nulls = Nulls.SKIP
    )
    public Builder previousItemId(Optional<String> previousItemId) {
      this.previousItemId = previousItemId;
      return this;
    }

    public Builder previousItemId(String previousItemId) {
      this.previousItemId = Optional.ofNullable(previousItemId);
      return this;
    }

    @JsonSetter(
        value = "item",
        nulls = Nulls.SKIP
    )
    public Builder item(Optional<ConversationItem> item) {
      this.item = item;
      return this;
    }

    public Builder item(ConversationItem item) {
      this.item = Optional.ofNullable(item);
      return this;
    }

    public ConversationItemAdded build() {
      return new ConversationItemAdded(type, eventId, previousItemId, item, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
