/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.smallest.resources.waves.speechtospeech.types;

import ai.smallest.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = InputAudioBufferSpeechStopped.Builder.class
)
public final class InputAudioBufferSpeechStopped {
  private final Optional<InputAudioBufferSpeechStoppedType> type;

  private final Optional<String> eventId;

  private final Optional<Integer> audioEndMs;

  private final Optional<String> itemId;

  private final Map<String, Object> additionalProperties;

  private InputAudioBufferSpeechStopped(Optional<InputAudioBufferSpeechStoppedType> type,
      Optional<String> eventId, Optional<Integer> audioEndMs, Optional<String> itemId,
      Map<String, Object> additionalProperties) {
    this.type = type;
    this.eventId = eventId;
    this.audioEndMs = audioEndMs;
    this.itemId = itemId;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("type")
  public Optional<InputAudioBufferSpeechStoppedType> getType() {
    return type;
  }

  @JsonProperty("event_id")
  public Optional<String> getEventId() {
    return eventId;
  }

  @JsonProperty("audio_end_ms")
  public Optional<Integer> getAudioEndMs() {
    return audioEndMs;
  }

  @JsonProperty("item_id")
  public Optional<String> getItemId() {
    return itemId;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof InputAudioBufferSpeechStopped && equalTo((InputAudioBufferSpeechStopped) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(InputAudioBufferSpeechStopped other) {
    return type.equals(other.type) && eventId.equals(other.eventId) && audioEndMs.equals(other.audioEndMs) && itemId.equals(other.itemId);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.type, this.eventId, this.audioEndMs, this.itemId);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<InputAudioBufferSpeechStoppedType> type = Optional.empty();

    private Optional<String> eventId = Optional.empty();

    private Optional<Integer> audioEndMs = Optional.empty();

    private Optional<String> itemId = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(InputAudioBufferSpeechStopped other) {
      type(other.getType());
      eventId(other.getEventId());
      audioEndMs(other.getAudioEndMs());
      itemId(other.getItemId());
      return this;
    }

    @JsonSetter(
        value = "type",
        nulls = Nulls.SKIP
    )
    public Builder type(Optional<InputAudioBufferSpeechStoppedType> type) {
      this.type = type;
      return this;
    }

    public Builder type(InputAudioBufferSpeechStoppedType type) {
      this.type = Optional.ofNullable(type);
      return this;
    }

    @JsonSetter(
        value = "event_id",
        nulls = Nulls.SKIP
    )
    public Builder eventId(Optional<String> eventId) {
      this.eventId = eventId;
      return this;
    }

    public Builder eventId(String eventId) {
      this.eventId = Optional.ofNullable(eventId);
      return this;
    }

    @JsonSetter(
        value = "audio_end_ms",
        nulls = Nulls.SKIP
    )
    public Builder audioEndMs(Optional<Integer> audioEndMs) {
      this.audioEndMs = audioEndMs;
      return this;
    }

    public Builder audioEndMs(Integer audioEndMs) {
      this.audioEndMs = Optional.ofNullable(audioEndMs);
      return this;
    }

    @JsonSetter(
        value = "item_id",
        nulls = Nulls.SKIP
    )
    public Builder itemId(Optional<String> itemId) {
      this.itemId = itemId;
      return this;
    }

    public Builder itemId(String itemId) {
      this.itemId = Optional.ofNullable(itemId);
      return this;
    }

    public InputAudioBufferSpeechStopped build() {
      return new InputAudioBufferSpeechStopped(type, eventId, audioEndMs, itemId, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
