/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.smallest.resources.waves.speechtospeech.types;

import ai.smallest.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = SessionConfigured.Builder.class
)
public final class SessionConfigured {
  private final Optional<SessionConfiguredType> type;

  private final Optional<String> eventId;

  private final Optional<SessionConfiguredSession> session;

  private final Map<String, Object> additionalProperties;

  private SessionConfigured(Optional<SessionConfiguredType> type, Optional<String> eventId,
      Optional<SessionConfiguredSession> session, Map<String, Object> additionalProperties) {
    this.type = type;
    this.eventId = eventId;
    this.session = session;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("type")
  public Optional<SessionConfiguredType> getType() {
    return type;
  }

  @JsonProperty("event_id")
  public Optional<String> getEventId() {
    return eventId;
  }

  /**
   * @return Effective session configuration as accepted by the server. Echoes the fields the server applied:
   * <code>instructions</code>, <code>voice</code>, <code>tools</code>, <code>generate_initial_response</code>.
   */
  @JsonProperty("session")
  public Optional<SessionConfiguredSession> getSession() {
    return session;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof SessionConfigured && equalTo((SessionConfigured) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(SessionConfigured other) {
    return type.equals(other.type) && eventId.equals(other.eventId) && session.equals(other.session);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.type, this.eventId, this.session);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<SessionConfiguredType> type = Optional.empty();

    private Optional<String> eventId = Optional.empty();

    private Optional<SessionConfiguredSession> session = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(SessionConfigured other) {
      type(other.getType());
      eventId(other.getEventId());
      session(other.getSession());
      return this;
    }

    @JsonSetter(
        value = "type",
        nulls = Nulls.SKIP
    )
    public Builder type(Optional<SessionConfiguredType> type) {
      this.type = type;
      return this;
    }

    public Builder type(SessionConfiguredType type) {
      this.type = Optional.ofNullable(type);
      return this;
    }

    @JsonSetter(
        value = "event_id",
        nulls = Nulls.SKIP
    )
    public Builder eventId(Optional<String> eventId) {
      this.eventId = eventId;
      return this;
    }

    public Builder eventId(String eventId) {
      this.eventId = Optional.ofNullable(eventId);
      return this;
    }

    /**
     * <p>Effective session configuration as accepted by the server. Echoes the fields the server applied:
     * <code>instructions</code>, <code>voice</code>, <code>tools</code>, <code>generate_initial_response</code>.</p>
     */
    @JsonSetter(
        value = "session",
        nulls = Nulls.SKIP
    )
    public Builder session(Optional<SessionConfiguredSession> session) {
      this.session = session;
      return this;
    }

    public Builder session(SessionConfiguredSession session) {
      this.session = Optional.ofNullable(session);
      return this;
    }

    public SessionConfigured build() {
      return new SessionConfigured(type, eventId, session, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
