/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.smallest.resources.atoms.audience;

import ai.smallest.core.ClientOptions;
import ai.smallest.core.RequestOptions;
import ai.smallest.resources.atoms.audience.requests.DeleteAudienceIdMembersRequest;
import ai.smallest.resources.atoms.audience.requests.DeleteAudienceIdRequest;
import ai.smallest.resources.atoms.audience.requests.GetAudienceIdMembersRequest;
import ai.smallest.resources.atoms.audience.requests.GetAudienceIdMembersSearchRequest;
import ai.smallest.resources.atoms.audience.requests.GetAudienceRequest;
import ai.smallest.resources.atoms.audience.requests.PostAudienceIdMembersRequest;
import ai.smallest.resources.atoms.audience.requests.PostAudienceRequest;
import ai.smallest.resources.atoms.audience.types.DeleteAudienceIdMembersResponse;
import ai.smallest.resources.atoms.audience.types.DeleteAudienceIdResponse;
import ai.smallest.resources.atoms.audience.types.GetAudienceIdMembersResponse;
import ai.smallest.resources.atoms.audience.types.GetAudienceIdMembersSearchResponse;
import ai.smallest.resources.atoms.audience.types.GetAudienceResponse;
import ai.smallest.resources.atoms.audience.types.ListAudienceResponse;
import ai.smallest.resources.atoms.audience.types.PostAudienceIdMembersResponse;
import ai.smallest.resources.atoms.audience.types.PostAudienceResponse;
import java.io.File;
import java.io.InputStream;
import java.lang.String;
import java.util.concurrent.CompletableFuture;
import okhttp3.MediaType;

public class AsyncAudienceClient {
  protected final ClientOptions clientOptions;

  private final AsyncRawAudienceClient rawClient;

  public AsyncAudienceClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new AsyncRawAudienceClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public AsyncRawAudienceClient withRawResponse() {
    return this.rawClient;
  }

  /**
   * Retrieve all audiences created by the authenticated user. Users can only access audiences they have created.
   */
  public CompletableFuture<ListAudienceResponse> list() {
    return this.rawClient.list().thenApply(response -> response.body());
  }

  /**
   * Retrieve all audiences created by the authenticated user. Users can only access audiences they have created.
   */
  public CompletableFuture<ListAudienceResponse> list(RequestOptions requestOptions) {
    return this.rawClient.list(requestOptions).thenApply(response -> response.body());
  }

  /**
   * Create a new audience by uploading a CSV file containing phone numbers.
   * Only CSV text files are accepted — binary files will produce malformed data.
   * <p><strong>Additional 400 cases:</strong></p>
   * <ul>
   * <li>Duplicate phone numbers in the CSV: <code>&quot;Some phone numbers in your CSV already exist in this audience. Please remove duplicate entries and try again.&quot;</code></li>
   * <li>Member limit exceeded: <code>&quot;Audience cannot exceed X members&quot;</code></li>
   * </ul>
   */
  public CompletableFuture<PostAudienceResponse> createAudienceWithCsvUpload(File file,
      PostAudienceRequest request) {
    return this.rawClient.createAudienceWithCsvUpload(file, request).thenApply(response -> response.body());
  }

  /**
   * Create a new audience by uploading a CSV file containing phone numbers.
   * Only CSV text files are accepted — binary files will produce malformed data.
   * <p><strong>Additional 400 cases:</strong></p>
   * <ul>
   * <li>Duplicate phone numbers in the CSV: <code>&quot;Some phone numbers in your CSV already exist in this audience. Please remove duplicate entries and try again.&quot;</code></li>
   * <li>Member limit exceeded: <code>&quot;Audience cannot exceed X members&quot;</code></li>
   * </ul>
   */
  public CompletableFuture<PostAudienceResponse> createAudienceWithCsvUpload(File file,
      PostAudienceRequest request, RequestOptions requestOptions) {
    return this.rawClient.createAudienceWithCsvUpload(file, request, requestOptions).thenApply(response -> response.body());
  }

  public CompletableFuture<PostAudienceResponse> createAudienceWithCsvUpload(InputStream stream,
      String filename) {
    return this.rawClient.createAudienceWithCsvUpload(stream, filename).thenApply(response -> response.body());
  }

  public CompletableFuture<PostAudienceResponse> createAudienceWithCsvUpload(InputStream stream,
      String filename, MediaType mediaType) {
    return this.rawClient.createAudienceWithCsvUpload(stream, filename, mediaType).thenApply(response -> response.body());
  }

  public CompletableFuture<PostAudienceResponse> createAudienceWithCsvUpload(InputStream stream,
      String filename, RequestOptions requestOptions) {
    return this.rawClient.createAudienceWithCsvUpload(stream, filename, requestOptions).thenApply(response -> response.body());
  }

  public CompletableFuture<PostAudienceResponse> createAudienceWithCsvUpload(InputStream stream,
      String filename, MediaType mediaType, RequestOptions requestOptions) {
    return this.rawClient.createAudienceWithCsvUpload(stream, filename, mediaType, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Retrieve a specific audience by its ID.
   * Note: if the audience belongs to a different organization, the API returns 404 (not 403) — ownership is deliberately obscured.
   */
  public CompletableFuture<GetAudienceResponse> get(String id) {
    return this.rawClient.get(id).thenApply(response -> response.body());
  }

  /**
   * Retrieve a specific audience by its ID.
   * Note: if the audience belongs to a different organization, the API returns 404 (not 403) — ownership is deliberately obscured.
   */
  public CompletableFuture<GetAudienceResponse> get(String id, RequestOptions requestOptions) {
    return this.rawClient.get(id, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Retrieve a specific audience by its ID.
   * Note: if the audience belongs to a different organization, the API returns 404 (not 403) — ownership is deliberately obscured.
   */
  public CompletableFuture<GetAudienceResponse> get(String id, GetAudienceRequest request) {
    return this.rawClient.get(id, request).thenApply(response -> response.body());
  }

  /**
   * Retrieve a specific audience by its ID.
   * Note: if the audience belongs to a different organization, the API returns 404 (not 403) — ownership is deliberately obscured.
   */
  public CompletableFuture<GetAudienceResponse> get(String id, GetAudienceRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.get(id, request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Delete a specific audience by its ID. Users can only delete audiences they created.
   * <p><strong>400 is returned if the audience is used by an active campaign:</strong>
   * <code>&quot;can't delete audience, campaign with this audience &lt;id&gt; exists&quot;</code>
   * Remove the campaign first, then retry deletion.</p>
   * <p>On success, <code>data</code> is always an empty array <code>[]</code>.</p>
   */
  public CompletableFuture<DeleteAudienceIdResponse> deleteAudience(String id) {
    return this.rawClient.deleteAudience(id).thenApply(response -> response.body());
  }

  /**
   * Delete a specific audience by its ID. Users can only delete audiences they created.
   * <p><strong>400 is returned if the audience is used by an active campaign:</strong>
   * <code>&quot;can't delete audience, campaign with this audience &lt;id&gt; exists&quot;</code>
   * Remove the campaign first, then retry deletion.</p>
   * <p>On success, <code>data</code> is always an empty array <code>[]</code>.</p>
   */
  public CompletableFuture<DeleteAudienceIdResponse> deleteAudience(String id,
      RequestOptions requestOptions) {
    return this.rawClient.deleteAudience(id, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Delete a specific audience by its ID. Users can only delete audiences they created.
   * <p><strong>400 is returned if the audience is used by an active campaign:</strong>
   * <code>&quot;can't delete audience, campaign with this audience &lt;id&gt; exists&quot;</code>
   * Remove the campaign first, then retry deletion.</p>
   * <p>On success, <code>data</code> is always an empty array <code>[]</code>.</p>
   */
  public CompletableFuture<DeleteAudienceIdResponse> deleteAudience(String id,
      DeleteAudienceIdRequest request) {
    return this.rawClient.deleteAudience(id, request).thenApply(response -> response.body());
  }

  /**
   * Delete a specific audience by its ID. Users can only delete audiences they created.
   * <p><strong>400 is returned if the audience is used by an active campaign:</strong>
   * <code>&quot;can't delete audience, campaign with this audience &lt;id&gt; exists&quot;</code>
   * Remove the campaign first, then retry deletion.</p>
   * <p>On success, <code>data</code> is always an empty array <code>[]</code>.</p>
   */
  public CompletableFuture<DeleteAudienceIdResponse> deleteAudience(String id,
      DeleteAudienceIdRequest request, RequestOptions requestOptions) {
    return this.rawClient.deleteAudience(id, request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Retrieve members of a specific audience with pagination support. Users can only access members of audiences they created.
   */
  public CompletableFuture<GetAudienceIdMembersResponse> getAudienceMembers(String id) {
    return this.rawClient.getAudienceMembers(id).thenApply(response -> response.body());
  }

  /**
   * Retrieve members of a specific audience with pagination support. Users can only access members of audiences they created.
   */
  public CompletableFuture<GetAudienceIdMembersResponse> getAudienceMembers(String id,
      RequestOptions requestOptions) {
    return this.rawClient.getAudienceMembers(id, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Retrieve members of a specific audience with pagination support. Users can only access members of audiences they created.
   */
  public CompletableFuture<GetAudienceIdMembersResponse> getAudienceMembers(String id,
      GetAudienceIdMembersRequest request) {
    return this.rawClient.getAudienceMembers(id, request).thenApply(response -> response.body());
  }

  /**
   * Retrieve members of a specific audience with pagination support. Users can only access members of audiences they created.
   */
  public CompletableFuture<GetAudienceIdMembersResponse> getAudienceMembers(String id,
      GetAudienceIdMembersRequest request, RequestOptions requestOptions) {
    return this.rawClient.getAudienceMembers(id, request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Add new members to an existing audience.
   * <p>Each member object must include a key matching the audience's <code>phoneNumberColumnName</code>.
   * If it's missing, the API returns 400: <code>&quot;Each member must have a &lt;phoneNumberColumnName&gt; field&quot;</code>.
   * Adding members that would exceed the audience limit also returns 400.</p>
   * <p>Note: if the audience belongs to a different organization, the API returns 404 (not 403).</p>
   */
  public CompletableFuture<PostAudienceIdMembersResponse> addAudienceMembers(String id,
      PostAudienceIdMembersRequest request) {
    return this.rawClient.addAudienceMembers(id, request).thenApply(response -> response.body());
  }

  /**
   * Add new members to an existing audience.
   * <p>Each member object must include a key matching the audience's <code>phoneNumberColumnName</code>.
   * If it's missing, the API returns 400: <code>&quot;Each member must have a &lt;phoneNumberColumnName&gt; field&quot;</code>.
   * Adding members that would exceed the audience limit also returns 400.</p>
   * <p>Note: if the audience belongs to a different organization, the API returns 404 (not 403).</p>
   */
  public CompletableFuture<PostAudienceIdMembersResponse> addAudienceMembers(String id,
      PostAudienceIdMembersRequest request, RequestOptions requestOptions) {
    return this.rawClient.addAudienceMembers(id, request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Remove specific members from an audience by their member IDs. Users can only delete members from audiences they created.
   */
  public CompletableFuture<DeleteAudienceIdMembersResponse> deleteAudienceMembers(String id,
      DeleteAudienceIdMembersRequest request) {
    return this.rawClient.deleteAudienceMembers(id, request).thenApply(response -> response.body());
  }

  /**
   * Remove specific members from an audience by their member IDs. Users can only delete members from audiences they created.
   */
  public CompletableFuture<DeleteAudienceIdMembersResponse> deleteAudienceMembers(String id,
      DeleteAudienceIdMembersRequest request, RequestOptions requestOptions) {
    return this.rawClient.deleteAudienceMembers(id, request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Search for members within a specific audience using flexible search parameters. Users can only search members of audiences they created.
   * <p><strong>Search Types:</strong></p>
   * <ul>
   * <li><strong>General Search</strong> (<code>query</code>): Searches across all fields in the audience member data</li>
   * <li><strong>Field-Specific Search</strong>: Use any field name as a parameter (e.g., <code>firstName=john</code>, <code>phoneNumber=123456</code>, <code>email=test@example.com</code>)</li>
   * </ul>
   * <p><strong>Examples:</strong></p>
   * <ul>
   * <li><code>?query=john</code> - General search across all fields</li>
   * <li><code>?firstName=john</code> - Search specifically in firstName field</li>
   * <li><code>?phoneNumber=555-1234</code> - Search specifically in phoneNumber field</li>
   * <li><code>?firstName=john&amp;lastName=doe</code> - Search for members matching both criteria</li>
   * </ul>
   * <p><strong>Note:</strong> When using phoneNumber field, do not use quotes around the phone number. You can use either a general search OR field-specific searches, but not both simultaneously.</p>
   */
  public CompletableFuture<GetAudienceIdMembersSearchResponse> searchAudienceMembers(String id) {
    return this.rawClient.searchAudienceMembers(id).thenApply(response -> response.body());
  }

  /**
   * Search for members within a specific audience using flexible search parameters. Users can only search members of audiences they created.
   * <p><strong>Search Types:</strong></p>
   * <ul>
   * <li><strong>General Search</strong> (<code>query</code>): Searches across all fields in the audience member data</li>
   * <li><strong>Field-Specific Search</strong>: Use any field name as a parameter (e.g., <code>firstName=john</code>, <code>phoneNumber=123456</code>, <code>email=test@example.com</code>)</li>
   * </ul>
   * <p><strong>Examples:</strong></p>
   * <ul>
   * <li><code>?query=john</code> - General search across all fields</li>
   * <li><code>?firstName=john</code> - Search specifically in firstName field</li>
   * <li><code>?phoneNumber=555-1234</code> - Search specifically in phoneNumber field</li>
   * <li><code>?firstName=john&amp;lastName=doe</code> - Search for members matching both criteria</li>
   * </ul>
   * <p><strong>Note:</strong> When using phoneNumber field, do not use quotes around the phone number. You can use either a general search OR field-specific searches, but not both simultaneously.</p>
   */
  public CompletableFuture<GetAudienceIdMembersSearchResponse> searchAudienceMembers(String id,
      RequestOptions requestOptions) {
    return this.rawClient.searchAudienceMembers(id, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Search for members within a specific audience using flexible search parameters. Users can only search members of audiences they created.
   * <p><strong>Search Types:</strong></p>
   * <ul>
   * <li><strong>General Search</strong> (<code>query</code>): Searches across all fields in the audience member data</li>
   * <li><strong>Field-Specific Search</strong>: Use any field name as a parameter (e.g., <code>firstName=john</code>, <code>phoneNumber=123456</code>, <code>email=test@example.com</code>)</li>
   * </ul>
   * <p><strong>Examples:</strong></p>
   * <ul>
   * <li><code>?query=john</code> - General search across all fields</li>
   * <li><code>?firstName=john</code> - Search specifically in firstName field</li>
   * <li><code>?phoneNumber=555-1234</code> - Search specifically in phoneNumber field</li>
   * <li><code>?firstName=john&amp;lastName=doe</code> - Search for members matching both criteria</li>
   * </ul>
   * <p><strong>Note:</strong> When using phoneNumber field, do not use quotes around the phone number. You can use either a general search OR field-specific searches, but not both simultaneously.</p>
   */
  public CompletableFuture<GetAudienceIdMembersSearchResponse> searchAudienceMembers(String id,
      GetAudienceIdMembersSearchRequest request) {
    return this.rawClient.searchAudienceMembers(id, request).thenApply(response -> response.body());
  }

  /**
   * Search for members within a specific audience using flexible search parameters. Users can only search members of audiences they created.
   * <p><strong>Search Types:</strong></p>
   * <ul>
   * <li><strong>General Search</strong> (<code>query</code>): Searches across all fields in the audience member data</li>
   * <li><strong>Field-Specific Search</strong>: Use any field name as a parameter (e.g., <code>firstName=john</code>, <code>phoneNumber=123456</code>, <code>email=test@example.com</code>)</li>
   * </ul>
   * <p><strong>Examples:</strong></p>
   * <ul>
   * <li><code>?query=john</code> - General search across all fields</li>
   * <li><code>?firstName=john</code> - Search specifically in firstName field</li>
   * <li><code>?phoneNumber=555-1234</code> - Search specifically in phoneNumber field</li>
   * <li><code>?firstName=john&amp;lastName=doe</code> - Search for members matching both criteria</li>
   * </ul>
   * <p><strong>Note:</strong> When using phoneNumber field, do not use quotes around the phone number. You can use either a general search OR field-specific searches, but not both simultaneously.</p>
   */
  public CompletableFuture<GetAudienceIdMembersSearchResponse> searchAudienceMembers(String id,
      GetAudienceIdMembersSearchRequest request, RequestOptions requestOptions) {
    return this.rawClient.searchAudienceMembers(id, request, requestOptions).thenApply(response -> response.body());
  }
}
