/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.smallest.resources.waves.lightningv31tts.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class LightningV31TtsRequestMessageLanguage {
  public static final LightningV31TtsRequestMessageLanguage ES = new LightningV31TtsRequestMessageLanguage(Value.ES, "es");

  public static final LightningV31TtsRequestMessageLanguage EN = new LightningV31TtsRequestMessageLanguage(Value.EN, "en");

  public static final LightningV31TtsRequestMessageLanguage TE = new LightningV31TtsRequestMessageLanguage(Value.TE, "te");

  public static final LightningV31TtsRequestMessageLanguage PA = new LightningV31TtsRequestMessageLanguage(Value.PA, "pa");

  public static final LightningV31TtsRequestMessageLanguage HI = new LightningV31TtsRequestMessageLanguage(Value.HI, "hi");

  public static final LightningV31TtsRequestMessageLanguage ML = new LightningV31TtsRequestMessageLanguage(Value.ML, "ml");

  public static final LightningV31TtsRequestMessageLanguage KN = new LightningV31TtsRequestMessageLanguage(Value.KN, "kn");

  public static final LightningV31TtsRequestMessageLanguage GU = new LightningV31TtsRequestMessageLanguage(Value.GU, "gu");

  public static final LightningV31TtsRequestMessageLanguage OR = new LightningV31TtsRequestMessageLanguage(Value.OR, "or");

  public static final LightningV31TtsRequestMessageLanguage MR = new LightningV31TtsRequestMessageLanguage(Value.MR, "mr");

  public static final LightningV31TtsRequestMessageLanguage TA = new LightningV31TtsRequestMessageLanguage(Value.TA, "ta");

  public static final LightningV31TtsRequestMessageLanguage BN = new LightningV31TtsRequestMessageLanguage(Value.BN, "bn");

  private final Value value;

  private final String string;

  LightningV31TtsRequestMessageLanguage(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof LightningV31TtsRequestMessageLanguage && this.string.equals(((LightningV31TtsRequestMessageLanguage) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case ES:
        return visitor.visitEs();
      case EN:
        return visitor.visitEn();
      case TE:
        return visitor.visitTe();
      case PA:
        return visitor.visitPa();
      case HI:
        return visitor.visitHi();
      case ML:
        return visitor.visitMl();
      case KN:
        return visitor.visitKn();
      case GU:
        return visitor.visitGu();
      case OR:
        return visitor.visitOr();
      case MR:
        return visitor.visitMr();
      case TA:
        return visitor.visitTa();
      case BN:
        return visitor.visitBn();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static LightningV31TtsRequestMessageLanguage valueOf(String value) {
    switch (value) {
      case "es":
        return ES;
      case "en":
        return EN;
      case "te":
        return TE;
      case "pa":
        return PA;
      case "hi":
        return HI;
      case "ml":
        return ML;
      case "kn":
        return KN;
      case "gu":
        return GU;
      case "or":
        return OR;
      case "mr":
        return MR;
      case "ta":
        return TA;
      case "bn":
        return BN;
      default:
        return new LightningV31TtsRequestMessageLanguage(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    EN,

    HI,

    MR,

    KN,

    TA,

    BN,

    GU,

    TE,

    ML,

    PA,

    OR,

    ES,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitEn();

    T visitHi();

    T visitMr();

    T visitKn();

    T visitTa();

    T visitBn();

    T visitGu();

    T visitTe();

    T visitMl();

    T visitPa();

    T visitOr();

    T visitEs();

    T visitUnknown(String unknownType);
  }
}
