/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.smallest.resources.atoms.user;

import ai.smallest.core.ClientOptions;
import ai.smallest.core.RequestOptions;
import ai.smallest.resources.atoms.user.types.GetUserResponse;

public class UserClient {
  protected final ClientOptions clientOptions;

  private final RawUserClient rawClient;

  public UserClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new RawUserClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public RawUserClient withRawResponse() {
    return this.rawClient;
  }

  public GetUserResponse getUserDetails() {
    return this.rawClient.getUserDetails().body();
  }

  public GetUserResponse getUserDetails(RequestOptions requestOptions) {
    return this.rawClient.getUserDetails(requestOptions).body();
  }
}
