/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.smallest.resources.atoms.phonenumbers.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class ImportSipPhoneNumbersResponseDataProductType {
  public static final ImportSipPhoneNumbersResponseDataProductType CUSTOM = new ImportSipPhoneNumbersResponseDataProductType(Value.CUSTOM, "custom");

  private final Value value;

  private final String string;

  ImportSipPhoneNumbersResponseDataProductType(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof ImportSipPhoneNumbersResponseDataProductType && this.string.equals(((ImportSipPhoneNumbersResponseDataProductType) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case CUSTOM:
        return visitor.visitCustom();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static ImportSipPhoneNumbersResponseDataProductType valueOf(String value) {
    switch (value) {
      case "custom":
        return CUSTOM;
      default:
        return new ImportSipPhoneNumbersResponseDataProductType(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    CUSTOM,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitCustom();

    T visitUnknown(String unknownType);
  }
}
