/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.smallest.resources.atoms.phonenumbers.types;

import ai.smallest.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = ImportSipPhoneNumbersResponseDataAttributes.Builder.class
)
public final class ImportSipPhoneNumbersResponseDataAttributes {
  private final Optional<String> name;

  private final Optional<String> phoneNumber;

  private final Optional<String> outboundSipTrunkId;

  private final Optional<String> inboundSipTrunkId;

  private final Map<String, Object> additionalProperties;

  private ImportSipPhoneNumbersResponseDataAttributes(Optional<String> name,
      Optional<String> phoneNumber, Optional<String> outboundSipTrunkId,
      Optional<String> inboundSipTrunkId, Map<String, Object> additionalProperties) {
    this.name = name;
    this.phoneNumber = phoneNumber;
    this.outboundSipTrunkId = outboundSipTrunkId;
    this.inboundSipTrunkId = inboundSipTrunkId;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Display name for the number
   */
  @JsonProperty("name")
  public Optional<String> getName() {
    return name;
  }

  /**
   * @return The imported phone number
   */
  @JsonProperty("phoneNumber")
  public Optional<String> getPhoneNumber() {
    return phoneNumber;
  }

  /**
   * @return Identifier for the outbound SIP trunk created
   */
  @JsonProperty("outboundSipTrunkId")
  public Optional<String> getOutboundSipTrunkId() {
    return outboundSipTrunkId;
  }

  /**
   * @return Identifier for the inbound SIP trunk created
   */
  @JsonProperty("inboundSipTrunkId")
  public Optional<String> getInboundSipTrunkId() {
    return inboundSipTrunkId;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof ImportSipPhoneNumbersResponseDataAttributes && equalTo((ImportSipPhoneNumbersResponseDataAttributes) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(ImportSipPhoneNumbersResponseDataAttributes other) {
    return name.equals(other.name) && phoneNumber.equals(other.phoneNumber) && outboundSipTrunkId.equals(other.outboundSipTrunkId) && inboundSipTrunkId.equals(other.inboundSipTrunkId);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.name, this.phoneNumber, this.outboundSipTrunkId, this.inboundSipTrunkId);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<String> name = Optional.empty();

    private Optional<String> phoneNumber = Optional.empty();

    private Optional<String> outboundSipTrunkId = Optional.empty();

    private Optional<String> inboundSipTrunkId = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(ImportSipPhoneNumbersResponseDataAttributes other) {
      name(other.getName());
      phoneNumber(other.getPhoneNumber());
      outboundSipTrunkId(other.getOutboundSipTrunkId());
      inboundSipTrunkId(other.getInboundSipTrunkId());
      return this;
    }

    /**
     * <p>Display name for the number</p>
     */
    @JsonSetter(
        value = "name",
        nulls = Nulls.SKIP
    )
    public Builder name(Optional<String> name) {
      this.name = name;
      return this;
    }

    public Builder name(String name) {
      this.name = Optional.ofNullable(name);
      return this;
    }

    /**
     * <p>The imported phone number</p>
     */
    @JsonSetter(
        value = "phoneNumber",
        nulls = Nulls.SKIP
    )
    public Builder phoneNumber(Optional<String> phoneNumber) {
      this.phoneNumber = phoneNumber;
      return this;
    }

    public Builder phoneNumber(String phoneNumber) {
      this.phoneNumber = Optional.ofNullable(phoneNumber);
      return this;
    }

    /**
     * <p>Identifier for the outbound SIP trunk created</p>
     */
    @JsonSetter(
        value = "outboundSipTrunkId",
        nulls = Nulls.SKIP
    )
    public Builder outboundSipTrunkId(Optional<String> outboundSipTrunkId) {
      this.outboundSipTrunkId = outboundSipTrunkId;
      return this;
    }

    public Builder outboundSipTrunkId(String outboundSipTrunkId) {
      this.outboundSipTrunkId = Optional.ofNullable(outboundSipTrunkId);
      return this;
    }

    /**
     * <p>Identifier for the inbound SIP trunk created</p>
     */
    @JsonSetter(
        value = "inboundSipTrunkId",
        nulls = Nulls.SKIP
    )
    public Builder inboundSipTrunkId(Optional<String> inboundSipTrunkId) {
      this.inboundSipTrunkId = inboundSipTrunkId;
      return this;
    }

    public Builder inboundSipTrunkId(String inboundSipTrunkId) {
      this.inboundSipTrunkId = Optional.ofNullable(inboundSipTrunkId);
      return this;
    }

    public ImportSipPhoneNumbersResponseDataAttributes build() {
      return new ImportSipPhoneNumbersResponseDataAttributes(name, phoneNumber, outboundSipTrunkId, inboundSipTrunkId, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
