/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.smallest.resources.atoms.phonenumbers.types;

import ai.smallest.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = SearchRentablePhoneNumbersResponseDataItem.Builder.class
)
public final class SearchRentablePhoneNumbersResponseDataItem {
  private final Optional<String> phoneNumber;

  private final Optional<String> countryCode;

  private final Optional<SearchRentablePhoneNumbersResponseDataItemProvider> provider;

  private final Optional<String> areaCode;

  private final Map<String, Object> additionalProperties;

  private SearchRentablePhoneNumbersResponseDataItem(Optional<String> phoneNumber,
      Optional<String> countryCode,
      Optional<SearchRentablePhoneNumbersResponseDataItemProvider> provider,
      Optional<String> areaCode, Map<String, Object> additionalProperties) {
    this.phoneNumber = phoneNumber;
    this.countryCode = countryCode;
    this.provider = provider;
    this.areaCode = areaCode;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return E.164-style number without the leading <code>+</code>. Pass exactly this value to <code>POST /product/rent-number</code>.
   */
  @JsonProperty("phoneNumber")
  public Optional<String> getPhoneNumber() {
    return phoneNumber;
  }

  @JsonProperty("countryCode")
  public Optional<String> getCountryCode() {
    return countryCode;
  }

  @JsonProperty("provider")
  public Optional<SearchRentablePhoneNumbersResponseDataItemProvider> getProvider() {
    return provider;
  }

  /**
   * @return Region / state / area-code label returned by the provider.
   */
  @JsonProperty("areaCode")
  public Optional<String> getAreaCode() {
    return areaCode;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof SearchRentablePhoneNumbersResponseDataItem && equalTo((SearchRentablePhoneNumbersResponseDataItem) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(SearchRentablePhoneNumbersResponseDataItem other) {
    return phoneNumber.equals(other.phoneNumber) && countryCode.equals(other.countryCode) && provider.equals(other.provider) && areaCode.equals(other.areaCode);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.phoneNumber, this.countryCode, this.provider, this.areaCode);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<String> phoneNumber = Optional.empty();

    private Optional<String> countryCode = Optional.empty();

    private Optional<SearchRentablePhoneNumbersResponseDataItemProvider> provider = Optional.empty();

    private Optional<String> areaCode = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(SearchRentablePhoneNumbersResponseDataItem other) {
      phoneNumber(other.getPhoneNumber());
      countryCode(other.getCountryCode());
      provider(other.getProvider());
      areaCode(other.getAreaCode());
      return this;
    }

    /**
     * <p>E.164-style number without the leading <code>+</code>. Pass exactly this value to <code>POST /product/rent-number</code>.</p>
     */
    @JsonSetter(
        value = "phoneNumber",
        nulls = Nulls.SKIP
    )
    public Builder phoneNumber(Optional<String> phoneNumber) {
      this.phoneNumber = phoneNumber;
      return this;
    }

    public Builder phoneNumber(String phoneNumber) {
      this.phoneNumber = Optional.ofNullable(phoneNumber);
      return this;
    }

    @JsonSetter(
        value = "countryCode",
        nulls = Nulls.SKIP
    )
    public Builder countryCode(Optional<String> countryCode) {
      this.countryCode = countryCode;
      return this;
    }

    public Builder countryCode(String countryCode) {
      this.countryCode = Optional.ofNullable(countryCode);
      return this;
    }

    @JsonSetter(
        value = "provider",
        nulls = Nulls.SKIP
    )
    public Builder provider(Optional<SearchRentablePhoneNumbersResponseDataItemProvider> provider) {
      this.provider = provider;
      return this;
    }

    public Builder provider(SearchRentablePhoneNumbersResponseDataItemProvider provider) {
      this.provider = Optional.ofNullable(provider);
      return this;
    }

    /**
     * <p>Region / state / area-code label returned by the provider.</p>
     */
    @JsonSetter(
        value = "areaCode",
        nulls = Nulls.SKIP
    )
    public Builder areaCode(Optional<String> areaCode) {
      this.areaCode = areaCode;
      return this;
    }

    public Builder areaCode(String areaCode) {
      this.areaCode = Optional.ofNullable(areaCode);
      return this;
    }

    public SearchRentablePhoneNumbersResponseDataItem build() {
      return new SearchRentablePhoneNumbersResponseDataItem(phoneNumber, countryCode, provider, areaCode, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
