/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.smallest.resources.atoms.audience.requests;

import ai.smallest.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = GetAudienceIdMembersRequest.Builder.class
)
public final class GetAudienceIdMembersRequest {
  private final Optional<Integer> page;

  private final Optional<Integer> offset;

  private final Map<String, Object> additionalProperties;

  private GetAudienceIdMembersRequest(Optional<Integer> page, Optional<Integer> offset,
      Map<String, Object> additionalProperties) {
    this.page = page;
    this.offset = offset;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Page number for pagination (default is 1)
   */
  @JsonProperty("page")
  public Optional<Integer> getPage() {
    return page;
  }

  /**
   * @return Number of items per page (default is 5).
   * Note: this parameter is named &quot;offset&quot;, not &quot;limit&quot; — sending ?limit=N is silently ignored.
   */
  @JsonProperty("offset")
  public Optional<Integer> getOffset() {
    return offset;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof GetAudienceIdMembersRequest && equalTo((GetAudienceIdMembersRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(GetAudienceIdMembersRequest other) {
    return page.equals(other.page) && offset.equals(other.offset);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.page, this.offset);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<Integer> page = Optional.empty();

    private Optional<Integer> offset = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(GetAudienceIdMembersRequest other) {
      page(other.getPage());
      offset(other.getOffset());
      return this;
    }

    /**
     * <p>Page number for pagination (default is 1)</p>
     */
    @JsonSetter(
        value = "page",
        nulls = Nulls.SKIP
    )
    public Builder page(Optional<Integer> page) {
      this.page = page;
      return this;
    }

    public Builder page(Integer page) {
      this.page = Optional.ofNullable(page);
      return this;
    }

    /**
     * <p>Number of items per page (default is 5).
     * Note: this parameter is named &quot;offset&quot;, not &quot;limit&quot; — sending ?limit=N is silently ignored.</p>
     */
    @JsonSetter(
        value = "offset",
        nulls = Nulls.SKIP
    )
    public Builder offset(Optional<Integer> offset) {
      this.offset = offset;
      return this;
    }

    public Builder offset(Integer offset) {
      this.offset = Optional.ofNullable(offset);
      return this;
    }

    public GetAudienceIdMembersRequest build() {
      return new GetAudienceIdMembersRequest(page, offset, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
