/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.smallest.resources.atoms.agentversioningdrafts.requests;

import ai.smallest.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = CreateDraftRequest.Builder.class
)
public final class CreateDraftRequest {
  private final Optional<String> sourceVersionId;

  private final Optional<String> sourceDraftId;

  private final Optional<String> draftName;

  private final Map<String, Object> additionalProperties;

  private CreateDraftRequest(Optional<String> sourceVersionId, Optional<String> sourceDraftId,
      Optional<String> draftName, Map<String, Object> additionalProperties) {
    this.sourceVersionId = sourceVersionId;
    this.sourceDraftId = sourceDraftId;
    this.draftName = draftName;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return ID of a published version to branch from. Must be a valid MongoDB ObjectId (24-char hex).
   * Sending a non-ObjectId format returns 400.
   */
  @JsonProperty("sourceVersionId")
  public Optional<String> getSourceVersionId() {
    return sourceVersionId;
  }

  /**
   * @return ID of an existing draft to branch from
   */
  @JsonProperty("sourceDraftId")
  public Optional<String> getSourceDraftId() {
    return sourceDraftId;
  }

  /**
   * @return Optional name for the draft (1–100 characters)
   */
  @JsonProperty("draftName")
  public Optional<String> getDraftName() {
    return draftName;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof CreateDraftRequest && equalTo((CreateDraftRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(CreateDraftRequest other) {
    return sourceVersionId.equals(other.sourceVersionId) && sourceDraftId.equals(other.sourceDraftId) && draftName.equals(other.draftName);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.sourceVersionId, this.sourceDraftId, this.draftName);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<String> sourceVersionId = Optional.empty();

    private Optional<String> sourceDraftId = Optional.empty();

    private Optional<String> draftName = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(CreateDraftRequest other) {
      sourceVersionId(other.getSourceVersionId());
      sourceDraftId(other.getSourceDraftId());
      draftName(other.getDraftName());
      return this;
    }

    /**
     * <p>ID of a published version to branch from. Must be a valid MongoDB ObjectId (24-char hex).
     * Sending a non-ObjectId format returns 400.</p>
     */
    @JsonSetter(
        value = "sourceVersionId",
        nulls = Nulls.SKIP
    )
    public Builder sourceVersionId(Optional<String> sourceVersionId) {
      this.sourceVersionId = sourceVersionId;
      return this;
    }

    public Builder sourceVersionId(String sourceVersionId) {
      this.sourceVersionId = Optional.ofNullable(sourceVersionId);
      return this;
    }

    /**
     * <p>ID of an existing draft to branch from</p>
     */
    @JsonSetter(
        value = "sourceDraftId",
        nulls = Nulls.SKIP
    )
    public Builder sourceDraftId(Optional<String> sourceDraftId) {
      this.sourceDraftId = sourceDraftId;
      return this;
    }

    public Builder sourceDraftId(String sourceDraftId) {
      this.sourceDraftId = Optional.ofNullable(sourceDraftId);
      return this;
    }

    /**
     * <p>Optional name for the draft (1–100 characters)</p>
     */
    @JsonSetter(
        value = "draftName",
        nulls = Nulls.SKIP
    )
    public Builder draftName(Optional<String> draftName) {
      this.draftName = draftName;
      return this;
    }

    public Builder draftName(String draftName) {
      this.draftName = Optional.ofNullable(draftName);
      return this;
    }

    public CreateDraftRequest build() {
      return new CreateDraftRequest(sourceVersionId, sourceDraftId, draftName, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
