/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.smallest.resources.atoms.compliance.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class GetComplianceStatusRequestNumberType {
  public static final GetComplianceStatusRequestNumberType MOBILE = new GetComplianceStatusRequestNumberType(Value.MOBILE, "mobile");

  public static final GetComplianceStatusRequestNumberType TOLLFREE = new GetComplianceStatusRequestNumberType(Value.TOLLFREE, "tollfree");

  public static final GetComplianceStatusRequestNumberType LOCAL = new GetComplianceStatusRequestNumberType(Value.LOCAL, "local");

  private final Value value;

  private final String string;

  GetComplianceStatusRequestNumberType(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof GetComplianceStatusRequestNumberType && this.string.equals(((GetComplianceStatusRequestNumberType) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case MOBILE:
        return visitor.visitMobile();
      case TOLLFREE:
        return visitor.visitTollfree();
      case LOCAL:
        return visitor.visitLocal();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static GetComplianceStatusRequestNumberType valueOf(String value) {
    switch (value) {
      case "mobile":
        return MOBILE;
      case "tollfree":
        return TOLLFREE;
      case "local":
        return LOCAL;
      default:
        return new GetComplianceStatusRequestNumberType(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    LOCAL,

    MOBILE,

    TOLLFREE,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitLocal();

    T visitMobile();

    T visitTollfree();

    T visitUnknown(String unknownType);
  }
}
