/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.smallest.resources.atoms.promptscoring.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class PostPromptScoringScoreResponseDataDimensionsItemLevel {
  public static final PostPromptScoringScoreResponseDataDimensionsItemLevel MISSING = new PostPromptScoringScoreResponseDataDimensionsItemLevel(Value.MISSING, "Missing");

  public static final PostPromptScoringScoreResponseDataDimensionsItemLevel STRONG = new PostPromptScoringScoreResponseDataDimensionsItemLevel(Value.STRONG, "Strong");

  public static final PostPromptScoringScoreResponseDataDimensionsItemLevel ADEQUATE = new PostPromptScoringScoreResponseDataDimensionsItemLevel(Value.ADEQUATE, "Adequate");

  public static final PostPromptScoringScoreResponseDataDimensionsItemLevel NOT_APPLICABLE = new PostPromptScoringScoreResponseDataDimensionsItemLevel(Value.NOT_APPLICABLE, "Not Applicable");

  public static final PostPromptScoringScoreResponseDataDimensionsItemLevel WEAK = new PostPromptScoringScoreResponseDataDimensionsItemLevel(Value.WEAK, "Weak");

  private final Value value;

  private final String string;

  PostPromptScoringScoreResponseDataDimensionsItemLevel(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof PostPromptScoringScoreResponseDataDimensionsItemLevel && this.string.equals(((PostPromptScoringScoreResponseDataDimensionsItemLevel) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case MISSING:
        return visitor.visitMissing();
      case STRONG:
        return visitor.visitStrong();
      case ADEQUATE:
        return visitor.visitAdequate();
      case NOT_APPLICABLE:
        return visitor.visitNotApplicable();
      case WEAK:
        return visitor.visitWeak();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static PostPromptScoringScoreResponseDataDimensionsItemLevel valueOf(String value) {
    switch (value) {
      case "Missing":
        return MISSING;
      case "Strong":
        return STRONG;
      case "Adequate":
        return ADEQUATE;
      case "Not Applicable":
        return NOT_APPLICABLE;
      case "Weak":
        return WEAK;
      default:
        return new PostPromptScoringScoreResponseDataDimensionsItemLevel(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    STRONG,

    ADEQUATE,

    WEAK,

    MISSING,

    NOT_APPLICABLE,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitStrong();

    T visitAdequate();

    T visitWeak();

    T visitMissing();

    T visitNotApplicable();

    T visitUnknown(String unknownType);
  }
}
