/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.smallest.resources.atoms.webhooks;

import ai.smallest.core.ClientOptions;
import ai.smallest.core.MediaTypes;
import ai.smallest.core.ObjectMappers;
import ai.smallest.core.QueryStringMapper;
import ai.smallest.core.RequestOptions;
import ai.smallest.core.RetryInterceptor;
import ai.smallest.core.SmallestAIApiException;
import ai.smallest.core.SmallestAIException;
import ai.smallest.core.SmallestAIHttpResponse;
import ai.smallest.resources.atoms.errors.BadRequestError;
import ai.smallest.resources.atoms.errors.ForbiddenError;
import ai.smallest.resources.atoms.errors.InternalServerError;
import ai.smallest.resources.atoms.errors.NotFoundError;
import ai.smallest.resources.atoms.errors.UnauthorizedError;
import ai.smallest.resources.atoms.webhooks.requests.CreateWebhooksRequest;
import ai.smallest.resources.atoms.webhooks.requests.DeleteAgentAgentIdWebhookSubscriptionsRequest;
import ai.smallest.resources.atoms.webhooks.requests.DeleteWebhooksRequest;
import ai.smallest.resources.atoms.webhooks.requests.GetAgentAgentIdWebhookSubscriptionsRequest;
import ai.smallest.resources.atoms.webhooks.requests.GetWebhookRequest;
import ai.smallest.resources.atoms.webhooks.requests.PostAgentAgentIdWebhookSubscriptionsRequest;
import ai.smallest.resources.atoms.webhooks.types.CreateWebhooksResponse;
import ai.smallest.resources.atoms.webhooks.types.DeleteAgentAgentIdWebhookSubscriptionsResponse;
import ai.smallest.resources.atoms.webhooks.types.DeleteWebhooksResponse;
import ai.smallest.resources.atoms.webhooks.types.GetAgentAgentIdWebhookSubscriptionsResponse;
import ai.smallest.resources.atoms.webhooks.types.GetWebhookResponse;
import ai.smallest.resources.atoms.webhooks.types.PostAgentAgentIdWebhookSubscriptionsResponse;
import com.fasterxml.jackson.core.JsonProcessingException;
import java.io.IOException;
import java.lang.Object;
import java.lang.String;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;

public class RawWebhooksClient {
  protected final ClientOptions clientOptions;

  public RawWebhooksClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
  }

  /**
   * Retrieve all webhooks for the organization or a specific webhook by ID
   */
  public SmallestAIHttpResponse<GetWebhookResponse> getWebhooks() {
    return getWebhooks(GetWebhookRequest.builder().build());
  }

  /**
   * Retrieve all webhooks for the organization or a specific webhook by ID
   */
  public SmallestAIHttpResponse<GetWebhookResponse> getWebhooks(RequestOptions requestOptions) {
    return getWebhooks(GetWebhookRequest.builder().build(),requestOptions);
  }

  /**
   * Retrieve all webhooks for the organization or a specific webhook by ID
   */
  public SmallestAIHttpResponse<GetWebhookResponse> getWebhooks(GetWebhookRequest request) {
    return getWebhooks(request,null);
  }

  /**
   * Retrieve all webhooks for the organization or a specific webhook by ID
   */
  public SmallestAIHttpResponse<GetWebhookResponse> getWebhooks(GetWebhookRequest request,
      RequestOptions requestOptions) {
    HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getAtomsURL()).newBuilder()

      .addPathSegments("webhook");if (request.getWebhookId().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "webhookId", request.getWebhookId().get(), false);
      }
      if (requestOptions != null) {
        requestOptions.getQueryParameters().forEach((_key, _value) -> {
          httpUrl.addQueryParameter(_key, _value);
        } );
      }
      Request.Builder _requestBuilder = new Request.Builder()
        .url(httpUrl.build())
        .method("GET", null)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Accept", "application/json");
      Request okhttpRequest = _requestBuilder.build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
        okhttpRequest = okhttpRequest.newBuilder().tag(RetryInterceptor.MaxRetriesOverride.class, new RetryInterceptor.MaxRetriesOverride(requestOptions.getMaxRetries().get())).build();
      }
      try (Response response = client.newCall(okhttpRequest).execute()) {
        ResponseBody responseBody = response.body();
        String responseBodyString = responseBody != null ? responseBody.string() : "{}";
        if (response.isSuccessful()) {
          return new SmallestAIHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, GetWebhookResponse.class), response);
        }
        try {
          switch (response.code()) {
            case 400:throw new BadRequestError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
            case 401:throw new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
            case 500:throw new InternalServerError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
          }
        }
        catch (JsonProcessingException ignored) {
          // unable to map error response, throwing generic error
        }
        Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
        throw new SmallestAIApiException("Error with status code " + response.code(), response.code(), errorBody, response);
      }
      catch (JsonProcessingException e) {
        throw new SmallestAIException("Failed to deserialize response: " + e.getMessage(), e);
      }
      catch (IOException e) {
        throw new SmallestAIException("Network error executing HTTP request", e);
      }
    }

    /**
     * Create a new webhook with subscriptions for specific agents and events.
     * <p><strong>400 is also returned when the endpoint URL is already registered:</strong>
     * <code>&quot;A webhook with this URL has already been registered&quot;</code></p>
     */
    public SmallestAIHttpResponse<CreateWebhooksResponse> create(CreateWebhooksRequest request) {
      return create(request,null);
    }

    /**
     * Create a new webhook with subscriptions for specific agents and events.
     * <p><strong>400 is also returned when the endpoint URL is already registered:</strong>
     * <code>&quot;A webhook with this URL has already been registered&quot;</code></p>
     */
    public SmallestAIHttpResponse<CreateWebhooksResponse> create(CreateWebhooksRequest request,
        RequestOptions requestOptions) {
      HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getAtomsURL()).newBuilder()

        .addPathSegments("webhook");if (requestOptions != null) {
          requestOptions.getQueryParameters().forEach((_key, _value) -> {
            httpUrl.addQueryParameter(_key, _value);
          } );
        }
        RequestBody body;
        try {
          body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        }
        catch(JsonProcessingException e) {
          throw new SmallestAIException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
          .url(httpUrl.build())
          .method("POST", body)
          .headers(Headers.of(clientOptions.headers(requestOptions)))
          .addHeader("Content-Type", "application/json")
          .addHeader("Accept", "application/json")
          .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
          client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
          okhttpRequest = okhttpRequest.newBuilder().tag(RetryInterceptor.MaxRetriesOverride.class, new RetryInterceptor.MaxRetriesOverride(requestOptions.getMaxRetries().get())).build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
          ResponseBody responseBody = response.body();
          String responseBodyString = responseBody != null ? responseBody.string() : "{}";
          if (response.isSuccessful()) {
            return new SmallestAIHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, CreateWebhooksResponse.class), response);
          }
          try {
            switch (response.code()) {
              case 400:throw new BadRequestError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
              case 401:throw new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
              case 500:throw new InternalServerError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
            }
          }
          catch (JsonProcessingException ignored) {
            // unable to map error response, throwing generic error
          }
          Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
          throw new SmallestAIApiException("Error with status code " + response.code(), response.code(), errorBody, response);
        }
        catch (JsonProcessingException e) {
          throw new SmallestAIException("Failed to deserialize response: " + e.getMessage(), e);
        }
        catch (IOException e) {
          throw new SmallestAIException("Network error executing HTTP request", e);
        }
      }

      /**
       * Delete a webhook by its ID.
       * <p><strong>400 is returned when the webhook still has active agent subscriptions:</strong>
       * <code>&quot;Cannot delete webhook: It is currently assigned to one or more agents. Please remove all agent assignments first.&quot;</code>
       * Call <code>DELETE /agent/{agentId}/webhook-subscriptions</code> for each assigned agent before deleting.</p>
       * <p><strong>400 is also returned for an invalid webhook ID format:</strong>
       * <code>&quot;The provided Webhook ID is invalid.&quot;</code></p>
       */
      public SmallestAIHttpResponse<DeleteWebhooksResponse> delete(String id) {
        return delete(id,DeleteWebhooksRequest.builder().build());
      }

      /**
       * Delete a webhook by its ID.
       * <p><strong>400 is returned when the webhook still has active agent subscriptions:</strong>
       * <code>&quot;Cannot delete webhook: It is currently assigned to one or more agents. Please remove all agent assignments first.&quot;</code>
       * Call <code>DELETE /agent/{agentId}/webhook-subscriptions</code> for each assigned agent before deleting.</p>
       * <p><strong>400 is also returned for an invalid webhook ID format:</strong>
       * <code>&quot;The provided Webhook ID is invalid.&quot;</code></p>
       */
      public SmallestAIHttpResponse<DeleteWebhooksResponse> delete(String id,
          RequestOptions requestOptions) {
        return delete(id,DeleteWebhooksRequest.builder().build(),requestOptions);
      }

      /**
       * Delete a webhook by its ID.
       * <p><strong>400 is returned when the webhook still has active agent subscriptions:</strong>
       * <code>&quot;Cannot delete webhook: It is currently assigned to one or more agents. Please remove all agent assignments first.&quot;</code>
       * Call <code>DELETE /agent/{agentId}/webhook-subscriptions</code> for each assigned agent before deleting.</p>
       * <p><strong>400 is also returned for an invalid webhook ID format:</strong>
       * <code>&quot;The provided Webhook ID is invalid.&quot;</code></p>
       */
      public SmallestAIHttpResponse<DeleteWebhooksResponse> delete(String id,
          DeleteWebhooksRequest request) {
        return delete(id,request,null);
      }

      /**
       * Delete a webhook by its ID.
       * <p><strong>400 is returned when the webhook still has active agent subscriptions:</strong>
       * <code>&quot;Cannot delete webhook: It is currently assigned to one or more agents. Please remove all agent assignments first.&quot;</code>
       * Call <code>DELETE /agent/{agentId}/webhook-subscriptions</code> for each assigned agent before deleting.</p>
       * <p><strong>400 is also returned for an invalid webhook ID format:</strong>
       * <code>&quot;The provided Webhook ID is invalid.&quot;</code></p>
       */
      public SmallestAIHttpResponse<DeleteWebhooksResponse> delete(String id,
          DeleteWebhooksRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getAtomsURL()).newBuilder()

          .addPathSegments("webhook")
          .addPathSegment(id);if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
              httpUrl.addQueryParameter(_key, _value);
            } );
          }
          Request.Builder _requestBuilder = new Request.Builder()
            .url(httpUrl.build())
            .method("DELETE", null)
            .headers(Headers.of(clientOptions.headers(requestOptions)))
            .addHeader("Accept", "application/json");
          Request okhttpRequest = _requestBuilder.build();
          OkHttpClient client = clientOptions.httpClient();
          if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
          }
          if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest.newBuilder().tag(RetryInterceptor.MaxRetriesOverride.class, new RetryInterceptor.MaxRetriesOverride(requestOptions.getMaxRetries().get())).build();
          }
          try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
              return new SmallestAIHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, DeleteWebhooksResponse.class), response);
            }
            try {
              switch (response.code()) {
                case 400:throw new BadRequestError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                case 401:throw new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                case 404:throw new NotFoundError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                case 500:throw new InternalServerError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
              }
            }
            catch (JsonProcessingException ignored) {
              // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new SmallestAIApiException("Error with status code " + response.code(), response.code(), errorBody, response);
          }
          catch (JsonProcessingException e) {
            throw new SmallestAIException("Failed to deserialize response: " + e.getMessage(), e);
          }
          catch (IOException e) {
            throw new SmallestAIException("Network error executing HTTP request", e);
          }
        }

        /**
         * Retrieve webhook subscriptions for a given agent ID
         */
        public SmallestAIHttpResponse<GetAgentAgentIdWebhookSubscriptionsResponse> getWebhookSubscriptionsForAnAgent(
            String agentId) {
          return getWebhookSubscriptionsForAnAgent(agentId,GetAgentAgentIdWebhookSubscriptionsRequest.builder().build());
        }

        /**
         * Retrieve webhook subscriptions for a given agent ID
         */
        public SmallestAIHttpResponse<GetAgentAgentIdWebhookSubscriptionsResponse> getWebhookSubscriptionsForAnAgent(
            String agentId, RequestOptions requestOptions) {
          return getWebhookSubscriptionsForAnAgent(agentId,GetAgentAgentIdWebhookSubscriptionsRequest.builder().build(),requestOptions);
        }

        /**
         * Retrieve webhook subscriptions for a given agent ID
         */
        public SmallestAIHttpResponse<GetAgentAgentIdWebhookSubscriptionsResponse> getWebhookSubscriptionsForAnAgent(
            String agentId, GetAgentAgentIdWebhookSubscriptionsRequest request) {
          return getWebhookSubscriptionsForAnAgent(agentId,request,null);
        }

        /**
         * Retrieve webhook subscriptions for a given agent ID
         */
        public SmallestAIHttpResponse<GetAgentAgentIdWebhookSubscriptionsResponse> getWebhookSubscriptionsForAnAgent(
            String agentId, GetAgentAgentIdWebhookSubscriptionsRequest request,
            RequestOptions requestOptions) {
          HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getAtomsURL()).newBuilder()

            .addPathSegments("agent")
            .addPathSegment(agentId)
            .addPathSegments("webhook-subscriptions");if (requestOptions != null) {
              requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
              } );
            }
            Request.Builder _requestBuilder = new Request.Builder()
              .url(httpUrl.build())
              .method("GET", null)
              .headers(Headers.of(clientOptions.headers(requestOptions)))
              .addHeader("Accept", "application/json");
            Request okhttpRequest = _requestBuilder.build();
            OkHttpClient client = clientOptions.httpClient();
            if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
              client = clientOptions.httpClientWithTimeout(requestOptions);
            }
            if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
              okhttpRequest = okhttpRequest.newBuilder().tag(RetryInterceptor.MaxRetriesOverride.class, new RetryInterceptor.MaxRetriesOverride(requestOptions.getMaxRetries().get())).build();
            }
            try (Response response = client.newCall(okhttpRequest).execute()) {
              ResponseBody responseBody = response.body();
              String responseBodyString = responseBody != null ? responseBody.string() : "{}";
              if (response.isSuccessful()) {
                return new SmallestAIHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, GetAgentAgentIdWebhookSubscriptionsResponse.class), response);
              }
              try {
                switch (response.code()) {
                  case 400:throw new BadRequestError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                  case 401:throw new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                  case 403:throw new ForbiddenError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                  case 404:throw new NotFoundError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                  case 500:throw new InternalServerError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                }
              }
              catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
              }
              Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
              throw new SmallestAIApiException("Error with status code " + response.code(), response.code(), errorBody, response);
            }
            catch (JsonProcessingException e) {
              throw new SmallestAIException("Failed to deserialize response: " + e.getMessage(), e);
            }
            catch (IOException e) {
              throw new SmallestAIException("Network error executing HTTP request", e);
            }
          }

          /**
           * <strong>Replaces</strong> all existing webhook subscriptions for the agent with the provided event types.
           * Any previously configured subscriptions for this agent are deleted before the new ones are created.
           * To add subscriptions without removing existing ones, retrieve current subscriptions first and include them in the request.
           */
          public SmallestAIHttpResponse<PostAgentAgentIdWebhookSubscriptionsResponse> replaceWebhookSubscriptionsForAnAgent(
              String agentId, PostAgentAgentIdWebhookSubscriptionsRequest request) {
            return replaceWebhookSubscriptionsForAnAgent(agentId,request,null);
          }

          /**
           * <strong>Replaces</strong> all existing webhook subscriptions for the agent with the provided event types.
           * Any previously configured subscriptions for this agent are deleted before the new ones are created.
           * To add subscriptions without removing existing ones, retrieve current subscriptions first and include them in the request.
           */
          public SmallestAIHttpResponse<PostAgentAgentIdWebhookSubscriptionsResponse> replaceWebhookSubscriptionsForAnAgent(
              String agentId, PostAgentAgentIdWebhookSubscriptionsRequest request,
              RequestOptions requestOptions) {
            HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getAtomsURL()).newBuilder()

              .addPathSegments("agent")
              .addPathSegment(agentId)
              .addPathSegments("webhook-subscriptions");if (requestOptions != null) {
                requestOptions.getQueryParameters().forEach((_key, _value) -> {
                  httpUrl.addQueryParameter(_key, _value);
                } );
              }
              RequestBody body;
              try {
                body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
              }
              catch(JsonProcessingException e) {
                throw new SmallestAIException("Failed to serialize request", e);
              }
              Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
              OkHttpClient client = clientOptions.httpClient();
              if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
                client = clientOptions.httpClientWithTimeout(requestOptions);
              }
              if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
                okhttpRequest = okhttpRequest.newBuilder().tag(RetryInterceptor.MaxRetriesOverride.class, new RetryInterceptor.MaxRetriesOverride(requestOptions.getMaxRetries().get())).build();
              }
              try (Response response = client.newCall(okhttpRequest).execute()) {
                ResponseBody responseBody = response.body();
                String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                if (response.isSuccessful()) {
                  return new SmallestAIHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, PostAgentAgentIdWebhookSubscriptionsResponse.class), response);
                }
                try {
                  switch (response.code()) {
                    case 400:throw new BadRequestError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 401:throw new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 403:throw new ForbiddenError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 404:throw new NotFoundError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 500:throw new InternalServerError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                  }
                }
                catch (JsonProcessingException ignored) {
                  // unable to map error response, throwing generic error
                }
                Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                throw new SmallestAIApiException("Error with status code " + response.code(), response.code(), errorBody, response);
              }
              catch (JsonProcessingException e) {
                throw new SmallestAIException("Failed to deserialize response: " + e.getMessage(), e);
              }
              catch (IOException e) {
                throw new SmallestAIException("Network error executing HTTP request", e);
              }
            }

            /**
             * Deletes <strong>all</strong> webhook subscriptions for the agent, regardless of which webhook they belong to.
             * If the agent has subscriptions across multiple webhooks, all of them are removed in a single call.
             */
            public SmallestAIHttpResponse<DeleteAgentAgentIdWebhookSubscriptionsResponse> deleteWebhookSubscriptionsForAnAgent(
                String agentId) {
              return deleteWebhookSubscriptionsForAnAgent(agentId,DeleteAgentAgentIdWebhookSubscriptionsRequest.builder().build());
            }

            /**
             * Deletes <strong>all</strong> webhook subscriptions for the agent, regardless of which webhook they belong to.
             * If the agent has subscriptions across multiple webhooks, all of them are removed in a single call.
             */
            public SmallestAIHttpResponse<DeleteAgentAgentIdWebhookSubscriptionsResponse> deleteWebhookSubscriptionsForAnAgent(
                String agentId, RequestOptions requestOptions) {
              return deleteWebhookSubscriptionsForAnAgent(agentId,DeleteAgentAgentIdWebhookSubscriptionsRequest.builder().build(),requestOptions);
            }

            /**
             * Deletes <strong>all</strong> webhook subscriptions for the agent, regardless of which webhook they belong to.
             * If the agent has subscriptions across multiple webhooks, all of them are removed in a single call.
             */
            public SmallestAIHttpResponse<DeleteAgentAgentIdWebhookSubscriptionsResponse> deleteWebhookSubscriptionsForAnAgent(
                String agentId, DeleteAgentAgentIdWebhookSubscriptionsRequest request) {
              return deleteWebhookSubscriptionsForAnAgent(agentId,request,null);
            }

            /**
             * Deletes <strong>all</strong> webhook subscriptions for the agent, regardless of which webhook they belong to.
             * If the agent has subscriptions across multiple webhooks, all of them are removed in a single call.
             */
            public SmallestAIHttpResponse<DeleteAgentAgentIdWebhookSubscriptionsResponse> deleteWebhookSubscriptionsForAnAgent(
                String agentId, DeleteAgentAgentIdWebhookSubscriptionsRequest request,
                RequestOptions requestOptions) {
              HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getAtomsURL()).newBuilder()

                .addPathSegments("agent")
                .addPathSegment(agentId)
                .addPathSegments("webhook-subscriptions");if (requestOptions != null) {
                  requestOptions.getQueryParameters().forEach((_key, _value) -> {
                    httpUrl.addQueryParameter(_key, _value);
                  } );
                }
                Request.Builder _requestBuilder = new Request.Builder()
                  .url(httpUrl.build())
                  .method("DELETE", null)
                  .headers(Headers.of(clientOptions.headers(requestOptions)))
                  .addHeader("Accept", "application/json");
                Request okhttpRequest = _requestBuilder.build();
                OkHttpClient client = clientOptions.httpClient();
                if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
                  client = clientOptions.httpClientWithTimeout(requestOptions);
                }
                if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
                  okhttpRequest = okhttpRequest.newBuilder().tag(RetryInterceptor.MaxRetriesOverride.class, new RetryInterceptor.MaxRetriesOverride(requestOptions.getMaxRetries().get())).build();
                }
                try (Response response = client.newCall(okhttpRequest).execute()) {
                  ResponseBody responseBody = response.body();
                  String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                  if (response.isSuccessful()) {
                    return new SmallestAIHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, DeleteAgentAgentIdWebhookSubscriptionsResponse.class), response);
                  }
                  try {
                    switch (response.code()) {
                      case 400:throw new BadRequestError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                      case 401:throw new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                      case 403:throw new ForbiddenError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                      case 404:throw new NotFoundError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                      case 500:throw new InternalServerError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    }
                  }
                  catch (JsonProcessingException ignored) {
                    // unable to map error response, throwing generic error
                  }
                  Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                  throw new SmallestAIApiException("Error with status code " + response.code(), response.code(), errorBody, response);
                }
                catch (JsonProcessingException e) {
                  throw new SmallestAIException("Failed to deserialize response: " + e.getMessage(), e);
                }
                catch (IOException e) {
                  throw new SmallestAIException("Network error executing HTTP request", e);
                }
              }
            }
