/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.smallest.resources.atoms.livetranscripts.types;

import ai.smallest.core.Nullable;
import ai.smallest.core.NullableNonemptyFilter;
import ai.smallest.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Boolean;
import java.lang.Double;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = SubscribeToLiveEventsLiveTranscriptsResponse.Builder.class
)
public final class SubscribeToLiveEventsLiveTranscriptsResponse {
  private final Optional<SubscribeToLiveEventsLiveTranscriptsResponseEventType> eventType;

  private final Optional<String> eventId;

  private final Optional<OffsetDateTime> timestamp;

  private final Optional<String> callId;

  private final Optional<OffsetDateTime> eventTime;

  private final Optional<String> telephonyId;

  private final Optional<Map<String, Object>> metadata;

  private final Optional<Double> turnLatency;

  private final Optional<Double> sttApiMs;

  private final Optional<Double> sttToLlmMs;

  private final Optional<Double> smartTurnMs;

  private final Optional<Double> llmApiMs;

  private final Optional<Double> llmToTtsMs;

  private final Optional<Double> ttsApiMs;

  private final Optional<Double> ttsToAudioMs;

  private final Optional<Double> totalTurnMs;

  private final Optional<Integer> turnIndex;

  private final Optional<Boolean> interrupted;

  private final Optional<Boolean> smartTurnEnabled;

  private final Optional<String> interimTranscriptionText;

  private final Optional<String> userTranscriptionText;

  private final Optional<String> ttsText;

  private final Optional<Integer> ttsLatency;

  private final Optional<List<SubscribeToLiveEventsLiveTranscriptsResponseMetricsItem>> metrics;

  private final Optional<String> nodeId;

  private final Optional<String> nodeName;

  private final Optional<String> nodeType;

  private final Optional<Map<String, Object>> context;

  private final Optional<String> fromNodeId;

  private final Optional<String> toNodeId;

  private final Optional<String> knowledgeBaseId;

  private final Optional<String> userTranscript;

  private final Optional<Object> response;

  private final Optional<Double> latency;

  private final Optional<Object> error;

  private final Optional<Map<String, Object>> variables;

  private final Optional<String> variableExtractionPrompt;

  private final Optional<String> method;

  private final Optional<Map<String, Object>> headers;

  private final Optional<Object> body;

  private final Optional<Double> timeout;

  private final Optional<Map<String, Object>> extractedVariables;

  private final Optional<String> nextNodeId;

  private final Optional<Boolean> success;

  private final Optional<String> turnId;

  private final Optional<String> toolCallId;

  private final Optional<String> functionName;

  private final Optional<Double> latencyMs;

  private final Optional<String> recordingUrl;

  private final Optional<String> status;

  private final Map<String, Object> additionalProperties;

  private SubscribeToLiveEventsLiveTranscriptsResponse(
      Optional<SubscribeToLiveEventsLiveTranscriptsResponseEventType> eventType,
      Optional<String> eventId, Optional<OffsetDateTime> timestamp, Optional<String> callId,
      Optional<OffsetDateTime> eventTime, Optional<String> telephonyId,
      Optional<Map<String, Object>> metadata, Optional<Double> turnLatency,
      Optional<Double> sttApiMs, Optional<Double> sttToLlmMs, Optional<Double> smartTurnMs,
      Optional<Double> llmApiMs, Optional<Double> llmToTtsMs, Optional<Double> ttsApiMs,
      Optional<Double> ttsToAudioMs, Optional<Double> totalTurnMs, Optional<Integer> turnIndex,
      Optional<Boolean> interrupted, Optional<Boolean> smartTurnEnabled,
      Optional<String> interimTranscriptionText, Optional<String> userTranscriptionText,
      Optional<String> ttsText, Optional<Integer> ttsLatency,
      Optional<List<SubscribeToLiveEventsLiveTranscriptsResponseMetricsItem>> metrics,
      Optional<String> nodeId, Optional<String> nodeName, Optional<String> nodeType,
      Optional<Map<String, Object>> context, Optional<String> fromNodeId, Optional<String> toNodeId,
      Optional<String> knowledgeBaseId, Optional<String> userTranscript, Optional<Object> response,
      Optional<Double> latency, Optional<Object> error, Optional<Map<String, Object>> variables,
      Optional<String> variableExtractionPrompt, Optional<String> method,
      Optional<Map<String, Object>> headers, Optional<Object> body, Optional<Double> timeout,
      Optional<Map<String, Object>> extractedVariables, Optional<String> nextNodeId,
      Optional<Boolean> success, Optional<String> turnId, Optional<String> toolCallId,
      Optional<String> functionName, Optional<Double> latencyMs, Optional<String> recordingUrl,
      Optional<String> status, Map<String, Object> additionalProperties) {
    this.eventType = eventType;
    this.eventId = eventId;
    this.timestamp = timestamp;
    this.callId = callId;
    this.eventTime = eventTime;
    this.telephonyId = telephonyId;
    this.metadata = metadata;
    this.turnLatency = turnLatency;
    this.sttApiMs = sttApiMs;
    this.sttToLlmMs = sttToLlmMs;
    this.smartTurnMs = smartTurnMs;
    this.llmApiMs = llmApiMs;
    this.llmToTtsMs = llmToTtsMs;
    this.ttsApiMs = ttsApiMs;
    this.ttsToAudioMs = ttsToAudioMs;
    this.totalTurnMs = totalTurnMs;
    this.turnIndex = turnIndex;
    this.interrupted = interrupted;
    this.smartTurnEnabled = smartTurnEnabled;
    this.interimTranscriptionText = interimTranscriptionText;
    this.userTranscriptionText = userTranscriptionText;
    this.ttsText = ttsText;
    this.ttsLatency = ttsLatency;
    this.metrics = metrics;
    this.nodeId = nodeId;
    this.nodeName = nodeName;
    this.nodeType = nodeType;
    this.context = context;
    this.fromNodeId = fromNodeId;
    this.toNodeId = toNodeId;
    this.knowledgeBaseId = knowledgeBaseId;
    this.userTranscript = userTranscript;
    this.response = response;
    this.latency = latency;
    this.error = error;
    this.variables = variables;
    this.variableExtractionPrompt = variableExtractionPrompt;
    this.method = method;
    this.headers = headers;
    this.body = body;
    this.timeout = timeout;
    this.extractedVariables = extractedVariables;
    this.nextNodeId = nextNodeId;
    this.success = success;
    this.turnId = turnId;
    this.toolCallId = toolCallId;
    this.functionName = functionName;
    this.latencyMs = latencyMs;
    this.recordingUrl = recordingUrl;
    this.status = status;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return The type of event
   */
  @JsonProperty("event_type")
  public Optional<SubscribeToLiveEventsLiveTranscriptsResponseEventType> getEventType() {
    return eventType;
  }

  /**
   * @return Unique identifier for the event
   */
  @JsonProperty("event_id")
  public Optional<String> getEventId() {
    return eventId;
  }

  /**
   * @return ISO 8601 timestamp of the event
   */
  @JsonProperty("timestamp")
  public Optional<OffsetDateTime> getTimestamp() {
    return timestamp;
  }

  /**
   * @return The call ID this event belongs to
   */
  @JsonProperty("call_id")
  public Optional<String> getCallId() {
    return callId;
  }

  /**
   * @return Timestamp used by <code>sse_init</code> and <code>sse_close</code>
   */
  @JsonProperty("event_time")
  public Optional<OffsetDateTime> getEventTime() {
    return eventTime;
  }

  /**
   * @return Telephony ID for <code>call_start</code>
   */
  @JsonProperty("telephony_id")
  public Optional<String> getTelephonyId() {
    return telephonyId;
  }

  /**
   * @return Metadata for <code>call_end</code>, <code>agent_error</code>, or <code>agent_log</code>
   */
  @JsonProperty("metadata")
  public Optional<Map<String, Object>> getMetadata() {
    return metadata;
  }

  /**
   * @return Turn latency value for <code>turn_latency</code>
   */
  @JsonProperty("turn_latency")
  public Optional<Double> getTurnLatency() {
    return turnLatency;
  }

  /**
   * @return STT API latency in milliseconds for <code>turn_latency</code>
   */
  @JsonProperty("stt_api_ms")
  public Optional<Double> getSttApiMs() {
    return sttApiMs;
  }

  /**
   * @return STT-to-LLM latency in milliseconds for <code>turn_latency</code>
   */
  @JsonProperty("stt_to_llm_ms")
  public Optional<Double> getSttToLlmMs() {
    return sttToLlmMs;
  }

  /**
   * @return Smart-turn latency in milliseconds for <code>turn_latency</code>
   */
  @JsonProperty("smart_turn_ms")
  public Optional<Double> getSmartTurnMs() {
    return smartTurnMs;
  }

  /**
   * @return LLM API latency in milliseconds for <code>turn_latency</code>
   */
  @JsonProperty("llm_api_ms")
  public Optional<Double> getLlmApiMs() {
    return llmApiMs;
  }

  /**
   * @return LLM-to-TTS latency in milliseconds for <code>turn_latency</code>
   */
  @JsonProperty("llm_to_tts_ms")
  public Optional<Double> getLlmToTtsMs() {
    return llmToTtsMs;
  }

  /**
   * @return TTS API latency in milliseconds for <code>turn_latency</code>
   */
  @JsonProperty("tts_api_ms")
  public Optional<Double> getTtsApiMs() {
    return ttsApiMs;
  }

  /**
   * @return TTS-to-audio latency in milliseconds for <code>turn_latency</code>
   */
  @JsonProperty("tts_to_audio_ms")
  public Optional<Double> getTtsToAudioMs() {
    return ttsToAudioMs;
  }

  /**
   * @return Total turn latency in milliseconds for <code>turn_latency</code>
   */
  @JsonProperty("total_turn_ms")
  public Optional<Double> getTotalTurnMs() {
    return totalTurnMs;
  }

  /**
   * @return Turn index for <code>turn_latency</code>
   */
  @JsonProperty("turn_index")
  public Optional<Integer> getTurnIndex() {
    return turnIndex;
  }

  /**
   * @return Whether the turn was interrupted for <code>turn_latency</code>
   */
  @JsonProperty("interrupted")
  public Optional<Boolean> getInterrupted() {
    return interrupted;
  }

  /**
   * @return Whether smart turn was enabled for <code>turn_latency</code>
   */
  @JsonProperty("smart_turn_enabled")
  public Optional<Boolean> getSmartTurnEnabled() {
    return smartTurnEnabled;
  }

  /**
   * @return Partial transcription text (only for <code>user_interim_transcription</code>)
   */
  @JsonProperty("interim_transcription_text")
  public Optional<String> getInterimTranscriptionText() {
    return interimTranscriptionText;
  }

  /**
   * @return Final transcription text (only for <code>user_transcription</code>)
   */
  @JsonProperty("user_transcription_text")
  public Optional<String> getUserTranscriptionText() {
    return userTranscriptionText;
  }

  /**
   * @return Text spoken by the agent (only for <code>tts_completed</code>)
   */
  @JsonProperty("tts_text")
  public Optional<String> getTtsText() {
    return ttsText;
  }

  /**
   * @return TTS latency in milliseconds (only for <code>tts_completed</code>)
   */
  @JsonProperty("tts_latency")
  public Optional<Integer> getTtsLatency() {
    return ttsLatency;
  }

  /**
   * @return Per-turn metrics payload for <code>metrics</code> events. Server emits an
   * <strong>array</strong> of <code>{processor, model, value}</code> entries (one per
   * pipeline stage), not a single object. The SDK previously
   * dropped every <code>metrics</code> SSE event with a pydantic
   * ValidationError when this was typed as an object (122
   * events on a 40s call); typing it as an array of objects
   * fixes the decode.
   */
  @JsonProperty("metrics")
  public Optional<List<SubscribeToLiveEventsLiveTranscriptsResponseMetricsItem>> getMetrics() {
    return metrics;
  }

  /**
   * @return Node ID for <code>agent_node_state</code>
   */
  @JsonProperty("node_id")
  public Optional<String> getNodeId() {
    return nodeId;
  }

  /**
   * @return Node name for <code>agent_node_state</code>
   */
  @JsonProperty("node_name")
  public Optional<String> getNodeName() {
    return nodeName;
  }

  /**
   * @return Node type for <code>agent_node_state</code>
   */
  @JsonProperty("node_type")
  public Optional<String> getNodeType() {
    return nodeType;
  }

  /**
   * @return Context payload for agent-node and tool-call events
   */
  @JsonProperty("context")
  public Optional<Map<String, Object>> getContext() {
    return context;
  }

  /**
   * @return Source node ID for <code>hopping</code>
   */
  @JsonProperty("from_node_id")
  public Optional<String> getFromNodeId() {
    return fromNodeId;
  }

  /**
   * @return Destination node ID for <code>hopping</code>
   */
  @JsonProperty("to_node_id")
  public Optional<String> getToNodeId() {
    return toNodeId;
  }

  /**
   * @return Knowledge base ID for <code>knowledgebase</code>
   */
  @JsonProperty("knowledge_base_id")
  public Optional<String> getKnowledgeBaseId() {
    return knowledgeBaseId;
  }

  /**
   * @return User transcript for <code>knowledgebase</code>
   */
  @JsonProperty("user_transcript")
  public Optional<String> getUserTranscript() {
    return userTranscript;
  }

  /**
   * @return Response payload for knowledgebase, API, or tool-call events
   */
  @JsonIgnore
  public Optional<Object> getResponse() {
    if (response == null) {
      return Optional.empty();
    }
    return response;
  }

  /**
   * @return Latency for <code>knowledgebase</code> or <code>variable_extraction</code>
   */
  @JsonProperty("latency")
  public Optional<Double> getLatency() {
    return latency;
  }

  /**
   * @return Error payload for knowledgebase, variable extraction, API, tool, or agent error events
   */
  @JsonIgnore
  public Optional<Object> getError() {
    if (error == null) {
      return Optional.empty();
    }
    return error;
  }

  /**
   * @return Variables extracted by <code>variable_extraction</code>
   */
  @JsonProperty("variables")
  public Optional<Map<String, Object>> getVariables() {
    return variables;
  }

  /**
   * @return Prompt used for <code>variable_extraction</code>
   */
  @JsonProperty("variable_extraction_prompt")
  public Optional<String> getVariableExtractionPrompt() {
    return variableExtractionPrompt;
  }

  /**
   * @return HTTP method for <code>pre_call_api</code> or <code>post_call_api</code>
   */
  @JsonProperty("method")
  public Optional<String> getMethod() {
    return method;
  }

  /**
   * @return Headers for <code>pre_call_api</code> or <code>post_call_api</code>
   */
  @JsonProperty("headers")
  public Optional<Map<String, Object>> getHeaders() {
    return headers;
  }

  /**
   * @return Body for <code>pre_call_api</code> or <code>post_call_api</code>
   */
  @JsonIgnore
  public Optional<Object> getBody() {
    if (body == null) {
      return Optional.empty();
    }
    return body;
  }

  /**
   * @return Timeout for <code>pre_call_api</code> or <code>post_call_api</code>
   */
  @JsonProperty("timeout")
  public Optional<Double> getTimeout() {
    return timeout;
  }

  /**
   * @return Extracted variables for <code>pre_call_api</code> or <code>post_call_api</code>
   */
  @JsonProperty("extracted_variables")
  public Optional<Map<String, Object>> getExtractedVariables() {
    return extractedVariables;
  }

  /**
   * @return Next node ID for <code>pre_call_api</code> or <code>post_call_api</code>
   */
  @JsonProperty("next_node_id")
  public Optional<String> getNextNodeId() {
    return nextNodeId;
  }

  /**
   * @return Success status for API and tool-call events
   */
  @JsonProperty("success")
  public Optional<Boolean> getSuccess() {
    return success;
  }

  /**
   * @return Turn ID for tool-call events
   */
  @JsonProperty("turn_id")
  public Optional<String> getTurnId() {
    return turnId;
  }

  /**
   * @return Tool call ID for tool-call events
   */
  @JsonProperty("tool_call_id")
  public Optional<String> getToolCallId() {
    return toolCallId;
  }

  /**
   * @return Function name for tool-call events
   */
  @JsonProperty("function_name")
  public Optional<String> getFunctionName() {
    return functionName;
  }

  /**
   * @return Latency in milliseconds for <code>tool_call_end</code>
   */
  @JsonProperty("latency_ms")
  public Optional<Double> getLatencyMs() {
    return latencyMs;
  }

  /**
   * @return Recording URL for <code>call_recording</code>
   */
  @JsonProperty("recording_url")
  public Optional<String> getRecordingUrl() {
    return recordingUrl;
  }

  /**
   * @return Recording status for <code>call_recording</code>
   */
  @JsonProperty("status")
  public Optional<String> getStatus() {
    return status;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("response")
  private Optional<Object> _getResponse() {
    return response;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("error")
  private Optional<Object> _getError() {
    return error;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("body")
  private Optional<Object> _getBody() {
    return body;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof SubscribeToLiveEventsLiveTranscriptsResponse && equalTo((SubscribeToLiveEventsLiveTranscriptsResponse) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(SubscribeToLiveEventsLiveTranscriptsResponse other) {
    return eventType.equals(other.eventType) && eventId.equals(other.eventId) && timestamp.equals(other.timestamp) && callId.equals(other.callId) && eventTime.equals(other.eventTime) && telephonyId.equals(other.telephonyId) && metadata.equals(other.metadata) && turnLatency.equals(other.turnLatency) && sttApiMs.equals(other.sttApiMs) && sttToLlmMs.equals(other.sttToLlmMs) && smartTurnMs.equals(other.smartTurnMs) && llmApiMs.equals(other.llmApiMs) && llmToTtsMs.equals(other.llmToTtsMs) && ttsApiMs.equals(other.ttsApiMs) && ttsToAudioMs.equals(other.ttsToAudioMs) && totalTurnMs.equals(other.totalTurnMs) && turnIndex.equals(other.turnIndex) && interrupted.equals(other.interrupted) && smartTurnEnabled.equals(other.smartTurnEnabled) && interimTranscriptionText.equals(other.interimTranscriptionText) && userTranscriptionText.equals(other.userTranscriptionText) && ttsText.equals(other.ttsText) && ttsLatency.equals(other.ttsLatency) && metrics.equals(other.metrics) && nodeId.equals(other.nodeId) && nodeName.equals(other.nodeName) && nodeType.equals(other.nodeType) && context.equals(other.context) && fromNodeId.equals(other.fromNodeId) && toNodeId.equals(other.toNodeId) && knowledgeBaseId.equals(other.knowledgeBaseId) && userTranscript.equals(other.userTranscript) && response.equals(other.response) && latency.equals(other.latency) && error.equals(other.error) && variables.equals(other.variables) && variableExtractionPrompt.equals(other.variableExtractionPrompt) && method.equals(other.method) && headers.equals(other.headers) && body.equals(other.body) && timeout.equals(other.timeout) && extractedVariables.equals(other.extractedVariables) && nextNodeId.equals(other.nextNodeId) && success.equals(other.success) && turnId.equals(other.turnId) && toolCallId.equals(other.toolCallId) && functionName.equals(other.functionName) && latencyMs.equals(other.latencyMs) && recordingUrl.equals(other.recordingUrl) && status.equals(other.status);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.eventType, this.eventId, this.timestamp, this.callId, this.eventTime, this.telephonyId, this.metadata, this.turnLatency, this.sttApiMs, this.sttToLlmMs, this.smartTurnMs, this.llmApiMs, this.llmToTtsMs, this.ttsApiMs, this.ttsToAudioMs, this.totalTurnMs, this.turnIndex, this.interrupted, this.smartTurnEnabled, this.interimTranscriptionText, this.userTranscriptionText, this.ttsText, this.ttsLatency, this.metrics, this.nodeId, this.nodeName, this.nodeType, this.context, this.fromNodeId, this.toNodeId, this.knowledgeBaseId, this.userTranscript, this.response, this.latency, this.error, this.variables, this.variableExtractionPrompt, this.method, this.headers, this.body, this.timeout, this.extractedVariables, this.nextNodeId, this.success, this.turnId, this.toolCallId, this.functionName, this.latencyMs, this.recordingUrl, this.status);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<SubscribeToLiveEventsLiveTranscriptsResponseEventType> eventType = Optional.empty();

    private Optional<String> eventId = Optional.empty();

    private Optional<OffsetDateTime> timestamp = Optional.empty();

    private Optional<String> callId = Optional.empty();

    private Optional<OffsetDateTime> eventTime = Optional.empty();

    private Optional<String> telephonyId = Optional.empty();

    private Optional<Map<String, Object>> metadata = Optional.empty();

    private Optional<Double> turnLatency = Optional.empty();

    private Optional<Double> sttApiMs = Optional.empty();

    private Optional<Double> sttToLlmMs = Optional.empty();

    private Optional<Double> smartTurnMs = Optional.empty();

    private Optional<Double> llmApiMs = Optional.empty();

    private Optional<Double> llmToTtsMs = Optional.empty();

    private Optional<Double> ttsApiMs = Optional.empty();

    private Optional<Double> ttsToAudioMs = Optional.empty();

    private Optional<Double> totalTurnMs = Optional.empty();

    private Optional<Integer> turnIndex = Optional.empty();

    private Optional<Boolean> interrupted = Optional.empty();

    private Optional<Boolean> smartTurnEnabled = Optional.empty();

    private Optional<String> interimTranscriptionText = Optional.empty();

    private Optional<String> userTranscriptionText = Optional.empty();

    private Optional<String> ttsText = Optional.empty();

    private Optional<Integer> ttsLatency = Optional.empty();

    private Optional<List<SubscribeToLiveEventsLiveTranscriptsResponseMetricsItem>> metrics = Optional.empty();

    private Optional<String> nodeId = Optional.empty();

    private Optional<String> nodeName = Optional.empty();

    private Optional<String> nodeType = Optional.empty();

    private Optional<Map<String, Object>> context = Optional.empty();

    private Optional<String> fromNodeId = Optional.empty();

    private Optional<String> toNodeId = Optional.empty();

    private Optional<String> knowledgeBaseId = Optional.empty();

    private Optional<String> userTranscript = Optional.empty();

    private Optional<Object> response = Optional.empty();

    private Optional<Double> latency = Optional.empty();

    private Optional<Object> error = Optional.empty();

    private Optional<Map<String, Object>> variables = Optional.empty();

    private Optional<String> variableExtractionPrompt = Optional.empty();

    private Optional<String> method = Optional.empty();

    private Optional<Map<String, Object>> headers = Optional.empty();

    private Optional<Object> body = Optional.empty();

    private Optional<Double> timeout = Optional.empty();

    private Optional<Map<String, Object>> extractedVariables = Optional.empty();

    private Optional<String> nextNodeId = Optional.empty();

    private Optional<Boolean> success = Optional.empty();

    private Optional<String> turnId = Optional.empty();

    private Optional<String> toolCallId = Optional.empty();

    private Optional<String> functionName = Optional.empty();

    private Optional<Double> latencyMs = Optional.empty();

    private Optional<String> recordingUrl = Optional.empty();

    private Optional<String> status = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(SubscribeToLiveEventsLiveTranscriptsResponse other) {
      eventType(other.getEventType());
      eventId(other.getEventId());
      timestamp(other.getTimestamp());
      callId(other.getCallId());
      eventTime(other.getEventTime());
      telephonyId(other.getTelephonyId());
      metadata(other.getMetadata());
      turnLatency(other.getTurnLatency());
      sttApiMs(other.getSttApiMs());
      sttToLlmMs(other.getSttToLlmMs());
      smartTurnMs(other.getSmartTurnMs());
      llmApiMs(other.getLlmApiMs());
      llmToTtsMs(other.getLlmToTtsMs());
      ttsApiMs(other.getTtsApiMs());
      ttsToAudioMs(other.getTtsToAudioMs());
      totalTurnMs(other.getTotalTurnMs());
      turnIndex(other.getTurnIndex());
      interrupted(other.getInterrupted());
      smartTurnEnabled(other.getSmartTurnEnabled());
      interimTranscriptionText(other.getInterimTranscriptionText());
      userTranscriptionText(other.getUserTranscriptionText());
      ttsText(other.getTtsText());
      ttsLatency(other.getTtsLatency());
      metrics(other.getMetrics());
      nodeId(other.getNodeId());
      nodeName(other.getNodeName());
      nodeType(other.getNodeType());
      context(other.getContext());
      fromNodeId(other.getFromNodeId());
      toNodeId(other.getToNodeId());
      knowledgeBaseId(other.getKnowledgeBaseId());
      userTranscript(other.getUserTranscript());
      response(other.getResponse());
      latency(other.getLatency());
      error(other.getError());
      variables(other.getVariables());
      variableExtractionPrompt(other.getVariableExtractionPrompt());
      method(other.getMethod());
      headers(other.getHeaders());
      body(other.getBody());
      timeout(other.getTimeout());
      extractedVariables(other.getExtractedVariables());
      nextNodeId(other.getNextNodeId());
      success(other.getSuccess());
      turnId(other.getTurnId());
      toolCallId(other.getToolCallId());
      functionName(other.getFunctionName());
      latencyMs(other.getLatencyMs());
      recordingUrl(other.getRecordingUrl());
      status(other.getStatus());
      return this;
    }

    /**
     * <p>The type of event</p>
     */
    @JsonSetter(
        value = "event_type",
        nulls = Nulls.SKIP
    )
    public Builder eventType(
        Optional<SubscribeToLiveEventsLiveTranscriptsResponseEventType> eventType) {
      this.eventType = eventType;
      return this;
    }

    public Builder eventType(SubscribeToLiveEventsLiveTranscriptsResponseEventType eventType) {
      this.eventType = Optional.ofNullable(eventType);
      return this;
    }

    /**
     * <p>Unique identifier for the event</p>
     */
    @JsonSetter(
        value = "event_id",
        nulls = Nulls.SKIP
    )
    public Builder eventId(Optional<String> eventId) {
      this.eventId = eventId;
      return this;
    }

    public Builder eventId(String eventId) {
      this.eventId = Optional.ofNullable(eventId);
      return this;
    }

    /**
     * <p>ISO 8601 timestamp of the event</p>
     */
    @JsonSetter(
        value = "timestamp",
        nulls = Nulls.SKIP
    )
    public Builder timestamp(Optional<OffsetDateTime> timestamp) {
      this.timestamp = timestamp;
      return this;
    }

    public Builder timestamp(OffsetDateTime timestamp) {
      this.timestamp = Optional.ofNullable(timestamp);
      return this;
    }

    /**
     * <p>The call ID this event belongs to</p>
     */
    @JsonSetter(
        value = "call_id",
        nulls = Nulls.SKIP
    )
    public Builder callId(Optional<String> callId) {
      this.callId = callId;
      return this;
    }

    public Builder callId(String callId) {
      this.callId = Optional.ofNullable(callId);
      return this;
    }

    /**
     * <p>Timestamp used by <code>sse_init</code> and <code>sse_close</code></p>
     */
    @JsonSetter(
        value = "event_time",
        nulls = Nulls.SKIP
    )
    public Builder eventTime(Optional<OffsetDateTime> eventTime) {
      this.eventTime = eventTime;
      return this;
    }

    public Builder eventTime(OffsetDateTime eventTime) {
      this.eventTime = Optional.ofNullable(eventTime);
      return this;
    }

    /**
     * <p>Telephony ID for <code>call_start</code></p>
     */
    @JsonSetter(
        value = "telephony_id",
        nulls = Nulls.SKIP
    )
    public Builder telephonyId(Optional<String> telephonyId) {
      this.telephonyId = telephonyId;
      return this;
    }

    public Builder telephonyId(String telephonyId) {
      this.telephonyId = Optional.ofNullable(telephonyId);
      return this;
    }

    /**
     * <p>Metadata for <code>call_end</code>, <code>agent_error</code>, or <code>agent_log</code></p>
     */
    @JsonSetter(
        value = "metadata",
        nulls = Nulls.SKIP
    )
    public Builder metadata(Optional<Map<String, Object>> metadata) {
      this.metadata = metadata;
      return this;
    }

    public Builder metadata(Map<String, Object> metadata) {
      this.metadata = Optional.ofNullable(metadata);
      return this;
    }

    /**
     * <p>Turn latency value for <code>turn_latency</code></p>
     */
    @JsonSetter(
        value = "turn_latency",
        nulls = Nulls.SKIP
    )
    public Builder turnLatency(Optional<Double> turnLatency) {
      this.turnLatency = turnLatency;
      return this;
    }

    public Builder turnLatency(Double turnLatency) {
      this.turnLatency = Optional.ofNullable(turnLatency);
      return this;
    }

    /**
     * <p>STT API latency in milliseconds for <code>turn_latency</code></p>
     */
    @JsonSetter(
        value = "stt_api_ms",
        nulls = Nulls.SKIP
    )
    public Builder sttApiMs(Optional<Double> sttApiMs) {
      this.sttApiMs = sttApiMs;
      return this;
    }

    public Builder sttApiMs(Double sttApiMs) {
      this.sttApiMs = Optional.ofNullable(sttApiMs);
      return this;
    }

    /**
     * <p>STT-to-LLM latency in milliseconds for <code>turn_latency</code></p>
     */
    @JsonSetter(
        value = "stt_to_llm_ms",
        nulls = Nulls.SKIP
    )
    public Builder sttToLlmMs(Optional<Double> sttToLlmMs) {
      this.sttToLlmMs = sttToLlmMs;
      return this;
    }

    public Builder sttToLlmMs(Double sttToLlmMs) {
      this.sttToLlmMs = Optional.ofNullable(sttToLlmMs);
      return this;
    }

    /**
     * <p>Smart-turn latency in milliseconds for <code>turn_latency</code></p>
     */
    @JsonSetter(
        value = "smart_turn_ms",
        nulls = Nulls.SKIP
    )
    public Builder smartTurnMs(Optional<Double> smartTurnMs) {
      this.smartTurnMs = smartTurnMs;
      return this;
    }

    public Builder smartTurnMs(Double smartTurnMs) {
      this.smartTurnMs = Optional.ofNullable(smartTurnMs);
      return this;
    }

    /**
     * <p>LLM API latency in milliseconds for <code>turn_latency</code></p>
     */
    @JsonSetter(
        value = "llm_api_ms",
        nulls = Nulls.SKIP
    )
    public Builder llmApiMs(Optional<Double> llmApiMs) {
      this.llmApiMs = llmApiMs;
      return this;
    }

    public Builder llmApiMs(Double llmApiMs) {
      this.llmApiMs = Optional.ofNullable(llmApiMs);
      return this;
    }

    /**
     * <p>LLM-to-TTS latency in milliseconds for <code>turn_latency</code></p>
     */
    @JsonSetter(
        value = "llm_to_tts_ms",
        nulls = Nulls.SKIP
    )
    public Builder llmToTtsMs(Optional<Double> llmToTtsMs) {
      this.llmToTtsMs = llmToTtsMs;
      return this;
    }

    public Builder llmToTtsMs(Double llmToTtsMs) {
      this.llmToTtsMs = Optional.ofNullable(llmToTtsMs);
      return this;
    }

    /**
     * <p>TTS API latency in milliseconds for <code>turn_latency</code></p>
     */
    @JsonSetter(
        value = "tts_api_ms",
        nulls = Nulls.SKIP
    )
    public Builder ttsApiMs(Optional<Double> ttsApiMs) {
      this.ttsApiMs = ttsApiMs;
      return this;
    }

    public Builder ttsApiMs(Double ttsApiMs) {
      this.ttsApiMs = Optional.ofNullable(ttsApiMs);
      return this;
    }

    /**
     * <p>TTS-to-audio latency in milliseconds for <code>turn_latency</code></p>
     */
    @JsonSetter(
        value = "tts_to_audio_ms",
        nulls = Nulls.SKIP
    )
    public Builder ttsToAudioMs(Optional<Double> ttsToAudioMs) {
      this.ttsToAudioMs = ttsToAudioMs;
      return this;
    }

    public Builder ttsToAudioMs(Double ttsToAudioMs) {
      this.ttsToAudioMs = Optional.ofNullable(ttsToAudioMs);
      return this;
    }

    /**
     * <p>Total turn latency in milliseconds for <code>turn_latency</code></p>
     */
    @JsonSetter(
        value = "total_turn_ms",
        nulls = Nulls.SKIP
    )
    public Builder totalTurnMs(Optional<Double> totalTurnMs) {
      this.totalTurnMs = totalTurnMs;
      return this;
    }

    public Builder totalTurnMs(Double totalTurnMs) {
      this.totalTurnMs = Optional.ofNullable(totalTurnMs);
      return this;
    }

    /**
     * <p>Turn index for <code>turn_latency</code></p>
     */
    @JsonSetter(
        value = "turn_index",
        nulls = Nulls.SKIP
    )
    public Builder turnIndex(Optional<Integer> turnIndex) {
      this.turnIndex = turnIndex;
      return this;
    }

    public Builder turnIndex(Integer turnIndex) {
      this.turnIndex = Optional.ofNullable(turnIndex);
      return this;
    }

    /**
     * <p>Whether the turn was interrupted for <code>turn_latency</code></p>
     */
    @JsonSetter(
        value = "interrupted",
        nulls = Nulls.SKIP
    )
    public Builder interrupted(Optional<Boolean> interrupted) {
      this.interrupted = interrupted;
      return this;
    }

    public Builder interrupted(Boolean interrupted) {
      this.interrupted = Optional.ofNullable(interrupted);
      return this;
    }

    /**
     * <p>Whether smart turn was enabled for <code>turn_latency</code></p>
     */
    @JsonSetter(
        value = "smart_turn_enabled",
        nulls = Nulls.SKIP
    )
    public Builder smartTurnEnabled(Optional<Boolean> smartTurnEnabled) {
      this.smartTurnEnabled = smartTurnEnabled;
      return this;
    }

    public Builder smartTurnEnabled(Boolean smartTurnEnabled) {
      this.smartTurnEnabled = Optional.ofNullable(smartTurnEnabled);
      return this;
    }

    /**
     * <p>Partial transcription text (only for <code>user_interim_transcription</code>)</p>
     */
    @JsonSetter(
        value = "interim_transcription_text",
        nulls = Nulls.SKIP
    )
    public Builder interimTranscriptionText(Optional<String> interimTranscriptionText) {
      this.interimTranscriptionText = interimTranscriptionText;
      return this;
    }

    public Builder interimTranscriptionText(String interimTranscriptionText) {
      this.interimTranscriptionText = Optional.ofNullable(interimTranscriptionText);
      return this;
    }

    /**
     * <p>Final transcription text (only for <code>user_transcription</code>)</p>
     */
    @JsonSetter(
        value = "user_transcription_text",
        nulls = Nulls.SKIP
    )
    public Builder userTranscriptionText(Optional<String> userTranscriptionText) {
      this.userTranscriptionText = userTranscriptionText;
      return this;
    }

    public Builder userTranscriptionText(String userTranscriptionText) {
      this.userTranscriptionText = Optional.ofNullable(userTranscriptionText);
      return this;
    }

    /**
     * <p>Text spoken by the agent (only for <code>tts_completed</code>)</p>
     */
    @JsonSetter(
        value = "tts_text",
        nulls = Nulls.SKIP
    )
    public Builder ttsText(Optional<String> ttsText) {
      this.ttsText = ttsText;
      return this;
    }

    public Builder ttsText(String ttsText) {
      this.ttsText = Optional.ofNullable(ttsText);
      return this;
    }

    /**
     * <p>TTS latency in milliseconds (only for <code>tts_completed</code>)</p>
     */
    @JsonSetter(
        value = "tts_latency",
        nulls = Nulls.SKIP
    )
    public Builder ttsLatency(Optional<Integer> ttsLatency) {
      this.ttsLatency = ttsLatency;
      return this;
    }

    public Builder ttsLatency(Integer ttsLatency) {
      this.ttsLatency = Optional.ofNullable(ttsLatency);
      return this;
    }

    /**
     * <p>Per-turn metrics payload for <code>metrics</code> events. Server emits an
     * <strong>array</strong> of <code>{processor, model, value}</code> entries (one per
     * pipeline stage), not a single object. The SDK previously
     * dropped every <code>metrics</code> SSE event with a pydantic
     * ValidationError when this was typed as an object (122
     * events on a 40s call); typing it as an array of objects
     * fixes the decode.</p>
     */
    @JsonSetter(
        value = "metrics",
        nulls = Nulls.SKIP
    )
    public Builder metrics(
        Optional<List<SubscribeToLiveEventsLiveTranscriptsResponseMetricsItem>> metrics) {
      this.metrics = metrics;
      return this;
    }

    public Builder metrics(List<SubscribeToLiveEventsLiveTranscriptsResponseMetricsItem> metrics) {
      this.metrics = Optional.ofNullable(metrics);
      return this;
    }

    /**
     * <p>Node ID for <code>agent_node_state</code></p>
     */
    @JsonSetter(
        value = "node_id",
        nulls = Nulls.SKIP
    )
    public Builder nodeId(Optional<String> nodeId) {
      this.nodeId = nodeId;
      return this;
    }

    public Builder nodeId(String nodeId) {
      this.nodeId = Optional.ofNullable(nodeId);
      return this;
    }

    /**
     * <p>Node name for <code>agent_node_state</code></p>
     */
    @JsonSetter(
        value = "node_name",
        nulls = Nulls.SKIP
    )
    public Builder nodeName(Optional<String> nodeName) {
      this.nodeName = nodeName;
      return this;
    }

    public Builder nodeName(String nodeName) {
      this.nodeName = Optional.ofNullable(nodeName);
      return this;
    }

    /**
     * <p>Node type for <code>agent_node_state</code></p>
     */
    @JsonSetter(
        value = "node_type",
        nulls = Nulls.SKIP
    )
    public Builder nodeType(Optional<String> nodeType) {
      this.nodeType = nodeType;
      return this;
    }

    public Builder nodeType(String nodeType) {
      this.nodeType = Optional.ofNullable(nodeType);
      return this;
    }

    /**
     * <p>Context payload for agent-node and tool-call events</p>
     */
    @JsonSetter(
        value = "context",
        nulls = Nulls.SKIP
    )
    public Builder context(Optional<Map<String, Object>> context) {
      this.context = context;
      return this;
    }

    public Builder context(Map<String, Object> context) {
      this.context = Optional.ofNullable(context);
      return this;
    }

    /**
     * <p>Source node ID for <code>hopping</code></p>
     */
    @JsonSetter(
        value = "from_node_id",
        nulls = Nulls.SKIP
    )
    public Builder fromNodeId(Optional<String> fromNodeId) {
      this.fromNodeId = fromNodeId;
      return this;
    }

    public Builder fromNodeId(String fromNodeId) {
      this.fromNodeId = Optional.ofNullable(fromNodeId);
      return this;
    }

    /**
     * <p>Destination node ID for <code>hopping</code></p>
     */
    @JsonSetter(
        value = "to_node_id",
        nulls = Nulls.SKIP
    )
    public Builder toNodeId(Optional<String> toNodeId) {
      this.toNodeId = toNodeId;
      return this;
    }

    public Builder toNodeId(String toNodeId) {
      this.toNodeId = Optional.ofNullable(toNodeId);
      return this;
    }

    /**
     * <p>Knowledge base ID for <code>knowledgebase</code></p>
     */
    @JsonSetter(
        value = "knowledge_base_id",
        nulls = Nulls.SKIP
    )
    public Builder knowledgeBaseId(Optional<String> knowledgeBaseId) {
      this.knowledgeBaseId = knowledgeBaseId;
      return this;
    }

    public Builder knowledgeBaseId(String knowledgeBaseId) {
      this.knowledgeBaseId = Optional.ofNullable(knowledgeBaseId);
      return this;
    }

    /**
     * <p>User transcript for <code>knowledgebase</code></p>
     */
    @JsonSetter(
        value = "user_transcript",
        nulls = Nulls.SKIP
    )
    public Builder userTranscript(Optional<String> userTranscript) {
      this.userTranscript = userTranscript;
      return this;
    }

    public Builder userTranscript(String userTranscript) {
      this.userTranscript = Optional.ofNullable(userTranscript);
      return this;
    }

    /**
     * <p>Response payload for knowledgebase, API, or tool-call events</p>
     */
    @JsonSetter(
        value = "response",
        nulls = Nulls.SKIP
    )
    public Builder response(Optional<Object> response) {
      this.response = response;
      return this;
    }

    public Builder response(Object response) {
      this.response = Optional.ofNullable(response);
      return this;
    }

    public Builder response(Nullable<Object> response) {
      if (response.isNull()) {
        this.response = null;
      }
      else if (response.isEmpty()) {
        this.response = Optional.empty();
      }
      else {
        this.response = Optional.of(response.get());
      }
      return this;
    }

    /**
     * <p>Latency for <code>knowledgebase</code> or <code>variable_extraction</code></p>
     */
    @JsonSetter(
        value = "latency",
        nulls = Nulls.SKIP
    )
    public Builder latency(Optional<Double> latency) {
      this.latency = latency;
      return this;
    }

    public Builder latency(Double latency) {
      this.latency = Optional.ofNullable(latency);
      return this;
    }

    /**
     * <p>Error payload for knowledgebase, variable extraction, API, tool, or agent error events</p>
     */
    @JsonSetter(
        value = "error",
        nulls = Nulls.SKIP
    )
    public Builder error(Optional<Object> error) {
      this.error = error;
      return this;
    }

    public Builder error(Object error) {
      this.error = Optional.ofNullable(error);
      return this;
    }

    public Builder error(Nullable<Object> error) {
      if (error.isNull()) {
        this.error = null;
      }
      else if (error.isEmpty()) {
        this.error = Optional.empty();
      }
      else {
        this.error = Optional.of(error.get());
      }
      return this;
    }

    /**
     * <p>Variables extracted by <code>variable_extraction</code></p>
     */
    @JsonSetter(
        value = "variables",
        nulls = Nulls.SKIP
    )
    public Builder variables(Optional<Map<String, Object>> variables) {
      this.variables = variables;
      return this;
    }

    public Builder variables(Map<String, Object> variables) {
      this.variables = Optional.ofNullable(variables);
      return this;
    }

    /**
     * <p>Prompt used for <code>variable_extraction</code></p>
     */
    @JsonSetter(
        value = "variable_extraction_prompt",
        nulls = Nulls.SKIP
    )
    public Builder variableExtractionPrompt(Optional<String> variableExtractionPrompt) {
      this.variableExtractionPrompt = variableExtractionPrompt;
      return this;
    }

    public Builder variableExtractionPrompt(String variableExtractionPrompt) {
      this.variableExtractionPrompt = Optional.ofNullable(variableExtractionPrompt);
      return this;
    }

    /**
     * <p>HTTP method for <code>pre_call_api</code> or <code>post_call_api</code></p>
     */
    @JsonSetter(
        value = "method",
        nulls = Nulls.SKIP
    )
    public Builder method(Optional<String> method) {
      this.method = method;
      return this;
    }

    public Builder method(String method) {
      this.method = Optional.ofNullable(method);
      return this;
    }

    /**
     * <p>Headers for <code>pre_call_api</code> or <code>post_call_api</code></p>
     */
    @JsonSetter(
        value = "headers",
        nulls = Nulls.SKIP
    )
    public Builder headers(Optional<Map<String, Object>> headers) {
      this.headers = headers;
      return this;
    }

    public Builder headers(Map<String, Object> headers) {
      this.headers = Optional.ofNullable(headers);
      return this;
    }

    /**
     * <p>Body for <code>pre_call_api</code> or <code>post_call_api</code></p>
     */
    @JsonSetter(
        value = "body",
        nulls = Nulls.SKIP
    )
    public Builder body(Optional<Object> body) {
      this.body = body;
      return this;
    }

    public Builder body(Object body) {
      this.body = Optional.ofNullable(body);
      return this;
    }

    public Builder body(Nullable<Object> body) {
      if (body.isNull()) {
        this.body = null;
      }
      else if (body.isEmpty()) {
        this.body = Optional.empty();
      }
      else {
        this.body = Optional.of(body.get());
      }
      return this;
    }

    /**
     * <p>Timeout for <code>pre_call_api</code> or <code>post_call_api</code></p>
     */
    @JsonSetter(
        value = "timeout",
        nulls = Nulls.SKIP
    )
    public Builder timeout(Optional<Double> timeout) {
      this.timeout = timeout;
      return this;
    }

    public Builder timeout(Double timeout) {
      this.timeout = Optional.ofNullable(timeout);
      return this;
    }

    /**
     * <p>Extracted variables for <code>pre_call_api</code> or <code>post_call_api</code></p>
     */
    @JsonSetter(
        value = "extracted_variables",
        nulls = Nulls.SKIP
    )
    public Builder extractedVariables(Optional<Map<String, Object>> extractedVariables) {
      this.extractedVariables = extractedVariables;
      return this;
    }

    public Builder extractedVariables(Map<String, Object> extractedVariables) {
      this.extractedVariables = Optional.ofNullable(extractedVariables);
      return this;
    }

    /**
     * <p>Next node ID for <code>pre_call_api</code> or <code>post_call_api</code></p>
     */
    @JsonSetter(
        value = "next_node_id",
        nulls = Nulls.SKIP
    )
    public Builder nextNodeId(Optional<String> nextNodeId) {
      this.nextNodeId = nextNodeId;
      return this;
    }

    public Builder nextNodeId(String nextNodeId) {
      this.nextNodeId = Optional.ofNullable(nextNodeId);
      return this;
    }

    /**
     * <p>Success status for API and tool-call events</p>
     */
    @JsonSetter(
        value = "success",
        nulls = Nulls.SKIP
    )
    public Builder success(Optional<Boolean> success) {
      this.success = success;
      return this;
    }

    public Builder success(Boolean success) {
      this.success = Optional.ofNullable(success);
      return this;
    }

    /**
     * <p>Turn ID for tool-call events</p>
     */
    @JsonSetter(
        value = "turn_id",
        nulls = Nulls.SKIP
    )
    public Builder turnId(Optional<String> turnId) {
      this.turnId = turnId;
      return this;
    }

    public Builder turnId(String turnId) {
      this.turnId = Optional.ofNullable(turnId);
      return this;
    }

    /**
     * <p>Tool call ID for tool-call events</p>
     */
    @JsonSetter(
        value = "tool_call_id",
        nulls = Nulls.SKIP
    )
    public Builder toolCallId(Optional<String> toolCallId) {
      this.toolCallId = toolCallId;
      return this;
    }

    public Builder toolCallId(String toolCallId) {
      this.toolCallId = Optional.ofNullable(toolCallId);
      return this;
    }

    /**
     * <p>Function name for tool-call events</p>
     */
    @JsonSetter(
        value = "function_name",
        nulls = Nulls.SKIP
    )
    public Builder functionName(Optional<String> functionName) {
      this.functionName = functionName;
      return this;
    }

    public Builder functionName(String functionName) {
      this.functionName = Optional.ofNullable(functionName);
      return this;
    }

    /**
     * <p>Latency in milliseconds for <code>tool_call_end</code></p>
     */
    @JsonSetter(
        value = "latency_ms",
        nulls = Nulls.SKIP
    )
    public Builder latencyMs(Optional<Double> latencyMs) {
      this.latencyMs = latencyMs;
      return this;
    }

    public Builder latencyMs(Double latencyMs) {
      this.latencyMs = Optional.ofNullable(latencyMs);
      return this;
    }

    /**
     * <p>Recording URL for <code>call_recording</code></p>
     */
    @JsonSetter(
        value = "recording_url",
        nulls = Nulls.SKIP
    )
    public Builder recordingUrl(Optional<String> recordingUrl) {
      this.recordingUrl = recordingUrl;
      return this;
    }

    public Builder recordingUrl(String recordingUrl) {
      this.recordingUrl = Optional.ofNullable(recordingUrl);
      return this;
    }

    /**
     * <p>Recording status for <code>call_recording</code></p>
     */
    @JsonSetter(
        value = "status",
        nulls = Nulls.SKIP
    )
    public Builder status(Optional<String> status) {
      this.status = status;
      return this;
    }

    public Builder status(String status) {
      this.status = Optional.ofNullable(status);
      return this;
    }

    public SubscribeToLiveEventsLiveTranscriptsResponse build() {
      return new SubscribeToLiveEventsLiveTranscriptsResponse(eventType, eventId, timestamp, callId, eventTime, telephonyId, metadata, turnLatency, sttApiMs, sttToLlmMs, smartTurnMs, llmApiMs, llmToTtsMs, ttsApiMs, ttsToAudioMs, totalTurnMs, turnIndex, interrupted, smartTurnEnabled, interimTranscriptionText, userTranscriptionText, ttsText, ttsLatency, metrics, nodeId, nodeName, nodeType, context, fromNodeId, toNodeId, knowledgeBaseId, userTranscript, response, latency, error, variables, variableExtractionPrompt, method, headers, body, timeout, extractedVariables, nextNodeId, success, turnId, toolCallId, functionName, latencyMs, recordingUrl, status, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
