/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.smallest.resources.atoms.types;

import ai.smallest.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = AgentDtoPreCallApi.Builder.class
)
public final class AgentDtoPreCallApi {
  private final Optional<Boolean> isEnabled;

  private final String url;

  private final AgentDtoPreCallApiMethod method;

  private final Optional<Map<String, String>> headers;

  private final Optional<Map<String, Object>> body;

  private final Optional<Integer> timeout;

  private final Optional<Map<String, Object>> queryParams;

  private final Optional<List<AgentDtoPreCallApiResponseVariablesItem>> responseVariables;

  private final Map<String, Object> additionalProperties;

  private AgentDtoPreCallApi(Optional<Boolean> isEnabled, String url,
      AgentDtoPreCallApiMethod method, Optional<Map<String, String>> headers,
      Optional<Map<String, Object>> body, Optional<Integer> timeout,
      Optional<Map<String, Object>> queryParams,
      Optional<List<AgentDtoPreCallApiResponseVariablesItem>> responseVariables,
      Map<String, Object> additionalProperties) {
    this.isEnabled = isEnabled;
    this.url = url;
    this.method = method;
    this.headers = headers;
    this.body = body;
    this.timeout = timeout;
    this.queryParams = queryParams;
    this.responseVariables = responseVariables;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Whether the pre-call API is enabled.
   */
  @JsonProperty("isEnabled")
  public Optional<Boolean> getIsEnabled() {
    return isEnabled;
  }

  /**
   * @return The URL of the API endpoint to call.
   */
  @JsonProperty("url")
  public String getUrl() {
    return url;
  }

  /**
   * @return The HTTP method to use for the API call.
   */
  @JsonProperty("method")
  public AgentDtoPreCallApiMethod getMethod() {
    return method;
  }

  /**
   * @return Optional HTTP headers to include in the request.
   */
  @JsonProperty("headers")
  public Optional<Map<String, String>> getHeaders() {
    return headers;
  }

  /**
   * @return Optional request body for POST/PUT/PATCH requests.
   */
  @JsonProperty("body")
  public Optional<Map<String, Object>> getBody() {
    return body;
  }

  /**
   * @return Timeout in seconds for the API call.
   */
  @JsonProperty("timeout")
  public Optional<Integer> getTimeout() {
    return timeout;
  }

  /**
   * @return Optional query parameters to include in the request URL.
   */
  @JsonProperty("queryParams")
  public Optional<Map<String, Object>> getQueryParams() {
    return queryParams;
  }

  /**
   * @return List of variables to extract from the API response using JSON path expressions.
   */
  @JsonProperty("responseVariables")
  public Optional<List<AgentDtoPreCallApiResponseVariablesItem>> getResponseVariables() {
    return responseVariables;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof AgentDtoPreCallApi && equalTo((AgentDtoPreCallApi) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(AgentDtoPreCallApi other) {
    return isEnabled.equals(other.isEnabled) && url.equals(other.url) && method.equals(other.method) && headers.equals(other.headers) && body.equals(other.body) && timeout.equals(other.timeout) && queryParams.equals(other.queryParams) && responseVariables.equals(other.responseVariables);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.isEnabled, this.url, this.method, this.headers, this.body, this.timeout, this.queryParams, this.responseVariables);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static UrlStage builder() {
    return new Builder();
  }

  public interface UrlStage {
    /**
     * <p>The URL of the API endpoint to call.</p>
     */
    MethodStage url(@NotNull String url);

    Builder from(AgentDtoPreCallApi other);
  }

  public interface MethodStage {
    /**
     * <p>The HTTP method to use for the API call.</p>
     */
    _FinalStage method(@NotNull AgentDtoPreCallApiMethod method);
  }

  public interface _FinalStage {
    AgentDtoPreCallApi build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /**
     * <p>Whether the pre-call API is enabled.</p>
     */
    _FinalStage isEnabled(Optional<Boolean> isEnabled);

    _FinalStage isEnabled(Boolean isEnabled);

    /**
     * <p>Optional HTTP headers to include in the request.</p>
     */
    _FinalStage headers(Optional<Map<String, String>> headers);

    _FinalStage headers(Map<String, String> headers);

    /**
     * <p>Optional request body for POST/PUT/PATCH requests.</p>
     */
    _FinalStage body(Optional<Map<String, Object>> body);

    _FinalStage body(Map<String, Object> body);

    /**
     * <p>Timeout in seconds for the API call.</p>
     */
    _FinalStage timeout(Optional<Integer> timeout);

    _FinalStage timeout(Integer timeout);

    /**
     * <p>Optional query parameters to include in the request URL.</p>
     */
    _FinalStage queryParams(Optional<Map<String, Object>> queryParams);

    _FinalStage queryParams(Map<String, Object> queryParams);

    /**
     * <p>List of variables to extract from the API response using JSON path expressions.</p>
     */
    _FinalStage responseVariables(
        Optional<List<AgentDtoPreCallApiResponseVariablesItem>> responseVariables);

    _FinalStage responseVariables(List<AgentDtoPreCallApiResponseVariablesItem> responseVariables);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements UrlStage, MethodStage, _FinalStage {
    private String url;

    private AgentDtoPreCallApiMethod method;

    private Optional<List<AgentDtoPreCallApiResponseVariablesItem>> responseVariables = Optional.empty();

    private Optional<Map<String, Object>> queryParams = Optional.empty();

    private Optional<Integer> timeout = Optional.empty();

    private Optional<Map<String, Object>> body = Optional.empty();

    private Optional<Map<String, String>> headers = Optional.empty();

    private Optional<Boolean> isEnabled = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(AgentDtoPreCallApi other) {
      isEnabled(other.getIsEnabled());
      url(other.getUrl());
      method(other.getMethod());
      headers(other.getHeaders());
      body(other.getBody());
      timeout(other.getTimeout());
      queryParams(other.getQueryParams());
      responseVariables(other.getResponseVariables());
      return this;
    }

    /**
     * <p>The URL of the API endpoint to call.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("url")
    public MethodStage url(@NotNull String url) {
      this.url = Objects.requireNonNull(url, "url must not be null");
      return this;
    }

    /**
     * <p>The HTTP method to use for the API call.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("method")
    public _FinalStage method(@NotNull AgentDtoPreCallApiMethod method) {
      this.method = Objects.requireNonNull(method, "method must not be null");
      return this;
    }

    /**
     * <p>List of variables to extract from the API response using JSON path expressions.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage responseVariables(
        List<AgentDtoPreCallApiResponseVariablesItem> responseVariables) {
      this.responseVariables = Optional.ofNullable(responseVariables);
      return this;
    }

    /**
     * <p>List of variables to extract from the API response using JSON path expressions.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "responseVariables",
        nulls = Nulls.SKIP
    )
    public _FinalStage responseVariables(
        Optional<List<AgentDtoPreCallApiResponseVariablesItem>> responseVariables) {
      this.responseVariables = responseVariables;
      return this;
    }

    /**
     * <p>Optional query parameters to include in the request URL.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage queryParams(Map<String, Object> queryParams) {
      this.queryParams = Optional.ofNullable(queryParams);
      return this;
    }

    /**
     * <p>Optional query parameters to include in the request URL.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "queryParams",
        nulls = Nulls.SKIP
    )
    public _FinalStage queryParams(Optional<Map<String, Object>> queryParams) {
      this.queryParams = queryParams;
      return this;
    }

    /**
     * <p>Timeout in seconds for the API call.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage timeout(Integer timeout) {
      this.timeout = Optional.ofNullable(timeout);
      return this;
    }

    /**
     * <p>Timeout in seconds for the API call.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "timeout",
        nulls = Nulls.SKIP
    )
    public _FinalStage timeout(Optional<Integer> timeout) {
      this.timeout = timeout;
      return this;
    }

    /**
     * <p>Optional request body for POST/PUT/PATCH requests.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage body(Map<String, Object> body) {
      this.body = Optional.ofNullable(body);
      return this;
    }

    /**
     * <p>Optional request body for POST/PUT/PATCH requests.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "body",
        nulls = Nulls.SKIP
    )
    public _FinalStage body(Optional<Map<String, Object>> body) {
      this.body = body;
      return this;
    }

    /**
     * <p>Optional HTTP headers to include in the request.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage headers(Map<String, String> headers) {
      this.headers = Optional.ofNullable(headers);
      return this;
    }

    /**
     * <p>Optional HTTP headers to include in the request.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "headers",
        nulls = Nulls.SKIP
    )
    public _FinalStage headers(Optional<Map<String, String>> headers) {
      this.headers = headers;
      return this;
    }

    /**
     * <p>Whether the pre-call API is enabled.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage isEnabled(Boolean isEnabled) {
      this.isEnabled = Optional.ofNullable(isEnabled);
      return this;
    }

    /**
     * <p>Whether the pre-call API is enabled.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "isEnabled",
        nulls = Nulls.SKIP
    )
    public _FinalStage isEnabled(Optional<Boolean> isEnabled) {
      this.isEnabled = isEnabled;
      return this;
    }

    @java.lang.Override
    public AgentDtoPreCallApi build() {
      return new AgentDtoPreCallApi(isEnabled, url, method, headers, body, timeout, queryParams, responseVariables, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
