/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.smallest.resources.atoms.types;

import ai.smallest.core.Nullable;
import ai.smallest.core.NullableNonemptyFilter;
import ai.smallest.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = AgentVersionDiffDiffsItemChangesItem.Builder.class
)
public final class AgentVersionDiffDiffsItemChangesItem {
  private final Optional<String> path;

  private final Optional<AgentVersionDiffDiffsItemChangesItemOldValue> oldValue;

  private final Optional<AgentVersionDiffDiffsItemChangesItemNewValue> newValue;

  private final Map<String, Object> additionalProperties;

  private AgentVersionDiffDiffsItemChangesItem(Optional<String> path,
      Optional<AgentVersionDiffDiffsItemChangesItemOldValue> oldValue,
      Optional<AgentVersionDiffDiffsItemChangesItemNewValue> newValue,
      Map<String, Object> additionalProperties) {
    this.path = path;
    this.oldValue = oldValue;
    this.newValue = newValue;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Path to the changed value within the section.
   */
  @JsonProperty("path")
  public Optional<String> getPath() {
    return path;
  }

  /**
   * @return Previous value. Can be any JSON value or null.
   */
  @JsonIgnore
  public Optional<AgentVersionDiffDiffsItemChangesItemOldValue> getOldValue() {
    if (oldValue == null) {
      return Optional.empty();
    }
    return oldValue;
  }

  /**
   * @return New value. Can be any JSON value or null.
   */
  @JsonIgnore
  public Optional<AgentVersionDiffDiffsItemChangesItemNewValue> getNewValue() {
    if (newValue == null) {
      return Optional.empty();
    }
    return newValue;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("oldValue")
  private Optional<AgentVersionDiffDiffsItemChangesItemOldValue> _getOldValue() {
    return oldValue;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("newValue")
  private Optional<AgentVersionDiffDiffsItemChangesItemNewValue> _getNewValue() {
    return newValue;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof AgentVersionDiffDiffsItemChangesItem && equalTo((AgentVersionDiffDiffsItemChangesItem) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(AgentVersionDiffDiffsItemChangesItem other) {
    return path.equals(other.path) && oldValue.equals(other.oldValue) && newValue.equals(other.newValue);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.path, this.oldValue, this.newValue);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<String> path = Optional.empty();

    private Optional<AgentVersionDiffDiffsItemChangesItemOldValue> oldValue = Optional.empty();

    private Optional<AgentVersionDiffDiffsItemChangesItemNewValue> newValue = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(AgentVersionDiffDiffsItemChangesItem other) {
      path(other.getPath());
      oldValue(other.getOldValue());
      newValue(other.getNewValue());
      return this;
    }

    /**
     * <p>Path to the changed value within the section.</p>
     */
    @JsonSetter(
        value = "path",
        nulls = Nulls.SKIP
    )
    public Builder path(Optional<String> path) {
      this.path = path;
      return this;
    }

    public Builder path(String path) {
      this.path = Optional.ofNullable(path);
      return this;
    }

    /**
     * <p>Previous value. Can be any JSON value or null.</p>
     */
    @JsonSetter(
        value = "oldValue",
        nulls = Nulls.SKIP
    )
    public Builder oldValue(Optional<AgentVersionDiffDiffsItemChangesItemOldValue> oldValue) {
      this.oldValue = oldValue;
      return this;
    }

    public Builder oldValue(AgentVersionDiffDiffsItemChangesItemOldValue oldValue) {
      this.oldValue = Optional.ofNullable(oldValue);
      return this;
    }

    public Builder oldValue(Nullable<AgentVersionDiffDiffsItemChangesItemOldValue> oldValue) {
      if (oldValue.isNull()) {
        this.oldValue = null;
      }
      else if (oldValue.isEmpty()) {
        this.oldValue = Optional.empty();
      }
      else {
        this.oldValue = Optional.of(oldValue.get());
      }
      return this;
    }

    /**
     * <p>New value. Can be any JSON value or null.</p>
     */
    @JsonSetter(
        value = "newValue",
        nulls = Nulls.SKIP
    )
    public Builder newValue(Optional<AgentVersionDiffDiffsItemChangesItemNewValue> newValue) {
      this.newValue = newValue;
      return this;
    }

    public Builder newValue(AgentVersionDiffDiffsItemChangesItemNewValue newValue) {
      this.newValue = Optional.ofNullable(newValue);
      return this;
    }

    public Builder newValue(Nullable<AgentVersionDiffDiffsItemChangesItemNewValue> newValue) {
      if (newValue.isNull()) {
        this.newValue = null;
      }
      else if (newValue.isEmpty()) {
        this.newValue = Optional.empty();
      }
      else {
        this.newValue = Optional.of(newValue.get());
      }
      return this;
    }

    public AgentVersionDiffDiffsItemChangesItem build() {
      return new AgentVersionDiffDiffsItemChangesItem(path, oldValue, newValue, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
