/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.smallest.resources.atoms.types;

import ai.smallest.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = AgentDtoVersionedWorkflow.Builder.class
)
public final class AgentDtoVersionedWorkflow {
  private final Optional<String> prompt;

  private final Optional<List<Tool>> tools;

  private final Optional<Map<String, Object>> workflowGraph;

  private final Map<String, Object> additionalProperties;

  private AgentDtoVersionedWorkflow(Optional<String> prompt, Optional<List<Tool>> tools,
      Optional<Map<String, Object>> workflowGraph, Map<String, Object> additionalProperties) {
    this.prompt = prompt;
    this.tools = tools;
    this.workflowGraph = workflowGraph;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("prompt")
  public Optional<String> getPrompt() {
    return prompt;
  }

  @JsonProperty("tools")
  public Optional<List<Tool>> getTools() {
    return tools;
  }

  @JsonProperty("workflowGraph")
  public Optional<Map<String, Object>> getWorkflowGraph() {
    return workflowGraph;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof AgentDtoVersionedWorkflow && equalTo((AgentDtoVersionedWorkflow) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(AgentDtoVersionedWorkflow other) {
    return prompt.equals(other.prompt) && tools.equals(other.tools) && workflowGraph.equals(other.workflowGraph);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.prompt, this.tools, this.workflowGraph);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<String> prompt = Optional.empty();

    private Optional<List<Tool>> tools = Optional.empty();

    private Optional<Map<String, Object>> workflowGraph = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(AgentDtoVersionedWorkflow other) {
      prompt(other.getPrompt());
      tools(other.getTools());
      workflowGraph(other.getWorkflowGraph());
      return this;
    }

    @JsonSetter(
        value = "prompt",
        nulls = Nulls.SKIP
    )
    public Builder prompt(Optional<String> prompt) {
      this.prompt = prompt;
      return this;
    }

    public Builder prompt(String prompt) {
      this.prompt = Optional.ofNullable(prompt);
      return this;
    }

    @JsonSetter(
        value = "tools",
        nulls = Nulls.SKIP
    )
    public Builder tools(Optional<List<Tool>> tools) {
      this.tools = tools;
      return this;
    }

    public Builder tools(List<Tool> tools) {
      this.tools = Optional.ofNullable(tools);
      return this;
    }

    @JsonSetter(
        value = "workflowGraph",
        nulls = Nulls.SKIP
    )
    public Builder workflowGraph(Optional<Map<String, Object>> workflowGraph) {
      this.workflowGraph = workflowGraph;
      return this;
    }

    public Builder workflowGraph(Map<String, Object> workflowGraph) {
      this.workflowGraph = Optional.ofNullable(workflowGraph);
      return this;
    }

    public AgentDtoVersionedWorkflow build() {
      return new AgentDtoVersionedWorkflow(prompt, tools, workflowGraph, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
