/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.smallest.resources.atoms.types;

import ai.smallest.core.Nullable;
import ai.smallest.core.NullableNonemptyFilter;
import ai.smallest.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = DraftEditHistoryEntry.Builder.class
)
public final class DraftEditHistoryEntry {
  private final Optional<Integer> revision;

  private final Optional<List<String>> changedSections;

  private final Optional<String> editorName;

  private final Optional<String> editorId;

  private final Optional<OffsetDateTime> timestamp;

  private final Map<String, Object> additionalProperties;

  private DraftEditHistoryEntry(Optional<Integer> revision, Optional<List<String>> changedSections,
      Optional<String> editorName, Optional<String> editorId, Optional<OffsetDateTime> timestamp,
      Map<String, Object> additionalProperties) {
    this.revision = revision;
    this.changedSections = changedSections;
    this.editorName = editorName;
    this.editorId = editorId;
    this.timestamp = timestamp;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Draft revision number
   */
  @JsonProperty("revision")
  public Optional<Integer> getRevision() {
    return revision;
  }

  /**
   * @return List of config sections that changed in this revision
   */
  @JsonProperty("changedSections")
  public Optional<List<String>> getChangedSections() {
    return changedSections;
  }

  /**
   * @return Display name of the editor
   */
  @JsonIgnore
  public Optional<String> getEditorName() {
    if (editorName == null) {
      return Optional.empty();
    }
    return editorName;
  }

  /**
   * @return User ID of the editor
   */
  @JsonIgnore
  public Optional<String> getEditorId() {
    if (editorId == null) {
      return Optional.empty();
    }
    return editorId;
  }

  /**
   * @return When the edit was made
   */
  @JsonProperty("timestamp")
  public Optional<OffsetDateTime> getTimestamp() {
    return timestamp;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("editorName")
  private Optional<String> _getEditorName() {
    return editorName;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("editorId")
  private Optional<String> _getEditorId() {
    return editorId;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof DraftEditHistoryEntry && equalTo((DraftEditHistoryEntry) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(DraftEditHistoryEntry other) {
    return revision.equals(other.revision) && changedSections.equals(other.changedSections) && editorName.equals(other.editorName) && editorId.equals(other.editorId) && timestamp.equals(other.timestamp);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.revision, this.changedSections, this.editorName, this.editorId, this.timestamp);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<Integer> revision = Optional.empty();

    private Optional<List<String>> changedSections = Optional.empty();

    private Optional<String> editorName = Optional.empty();

    private Optional<String> editorId = Optional.empty();

    private Optional<OffsetDateTime> timestamp = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(DraftEditHistoryEntry other) {
      revision(other.getRevision());
      changedSections(other.getChangedSections());
      editorName(other.getEditorName());
      editorId(other.getEditorId());
      timestamp(other.getTimestamp());
      return this;
    }

    /**
     * <p>Draft revision number</p>
     */
    @JsonSetter(
        value = "revision",
        nulls = Nulls.SKIP
    )
    public Builder revision(Optional<Integer> revision) {
      this.revision = revision;
      return this;
    }

    public Builder revision(Integer revision) {
      this.revision = Optional.ofNullable(revision);
      return this;
    }

    /**
     * <p>List of config sections that changed in this revision</p>
     */
    @JsonSetter(
        value = "changedSections",
        nulls = Nulls.SKIP
    )
    public Builder changedSections(Optional<List<String>> changedSections) {
      this.changedSections = changedSections;
      return this;
    }

    public Builder changedSections(List<String> changedSections) {
      this.changedSections = Optional.ofNullable(changedSections);
      return this;
    }

    /**
     * <p>Display name of the editor</p>
     */
    @JsonSetter(
        value = "editorName",
        nulls = Nulls.SKIP
    )
    public Builder editorName(Optional<String> editorName) {
      this.editorName = editorName;
      return this;
    }

    public Builder editorName(String editorName) {
      this.editorName = Optional.ofNullable(editorName);
      return this;
    }

    public Builder editorName(Nullable<String> editorName) {
      if (editorName.isNull()) {
        this.editorName = null;
      }
      else if (editorName.isEmpty()) {
        this.editorName = Optional.empty();
      }
      else {
        this.editorName = Optional.of(editorName.get());
      }
      return this;
    }

    /**
     * <p>User ID of the editor</p>
     */
    @JsonSetter(
        value = "editorId",
        nulls = Nulls.SKIP
    )
    public Builder editorId(Optional<String> editorId) {
      this.editorId = editorId;
      return this;
    }

    public Builder editorId(String editorId) {
      this.editorId = Optional.ofNullable(editorId);
      return this;
    }

    public Builder editorId(Nullable<String> editorId) {
      if (editorId.isNull()) {
        this.editorId = null;
      }
      else if (editorId.isEmpty()) {
        this.editorId = Optional.empty();
      }
      else {
        this.editorId = Optional.of(editorId.get());
      }
      return this;
    }

    /**
     * <p>When the edit was made</p>
     */
    @JsonSetter(
        value = "timestamp",
        nulls = Nulls.SKIP
    )
    public Builder timestamp(Optional<OffsetDateTime> timestamp) {
      this.timestamp = timestamp;
      return this;
    }

    public Builder timestamp(OffsetDateTime timestamp) {
      this.timestamp = Optional.ofNullable(timestamp);
      return this;
    }

    public DraftEditHistoryEntry build() {
      return new DraftEditHistoryEntry(revision, changedSections, editorName, editorId, timestamp, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
