/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.smallest.resources.atoms.types;

import ai.smallest.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = KnowledgeBase.Builder.class
)
public final class KnowledgeBase {
  private final String id;

  private final String name;

  private final Optional<String> description;

  private final String organization;

  private final String createdBy;

  private final Optional<KnowledgeBaseProcessingStatus> processingStatus;

  private final Optional<OffsetDateTime> createdAt;

  private final Optional<OffsetDateTime> updatedAt;

  private final Map<String, Object> additionalProperties;

  private KnowledgeBase(String id, String name, Optional<String> description, String organization,
      String createdBy, Optional<KnowledgeBaseProcessingStatus> processingStatus,
      Optional<OffsetDateTime> createdAt, Optional<OffsetDateTime> updatedAt,
      Map<String, Object> additionalProperties) {
    this.id = id;
    this.name = name;
    this.description = description;
    this.organization = organization;
    this.createdBy = createdBy;
    this.processingStatus = processingStatus;
    this.createdAt = createdAt;
    this.updatedAt = updatedAt;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return The unique identifier for the knowledge base
   */
  @JsonProperty("_id")
  public String getId() {
    return id;
  }

  /**
   * @return The name of the knowledge base
   */
  @JsonProperty("name")
  public String getName() {
    return name;
  }

  /**
   * @return The description of the knowledge base
   */
  @JsonProperty("description")
  public Optional<String> getDescription() {
    return description;
  }

  /**
   * @return The organization ID
   */
  @JsonProperty("organization")
  public String getOrganization() {
    return organization;
  }

  /**
   * @return The user ID who created the knowledge base
   */
  @JsonProperty("createdBy")
  public String getCreatedBy() {
    return createdBy;
  }

  /**
   * @return The current processing status of the knowledge base
   */
  @JsonProperty("processingStatus")
  public Optional<KnowledgeBaseProcessingStatus> getProcessingStatus() {
    return processingStatus;
  }

  /**
   * @return The date and time when the knowledge base was created
   */
  @JsonProperty("createdAt")
  public Optional<OffsetDateTime> getCreatedAt() {
    return createdAt;
  }

  /**
   * @return The date and time when the knowledge base was last updated
   */
  @JsonProperty("updatedAt")
  public Optional<OffsetDateTime> getUpdatedAt() {
    return updatedAt;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof KnowledgeBase && equalTo((KnowledgeBase) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(KnowledgeBase other) {
    return id.equals(other.id) && name.equals(other.name) && description.equals(other.description) && organization.equals(other.organization) && createdBy.equals(other.createdBy) && processingStatus.equals(other.processingStatus) && createdAt.equals(other.createdAt) && updatedAt.equals(other.updatedAt);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.id, this.name, this.description, this.organization, this.createdBy, this.processingStatus, this.createdAt, this.updatedAt);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static IdStage builder() {
    return new Builder();
  }

  public interface IdStage {
    /**
     * <p>The unique identifier for the knowledge base</p>
     */
    NameStage id(@NotNull String id);

    Builder from(KnowledgeBase other);
  }

  public interface NameStage {
    /**
     * <p>The name of the knowledge base</p>
     */
    OrganizationStage name(@NotNull String name);
  }

  public interface OrganizationStage {
    /**
     * <p>The organization ID</p>
     */
    CreatedByStage organization(@NotNull String organization);
  }

  public interface CreatedByStage {
    /**
     * <p>The user ID who created the knowledge base</p>
     */
    _FinalStage createdBy(@NotNull String createdBy);
  }

  public interface _FinalStage {
    KnowledgeBase build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /**
     * <p>The description of the knowledge base</p>
     */
    _FinalStage description(Optional<String> description);

    _FinalStage description(String description);

    /**
     * <p>The current processing status of the knowledge base</p>
     */
    _FinalStage processingStatus(Optional<KnowledgeBaseProcessingStatus> processingStatus);

    _FinalStage processingStatus(KnowledgeBaseProcessingStatus processingStatus);

    /**
     * <p>The date and time when the knowledge base was created</p>
     */
    _FinalStage createdAt(Optional<OffsetDateTime> createdAt);

    _FinalStage createdAt(OffsetDateTime createdAt);

    /**
     * <p>The date and time when the knowledge base was last updated</p>
     */
    _FinalStage updatedAt(Optional<OffsetDateTime> updatedAt);

    _FinalStage updatedAt(OffsetDateTime updatedAt);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements IdStage, NameStage, OrganizationStage, CreatedByStage, _FinalStage {
    private String id;

    private String name;

    private String organization;

    private String createdBy;

    private Optional<OffsetDateTime> updatedAt = Optional.empty();

    private Optional<OffsetDateTime> createdAt = Optional.empty();

    private Optional<KnowledgeBaseProcessingStatus> processingStatus = Optional.empty();

    private Optional<String> description = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(KnowledgeBase other) {
      id(other.getId());
      name(other.getName());
      description(other.getDescription());
      organization(other.getOrganization());
      createdBy(other.getCreatedBy());
      processingStatus(other.getProcessingStatus());
      createdAt(other.getCreatedAt());
      updatedAt(other.getUpdatedAt());
      return this;
    }

    /**
     * <p>The unique identifier for the knowledge base</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("_id")
    public NameStage id(@NotNull String id) {
      this.id = Objects.requireNonNull(id, "id must not be null");
      return this;
    }

    /**
     * <p>The name of the knowledge base</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("name")
    public OrganizationStage name(@NotNull String name) {
      this.name = Objects.requireNonNull(name, "name must not be null");
      return this;
    }

    /**
     * <p>The organization ID</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("organization")
    public CreatedByStage organization(@NotNull String organization) {
      this.organization = Objects.requireNonNull(organization, "organization must not be null");
      return this;
    }

    /**
     * <p>The user ID who created the knowledge base</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("createdBy")
    public _FinalStage createdBy(@NotNull String createdBy) {
      this.createdBy = Objects.requireNonNull(createdBy, "createdBy must not be null");
      return this;
    }

    /**
     * <p>The date and time when the knowledge base was last updated</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage updatedAt(OffsetDateTime updatedAt) {
      this.updatedAt = Optional.ofNullable(updatedAt);
      return this;
    }

    /**
     * <p>The date and time when the knowledge base was last updated</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "updatedAt",
        nulls = Nulls.SKIP
    )
    public _FinalStage updatedAt(Optional<OffsetDateTime> updatedAt) {
      this.updatedAt = updatedAt;
      return this;
    }

    /**
     * <p>The date and time when the knowledge base was created</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage createdAt(OffsetDateTime createdAt) {
      this.createdAt = Optional.ofNullable(createdAt);
      return this;
    }

    /**
     * <p>The date and time when the knowledge base was created</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "createdAt",
        nulls = Nulls.SKIP
    )
    public _FinalStage createdAt(Optional<OffsetDateTime> createdAt) {
      this.createdAt = createdAt;
      return this;
    }

    /**
     * <p>The current processing status of the knowledge base</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage processingStatus(KnowledgeBaseProcessingStatus processingStatus) {
      this.processingStatus = Optional.ofNullable(processingStatus);
      return this;
    }

    /**
     * <p>The current processing status of the knowledge base</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "processingStatus",
        nulls = Nulls.SKIP
    )
    public _FinalStage processingStatus(Optional<KnowledgeBaseProcessingStatus> processingStatus) {
      this.processingStatus = processingStatus;
      return this;
    }

    /**
     * <p>The description of the knowledge base</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage description(String description) {
      this.description = Optional.ofNullable(description);
      return this;
    }

    /**
     * <p>The description of the knowledge base</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "description",
        nulls = Nulls.SKIP
    )
    public _FinalStage description(Optional<String> description) {
      this.description = description;
      return this;
    }

    @java.lang.Override
    public KnowledgeBase build() {
      return new KnowledgeBase(id, name, description, organization, createdBy, processingStatus, createdAt, updatedAt, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
