/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.smallest.resources.atoms.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class PostCallAnalyticsConfigSuccessMetricsItemSuccessMetricType {
  public static final PostCallAnalyticsConfigSuccessMetricsItemSuccessMetricType PERCENTAGE_SCALE = new PostCallAnalyticsConfigSuccessMetricsItemSuccessMetricType(Value.PERCENTAGE_SCALE, "PERCENTAGE_SCALE");

  public static final PostCallAnalyticsConfigSuccessMetricsItemSuccessMetricType NUMERIC_SCALE = new PostCallAnalyticsConfigSuccessMetricsItemSuccessMetricType(Value.NUMERIC_SCALE, "NUMERIC_SCALE");

  public static final PostCallAnalyticsConfigSuccessMetricsItemSuccessMetricType PASS_FAIL = new PostCallAnalyticsConfigSuccessMetricsItemSuccessMetricType(Value.PASS_FAIL, "PASS_FAIL");

  public static final PostCallAnalyticsConfigSuccessMetricsItemSuccessMetricType DESCRIPTIVE_SCALE = new PostCallAnalyticsConfigSuccessMetricsItemSuccessMetricType(Value.DESCRIPTIVE_SCALE, "DESCRIPTIVE_SCALE");

  private final Value value;

  private final String string;

  PostCallAnalyticsConfigSuccessMetricsItemSuccessMetricType(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof PostCallAnalyticsConfigSuccessMetricsItemSuccessMetricType && this.string.equals(((PostCallAnalyticsConfigSuccessMetricsItemSuccessMetricType) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case PERCENTAGE_SCALE:
        return visitor.visitPercentageScale();
      case NUMERIC_SCALE:
        return visitor.visitNumericScale();
      case PASS_FAIL:
        return visitor.visitPassFail();
      case DESCRIPTIVE_SCALE:
        return visitor.visitDescriptiveScale();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static PostCallAnalyticsConfigSuccessMetricsItemSuccessMetricType valueOf(String value) {
    switch (value) {
      case "PERCENTAGE_SCALE":
        return PERCENTAGE_SCALE;
      case "NUMERIC_SCALE":
        return NUMERIC_SCALE;
      case "PASS_FAIL":
        return PASS_FAIL;
      case "DESCRIPTIVE_SCALE":
        return DESCRIPTIVE_SCALE;
      default:
        return new PostCallAnalyticsConfigSuccessMetricsItemSuccessMetricType(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    NUMERIC_SCALE,

    PERCENTAGE_SCALE,

    PASS_FAIL,

    DESCRIPTIVE_SCALE,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitNumericScale();

    T visitPercentageScale();

    T visitPassFail();

    T visitDescriptiveScale();

    T visitUnknown(String unknownType);
  }
}
