/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.smallest.resources.atoms.types;

import ai.smallest.core.Nullable;
import ai.smallest.core.NullableNonemptyFilter;
import ai.smallest.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Boolean;
import java.lang.Object;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = Product.Builder.class
)
public final class Product {
  private final Optional<String> id;

  private final Optional<ProductProductType> productType;

  private final Optional<Boolean> isActive;

  private final Optional<ProductAttributes> attributes;

  private final Optional<String> agentId;

  private final Optional<OffsetDateTime> createdAt;

  private final Optional<OffsetDateTime> updatedAt;

  private final Map<String, Object> additionalProperties;

  private Product(Optional<String> id, Optional<ProductProductType> productType,
      Optional<Boolean> isActive, Optional<ProductAttributes> attributes, Optional<String> agentId,
      Optional<OffsetDateTime> createdAt, Optional<OffsetDateTime> updatedAt,
      Map<String, Object> additionalProperties) {
    this.id = id;
    this.productType = productType;
    this.isActive = isActive;
    this.attributes = attributes;
    this.agentId = agentId;
    this.createdAt = createdAt;
    this.updatedAt = updatedAt;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return 24-char MongoDB ObjectId. Use this as <code>productId</code> when releasing, or assign to an agent via <code>PATCH /agent/{agentId}</code>.
   */
  @JsonProperty("_id")
  public Optional<String> getId() {
    return id;
  }

  /**
   * @return <ul>
   * <li><code>telephony</code> — number rented via the Atoms platform (Plivo/Twilio).</li>
   * <li><code>custom-telephony</code> — number imported via <code>POST /product/import-phone-number</code> with the customer's own SIP trunk.</li>
   * </ul>
   */
  @JsonProperty("productType")
  public Optional<ProductProductType> getProductType() {
    return productType;
  }

  /**
   * @return Whether the number is currently billable / serving traffic.
   */
  @JsonProperty("isActive")
  public Optional<Boolean> getIsActive() {
    return isActive;
  }

  /**
   * @return Provider-specific number metadata.
   */
  @JsonProperty("attributes")
  public Optional<ProductAttributes> getAttributes() {
    return attributes;
  }

  /**
   * @return 24-char MongoDB ObjectId of the agent this number is assigned to, if any. <code>null</code> when unassigned.
   */
  @JsonIgnore
  public Optional<String> getAgentId() {
    if (agentId == null) {
      return Optional.empty();
    }
    return agentId;
  }

  @JsonProperty("createdAt")
  public Optional<OffsetDateTime> getCreatedAt() {
    return createdAt;
  }

  @JsonProperty("updatedAt")
  public Optional<OffsetDateTime> getUpdatedAt() {
    return updatedAt;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("agentId")
  private Optional<String> _getAgentId() {
    return agentId;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof Product && equalTo((Product) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(Product other) {
    return id.equals(other.id) && productType.equals(other.productType) && isActive.equals(other.isActive) && attributes.equals(other.attributes) && agentId.equals(other.agentId) && createdAt.equals(other.createdAt) && updatedAt.equals(other.updatedAt);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.id, this.productType, this.isActive, this.attributes, this.agentId, this.createdAt, this.updatedAt);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<String> id = Optional.empty();

    private Optional<ProductProductType> productType = Optional.empty();

    private Optional<Boolean> isActive = Optional.empty();

    private Optional<ProductAttributes> attributes = Optional.empty();

    private Optional<String> agentId = Optional.empty();

    private Optional<OffsetDateTime> createdAt = Optional.empty();

    private Optional<OffsetDateTime> updatedAt = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(Product other) {
      id(other.getId());
      productType(other.getProductType());
      isActive(other.getIsActive());
      attributes(other.getAttributes());
      agentId(other.getAgentId());
      createdAt(other.getCreatedAt());
      updatedAt(other.getUpdatedAt());
      return this;
    }

    /**
     * <p>24-char MongoDB ObjectId. Use this as <code>productId</code> when releasing, or assign to an agent via <code>PATCH /agent/{agentId}</code>.</p>
     */
    @JsonSetter(
        value = "_id",
        nulls = Nulls.SKIP
    )
    public Builder id(Optional<String> id) {
      this.id = id;
      return this;
    }

    public Builder id(String id) {
      this.id = Optional.ofNullable(id);
      return this;
    }

    /**
     * <ul>
     * <li><code>telephony</code> — number rented via the Atoms platform (Plivo/Twilio).</li>
     * <li><code>custom-telephony</code> — number imported via <code>POST /product/import-phone-number</code> with the customer's own SIP trunk.</li>
     * </ul>
     */
    @JsonSetter(
        value = "productType",
        nulls = Nulls.SKIP
    )
    public Builder productType(Optional<ProductProductType> productType) {
      this.productType = productType;
      return this;
    }

    public Builder productType(ProductProductType productType) {
      this.productType = Optional.ofNullable(productType);
      return this;
    }

    /**
     * <p>Whether the number is currently billable / serving traffic.</p>
     */
    @JsonSetter(
        value = "isActive",
        nulls = Nulls.SKIP
    )
    public Builder isActive(Optional<Boolean> isActive) {
      this.isActive = isActive;
      return this;
    }

    public Builder isActive(Boolean isActive) {
      this.isActive = Optional.ofNullable(isActive);
      return this;
    }

    /**
     * <p>Provider-specific number metadata.</p>
     */
    @JsonSetter(
        value = "attributes",
        nulls = Nulls.SKIP
    )
    public Builder attributes(Optional<ProductAttributes> attributes) {
      this.attributes = attributes;
      return this;
    }

    public Builder attributes(ProductAttributes attributes) {
      this.attributes = Optional.ofNullable(attributes);
      return this;
    }

    /**
     * <p>24-char MongoDB ObjectId of the agent this number is assigned to, if any. <code>null</code> when unassigned.</p>
     */
    @JsonSetter(
        value = "agentId",
        nulls = Nulls.SKIP
    )
    public Builder agentId(Optional<String> agentId) {
      this.agentId = agentId;
      return this;
    }

    public Builder agentId(String agentId) {
      this.agentId = Optional.ofNullable(agentId);
      return this;
    }

    public Builder agentId(Nullable<String> agentId) {
      if (agentId.isNull()) {
        this.agentId = null;
      }
      else if (agentId.isEmpty()) {
        this.agentId = Optional.empty();
      }
      else {
        this.agentId = Optional.of(agentId.get());
      }
      return this;
    }

    @JsonSetter(
        value = "createdAt",
        nulls = Nulls.SKIP
    )
    public Builder createdAt(Optional<OffsetDateTime> createdAt) {
      this.createdAt = createdAt;
      return this;
    }

    public Builder createdAt(OffsetDateTime createdAt) {
      this.createdAt = Optional.ofNullable(createdAt);
      return this;
    }

    @JsonSetter(
        value = "updatedAt",
        nulls = Nulls.SKIP
    )
    public Builder updatedAt(Optional<OffsetDateTime> updatedAt) {
      this.updatedAt = updatedAt;
      return this;
    }

    public Builder updatedAt(OffsetDateTime updatedAt) {
      this.updatedAt = Optional.ofNullable(updatedAt);
      return this;
    }

    public Product build() {
      return new Product(id, productType, isActive, attributes, agentId, createdAt, updatedAt, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
