/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.smallest.resources.atoms.types;

import ai.smallest.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = SinglePromptConfig.Builder.class
)
public final class SinglePromptConfig {
  private final String prompt;

  private final Optional<List<Tool>> tools;

  private final Map<String, Object> additionalProperties;

  private SinglePromptConfig(String prompt, Optional<List<Tool>> tools,
      Map<String, Object> additionalProperties) {
    this.prompt = prompt;
    this.tools = tools;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return The main prompt that defines the agent's behavior and responses
   */
  @JsonProperty("prompt")
  public String getPrompt() {
    return prompt;
  }

  /**
   * @return Array of tools/functions available to the agent during conversations.
   * Five tool types are supported: <code>end_call</code>, <code>transfer_call</code>, <code>api_call</code>,
   * <code>extract_dynamic_variables</code>, and <code>knowledge_base_search</code>. Each type has its
   * own required fields — see <code>Tool</code> schema.
   */
  @JsonProperty("tools")
  public Optional<List<Tool>> getTools() {
    return tools;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof SinglePromptConfig && equalTo((SinglePromptConfig) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(SinglePromptConfig other) {
    return prompt.equals(other.prompt) && tools.equals(other.tools);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.prompt, this.tools);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static PromptStage builder() {
    return new Builder();
  }

  public interface PromptStage {
    /**
     * <p>The main prompt that defines the agent's behavior and responses</p>
     */
    _FinalStage prompt(@NotNull String prompt);

    Builder from(SinglePromptConfig other);
  }

  public interface _FinalStage {
    SinglePromptConfig build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /**
     * <p>Array of tools/functions available to the agent during conversations.
     * Five tool types are supported: <code>end_call</code>, <code>transfer_call</code>, <code>api_call</code>,
     * <code>extract_dynamic_variables</code>, and <code>knowledge_base_search</code>. Each type has its
     * own required fields — see <code>Tool</code> schema.</p>
     */
    _FinalStage tools(Optional<List<Tool>> tools);

    _FinalStage tools(List<Tool> tools);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements PromptStage, _FinalStage {
    private String prompt;

    private Optional<List<Tool>> tools = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(SinglePromptConfig other) {
      prompt(other.getPrompt());
      tools(other.getTools());
      return this;
    }

    /**
     * <p>The main prompt that defines the agent's behavior and responses</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("prompt")
    public _FinalStage prompt(@NotNull String prompt) {
      this.prompt = Objects.requireNonNull(prompt, "prompt must not be null");
      return this;
    }

    /**
     * <p>Array of tools/functions available to the agent during conversations.
     * Five tool types are supported: <code>end_call</code>, <code>transfer_call</code>, <code>api_call</code>,
     * <code>extract_dynamic_variables</code>, and <code>knowledge_base_search</code>. Each type has its
     * own required fields — see <code>Tool</code> schema.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage tools(List<Tool> tools) {
      this.tools = Optional.ofNullable(tools);
      return this;
    }

    /**
     * <p>Array of tools/functions available to the agent during conversations.
     * Five tool types are supported: <code>end_call</code>, <code>transfer_call</code>, <code>api_call</code>,
     * <code>extract_dynamic_variables</code>, and <code>knowledge_base_search</code>. Each type has its
     * own required fields — see <code>Tool</code> schema.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "tools",
        nulls = Nulls.SKIP
    )
    public _FinalStage tools(Optional<List<Tool>> tools) {
      this.tools = tools;
      return this;
    }

    @java.lang.Override
    public SinglePromptConfig build() {
      return new SinglePromptConfig(prompt, tools, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
