/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.smallest.resources.atoms.types;

import ai.smallest.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = ToolTransferOptionPublicHandoffOption.Builder.class
)
public final class ToolTransferOptionPublicHandoffOption {
  private final Optional<ToolTransferOptionPublicHandoffOptionType> type;

  private final Optional<String> prompt;

  private final Map<String, Object> additionalProperties;

  private ToolTransferOptionPublicHandoffOption(
      Optional<ToolTransferOptionPublicHandoffOptionType> type, Optional<String> prompt,
      Map<String, Object> additionalProperties) {
    this.type = type;
    this.prompt = prompt;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("type")
  public Optional<ToolTransferOptionPublicHandoffOptionType> getType() {
    return type;
  }

  @JsonProperty("prompt")
  public Optional<String> getPrompt() {
    return prompt;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof ToolTransferOptionPublicHandoffOption && equalTo((ToolTransferOptionPublicHandoffOption) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(ToolTransferOptionPublicHandoffOption other) {
    return type.equals(other.type) && prompt.equals(other.prompt);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.type, this.prompt);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<ToolTransferOptionPublicHandoffOptionType> type = Optional.empty();

    private Optional<String> prompt = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(ToolTransferOptionPublicHandoffOption other) {
      type(other.getType());
      prompt(other.getPrompt());
      return this;
    }

    @JsonSetter(
        value = "type",
        nulls = Nulls.SKIP
    )
    public Builder type(Optional<ToolTransferOptionPublicHandoffOptionType> type) {
      this.type = type;
      return this;
    }

    public Builder type(ToolTransferOptionPublicHandoffOptionType type) {
      this.type = Optional.ofNullable(type);
      return this;
    }

    @JsonSetter(
        value = "prompt",
        nulls = Nulls.SKIP
    )
    public Builder prompt(Optional<String> prompt) {
      this.prompt = prompt;
      return this;
    }

    public Builder prompt(String prompt) {
      this.prompt = Optional.ofNullable(prompt);
      return this;
    }

    public ToolTransferOptionPublicHandoffOption build() {
      return new ToolTransferOptionPublicHandoffOption(type, prompt, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
