/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.smallest.resources.atoms.types;

import ai.smallest.core.Nullable;
import ai.smallest.core.NullableNonemptyFilter;
import ai.smallest.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = ToolTransferOption.Builder.class
)
public final class ToolTransferOption {
  private final Optional<ToolTransferOptionType> type;

  private final Optional<ToolTransferOptionPrivateHandoffOption> privateHandoffOption;

  private final Optional<ToolTransferOptionPublicHandoffOption> publicHandoffOption;

  private final Map<String, Object> additionalProperties;

  private ToolTransferOption(Optional<ToolTransferOptionType> type,
      Optional<ToolTransferOptionPrivateHandoffOption> privateHandoffOption,
      Optional<ToolTransferOptionPublicHandoffOption> publicHandoffOption,
      Map<String, Object> additionalProperties) {
    this.type = type;
    this.privateHandoffOption = privateHandoffOption;
    this.publicHandoffOption = publicHandoffOption;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Transfer mode. <code>cold_transfer</code> hands off immediately; <code>warm_transfer</code> briefs the receiving party first.
   */
  @JsonProperty("type")
  public Optional<ToolTransferOptionType> getType() {
    return type;
  }

  /**
   * @return Private briefing delivered to the transfer target before the caller is connected. Only used when <code>type = warm_transfer</code>.
   */
  @JsonIgnore
  public Optional<ToolTransferOptionPrivateHandoffOption> getPrivateHandoffOption() {
    if (privateHandoffOption == null) {
      return Optional.empty();
    }
    return privateHandoffOption;
  }

  /**
   * @return Message played to the caller while the transfer is being set up. Only used when <code>type = warm_transfer</code>.
   */
  @JsonIgnore
  public Optional<ToolTransferOptionPublicHandoffOption> getPublicHandoffOption() {
    if (publicHandoffOption == null) {
      return Optional.empty();
    }
    return publicHandoffOption;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("privateHandoffOption")
  private Optional<ToolTransferOptionPrivateHandoffOption> _getPrivateHandoffOption() {
    return privateHandoffOption;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("publicHandoffOption")
  private Optional<ToolTransferOptionPublicHandoffOption> _getPublicHandoffOption() {
    return publicHandoffOption;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof ToolTransferOption && equalTo((ToolTransferOption) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(ToolTransferOption other) {
    return type.equals(other.type) && privateHandoffOption.equals(other.privateHandoffOption) && publicHandoffOption.equals(other.publicHandoffOption);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.type, this.privateHandoffOption, this.publicHandoffOption);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<ToolTransferOptionType> type = Optional.empty();

    private Optional<ToolTransferOptionPrivateHandoffOption> privateHandoffOption = Optional.empty();

    private Optional<ToolTransferOptionPublicHandoffOption> publicHandoffOption = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(ToolTransferOption other) {
      type(other.getType());
      privateHandoffOption(other.getPrivateHandoffOption());
      publicHandoffOption(other.getPublicHandoffOption());
      return this;
    }

    /**
     * <p>Transfer mode. <code>cold_transfer</code> hands off immediately; <code>warm_transfer</code> briefs the receiving party first.</p>
     */
    @JsonSetter(
        value = "type",
        nulls = Nulls.SKIP
    )
    public Builder type(Optional<ToolTransferOptionType> type) {
      this.type = type;
      return this;
    }

    public Builder type(ToolTransferOptionType type) {
      this.type = Optional.ofNullable(type);
      return this;
    }

    /**
     * <p>Private briefing delivered to the transfer target before the caller is connected. Only used when <code>type = warm_transfer</code>.</p>
     */
    @JsonSetter(
        value = "privateHandoffOption",
        nulls = Nulls.SKIP
    )
    public Builder privateHandoffOption(
        Optional<ToolTransferOptionPrivateHandoffOption> privateHandoffOption) {
      this.privateHandoffOption = privateHandoffOption;
      return this;
    }

    public Builder privateHandoffOption(
        ToolTransferOptionPrivateHandoffOption privateHandoffOption) {
      this.privateHandoffOption = Optional.ofNullable(privateHandoffOption);
      return this;
    }

    public Builder privateHandoffOption(
        Nullable<ToolTransferOptionPrivateHandoffOption> privateHandoffOption) {
      if (privateHandoffOption.isNull()) {
        this.privateHandoffOption = null;
      }
      else if (privateHandoffOption.isEmpty()) {
        this.privateHandoffOption = Optional.empty();
      }
      else {
        this.privateHandoffOption = Optional.of(privateHandoffOption.get());
      }
      return this;
    }

    /**
     * <p>Message played to the caller while the transfer is being set up. Only used when <code>type = warm_transfer</code>.</p>
     */
    @JsonSetter(
        value = "publicHandoffOption",
        nulls = Nulls.SKIP
    )
    public Builder publicHandoffOption(
        Optional<ToolTransferOptionPublicHandoffOption> publicHandoffOption) {
      this.publicHandoffOption = publicHandoffOption;
      return this;
    }

    public Builder publicHandoffOption(ToolTransferOptionPublicHandoffOption publicHandoffOption) {
      this.publicHandoffOption = Optional.ofNullable(publicHandoffOption);
      return this;
    }

    public Builder publicHandoffOption(
        Nullable<ToolTransferOptionPublicHandoffOption> publicHandoffOption) {
      if (publicHandoffOption.isNull()) {
        this.publicHandoffOption = null;
      }
      else if (publicHandoffOption.isEmpty()) {
        this.publicHandoffOption = Optional.empty();
      }
      else {
        this.publicHandoffOption = Optional.of(publicHandoffOption.get());
      }
      return this;
    }

    public ToolTransferOption build() {
      return new ToolTransferOption(type, privateHandoffOption, publicHandoffOption, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
