/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.smallest.resources.atoms.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class ToolOnHoldMusic {
  public static final ToolOnHoldMusic RINGTONE = new ToolOnHoldMusic(Value.RINGTONE, "ringtone");

  public static final ToolOnHoldMusic UPLIFTING_BEATS = new ToolOnHoldMusic(Value.UPLIFTING_BEATS, "uplifting_beats");

  public static final ToolOnHoldMusic RELAXING_SOUND = new ToolOnHoldMusic(Value.RELAXING_SOUND, "relaxing_sound");

  public static final ToolOnHoldMusic NONE = new ToolOnHoldMusic(Value.NONE, "none");

  private final Value value;

  private final String string;

  ToolOnHoldMusic(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof ToolOnHoldMusic && this.string.equals(((ToolOnHoldMusic) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case RINGTONE:
        return visitor.visitRingtone();
      case UPLIFTING_BEATS:
        return visitor.visitUpliftingBeats();
      case RELAXING_SOUND:
        return visitor.visitRelaxingSound();
      case NONE:
        return visitor.visitNone();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static ToolOnHoldMusic valueOf(String value) {
    switch (value) {
      case "ringtone":
        return RINGTONE;
      case "uplifting_beats":
        return UPLIFTING_BEATS;
      case "relaxing_sound":
        return RELAXING_SOUND;
      case "none":
        return NONE;
      default:
        return new ToolOnHoldMusic(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    RINGTONE,

    RELAXING_SOUND,

    UPLIFTING_BEATS,

    NONE,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitRingtone();

    T visitRelaxingSound();

    T visitUpliftingBeats();

    T visitNone();

    T visitUnknown(String unknownType);
  }
}
