/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.smallest.resources.atoms.types;

import ai.smallest.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = WebEngageIntegrationSet.Builder.class
)
public final class WebEngageIntegrationSet {
  private final String licenseCode;

  private final String environment;

  private final String apiKey;

  private final Map<String, Object> additionalProperties;

  private WebEngageIntegrationSet(String licenseCode, String environment, String apiKey,
      Map<String, Object> additionalProperties) {
    this.licenseCode = licenseCode;
    this.environment = environment;
    this.apiKey = apiKey;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return WebEngage license code
   */
  @JsonProperty("licenseCode")
  public String getLicenseCode() {
    return licenseCode;
  }

  /**
   * @return WebEngage environment identifier
   */
  @JsonProperty("environment")
  public String getEnvironment() {
    return environment;
  }

  /**
   * @return WebEngage API key
   */
  @JsonProperty("apiKey")
  public String getApiKey() {
    return apiKey;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof WebEngageIntegrationSet && equalTo((WebEngageIntegrationSet) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(WebEngageIntegrationSet other) {
    return licenseCode.equals(other.licenseCode) && environment.equals(other.environment) && apiKey.equals(other.apiKey);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.licenseCode, this.environment, this.apiKey);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static LicenseCodeStage builder() {
    return new Builder();
  }

  public interface LicenseCodeStage {
    /**
     * <p>WebEngage license code</p>
     */
    EnvironmentStage licenseCode(@NotNull String licenseCode);

    Builder from(WebEngageIntegrationSet other);
  }

  public interface EnvironmentStage {
    /**
     * <p>WebEngage environment identifier</p>
     */
    ApiKeyStage environment(@NotNull String environment);
  }

  public interface ApiKeyStage {
    /**
     * <p>WebEngage API key</p>
     */
    _FinalStage apiKey(@NotNull String apiKey);
  }

  public interface _FinalStage {
    WebEngageIntegrationSet build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements LicenseCodeStage, EnvironmentStage, ApiKeyStage, _FinalStage {
    private String licenseCode;

    private String environment;

    private String apiKey;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(WebEngageIntegrationSet other) {
      licenseCode(other.getLicenseCode());
      environment(other.getEnvironment());
      apiKey(other.getApiKey());
      return this;
    }

    /**
     * <p>WebEngage license code</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("licenseCode")
    public EnvironmentStage licenseCode(@NotNull String licenseCode) {
      this.licenseCode = Objects.requireNonNull(licenseCode, "licenseCode must not be null");
      return this;
    }

    /**
     * <p>WebEngage environment identifier</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("environment")
    public ApiKeyStage environment(@NotNull String environment) {
      this.environment = Objects.requireNonNull(environment, "environment must not be null");
      return this;
    }

    /**
     * <p>WebEngage API key</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("apiKey")
    public _FinalStage apiKey(@NotNull String apiKey) {
      this.apiKey = Objects.requireNonNull(apiKey, "apiKey must not be null");
      return this;
    }

    @java.lang.Override
    public WebEngageIntegrationSet build() {
      return new WebEngageIntegrationSet(licenseCode, environment, apiKey, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
