/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.smallest.resources.atoms.types;

import ai.smallest.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = WebhookEventAnalyticsCompletedMetadata.Builder.class
)
public final class WebhookEventAnalyticsCompletedMetadata {
  private final String agentId;

  private final WebhookEventAnalyticsCompletedMetadataEventType eventType;

  private final String conversationType;

  private final String callId;

  private final WebhookEventAnalyticsCompletedMetadataAnalytics analytics;

  private final WebhookEventCallData callData;

  private final Map<String, Object> additionalProperties;

  private WebhookEventAnalyticsCompletedMetadata(String agentId,
      WebhookEventAnalyticsCompletedMetadataEventType eventType, String conversationType,
      String callId, WebhookEventAnalyticsCompletedMetadataAnalytics analytics,
      WebhookEventCallData callData, Map<String, Object> additionalProperties) {
    this.agentId = agentId;
    this.eventType = eventType;
    this.conversationType = conversationType;
    this.callId = callId;
    this.analytics = analytics;
    this.callData = callData;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("agentId")
  public String getAgentId() {
    return agentId;
  }

  @JsonProperty("eventType")
  public WebhookEventAnalyticsCompletedMetadataEventType getEventType() {
    return eventType;
  }

  @JsonProperty("conversationType")
  public String getConversationType() {
    return conversationType;
  }

  @JsonProperty("callId")
  public String getCallId() {
    return callId;
  }

  @JsonProperty("analytics")
  public WebhookEventAnalyticsCompletedMetadataAnalytics getAnalytics() {
    return analytics;
  }

  @JsonProperty("callData")
  public WebhookEventCallData getCallData() {
    return callData;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof WebhookEventAnalyticsCompletedMetadata && equalTo((WebhookEventAnalyticsCompletedMetadata) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(WebhookEventAnalyticsCompletedMetadata other) {
    return agentId.equals(other.agentId) && eventType.equals(other.eventType) && conversationType.equals(other.conversationType) && callId.equals(other.callId) && analytics.equals(other.analytics) && callData.equals(other.callData);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.agentId, this.eventType, this.conversationType, this.callId, this.analytics, this.callData);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static AgentIdStage builder() {
    return new Builder();
  }

  public interface AgentIdStage {
    EventTypeStage agentId(@NotNull String agentId);

    Builder from(WebhookEventAnalyticsCompletedMetadata other);
  }

  public interface EventTypeStage {
    ConversationTypeStage eventType(
        @NotNull WebhookEventAnalyticsCompletedMetadataEventType eventType);
  }

  public interface ConversationTypeStage {
    CallIdStage conversationType(@NotNull String conversationType);
  }

  public interface CallIdStage {
    AnalyticsStage callId(@NotNull String callId);
  }

  public interface AnalyticsStage {
    CallDataStage analytics(@NotNull WebhookEventAnalyticsCompletedMetadataAnalytics analytics);
  }

  public interface CallDataStage {
    _FinalStage callData(@NotNull WebhookEventCallData callData);
  }

  public interface _FinalStage {
    WebhookEventAnalyticsCompletedMetadata build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements AgentIdStage, EventTypeStage, ConversationTypeStage, CallIdStage, AnalyticsStage, CallDataStage, _FinalStage {
    private String agentId;

    private WebhookEventAnalyticsCompletedMetadataEventType eventType;

    private String conversationType;

    private String callId;

    private WebhookEventAnalyticsCompletedMetadataAnalytics analytics;

    private WebhookEventCallData callData;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(WebhookEventAnalyticsCompletedMetadata other) {
      agentId(other.getAgentId());
      eventType(other.getEventType());
      conversationType(other.getConversationType());
      callId(other.getCallId());
      analytics(other.getAnalytics());
      callData(other.getCallData());
      return this;
    }

    @java.lang.Override
    @JsonSetter("agentId")
    public EventTypeStage agentId(@NotNull String agentId) {
      this.agentId = Objects.requireNonNull(agentId, "agentId must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("eventType")
    public ConversationTypeStage eventType(
        @NotNull WebhookEventAnalyticsCompletedMetadataEventType eventType) {
      this.eventType = Objects.requireNonNull(eventType, "eventType must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("conversationType")
    public CallIdStage conversationType(@NotNull String conversationType) {
      this.conversationType = Objects.requireNonNull(conversationType, "conversationType must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("callId")
    public AnalyticsStage callId(@NotNull String callId) {
      this.callId = Objects.requireNonNull(callId, "callId must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("analytics")
    public CallDataStage analytics(
        @NotNull WebhookEventAnalyticsCompletedMetadataAnalytics analytics) {
      this.analytics = Objects.requireNonNull(analytics, "analytics must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("callData")
    public _FinalStage callData(@NotNull WebhookEventCallData callData) {
      this.callData = Objects.requireNonNull(callData, "callData must not be null");
      return this;
    }

    @java.lang.Override
    public WebhookEventAnalyticsCompletedMetadata build() {
      return new WebhookEventAnalyticsCompletedMetadata(agentId, eventType, conversationType, callId, analytics, callData, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
