/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.smallest.resources.atoms.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class WebhookEventPreConversationMetadataEventType {
  public static final WebhookEventPreConversationMetadataEventType PRE_CONVERSATION = new WebhookEventPreConversationMetadataEventType(Value.PRE_CONVERSATION, "pre-conversation");

  private final Value value;

  private final String string;

  WebhookEventPreConversationMetadataEventType(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof WebhookEventPreConversationMetadataEventType && this.string.equals(((WebhookEventPreConversationMetadataEventType) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case PRE_CONVERSATION:
        return visitor.visitPreConversation();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static WebhookEventPreConversationMetadataEventType valueOf(String value) {
    switch (value) {
      case "pre-conversation":
        return PRE_CONVERSATION;
      default:
        return new WebhookEventPreConversationMetadataEventType(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    PRE_CONVERSATION,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitPreConversation();

    T visitUnknown(String unknownType);
  }
}
