/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.smallest.resources.atoms.agentversioningdrafts.types;

import ai.smallest.core.ObjectMappers;
import ai.smallest.resources.atoms.types.AgentVersion;
import ai.smallest.resources.atoms.types.DraftEditHistoryEntry;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = GetAgentIdDraftsDraftIdResponseData.Builder.class
)
public final class GetAgentIdDraftsDraftIdResponseData {
  private final Optional<AgentVersion> latest;

  private final Optional<List<DraftEditHistoryEntry>> editHistory;

  private final Optional<Integer> editCount;

  private final Map<String, Object> additionalProperties;

  private GetAgentIdDraftsDraftIdResponseData(Optional<AgentVersion> latest,
      Optional<List<DraftEditHistoryEntry>> editHistory, Optional<Integer> editCount,
      Map<String, Object> additionalProperties) {
    this.latest = latest;
    this.editHistory = editHistory;
    this.editCount = editCount;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("latest")
  public Optional<AgentVersion> getLatest() {
    return latest;
  }

  @JsonProperty("editHistory")
  public Optional<List<DraftEditHistoryEntry>> getEditHistory() {
    return editHistory;
  }

  /**
   * @return Total number of edits on this draft
   */
  @JsonProperty("editCount")
  public Optional<Integer> getEditCount() {
    return editCount;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof GetAgentIdDraftsDraftIdResponseData && equalTo((GetAgentIdDraftsDraftIdResponseData) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(GetAgentIdDraftsDraftIdResponseData other) {
    return latest.equals(other.latest) && editHistory.equals(other.editHistory) && editCount.equals(other.editCount);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.latest, this.editHistory, this.editCount);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<AgentVersion> latest = Optional.empty();

    private Optional<List<DraftEditHistoryEntry>> editHistory = Optional.empty();

    private Optional<Integer> editCount = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(GetAgentIdDraftsDraftIdResponseData other) {
      latest(other.getLatest());
      editHistory(other.getEditHistory());
      editCount(other.getEditCount());
      return this;
    }

    @JsonSetter(
        value = "latest",
        nulls = Nulls.SKIP
    )
    public Builder latest(Optional<AgentVersion> latest) {
      this.latest = latest;
      return this;
    }

    public Builder latest(AgentVersion latest) {
      this.latest = Optional.ofNullable(latest);
      return this;
    }

    @JsonSetter(
        value = "editHistory",
        nulls = Nulls.SKIP
    )
    public Builder editHistory(Optional<List<DraftEditHistoryEntry>> editHistory) {
      this.editHistory = editHistory;
      return this;
    }

    public Builder editHistory(List<DraftEditHistoryEntry> editHistory) {
      this.editHistory = Optional.ofNullable(editHistory);
      return this;
    }

    /**
     * <p>Total number of edits on this draft</p>
     */
    @JsonSetter(
        value = "editCount",
        nulls = Nulls.SKIP
    )
    public Builder editCount(Optional<Integer> editCount) {
      this.editCount = editCount;
      return this;
    }

    public Builder editCount(Integer editCount) {
      this.editCount = Optional.ofNullable(editCount);
      return this;
    }

    public GetAgentIdDraftsDraftIdResponseData build() {
      return new GetAgentIdDraftsDraftIdResponseData(latest, editHistory, editCount, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
