/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.smallest.resources.atoms.agentversioningdrafts.types;

import ai.smallest.core.ObjectMappers;
import ai.smallest.resources.atoms.types.AgentVersion;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Boolean;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = PublishDraftAgentVersioningDraftsResponse.Builder.class
)
public final class PublishDraftAgentVersioningDraftsResponse {
  private final Optional<Boolean> status;

  private final Optional<AgentVersion> data;

  private final Map<String, Object> additionalProperties;

  private PublishDraftAgentVersioningDraftsResponse(Optional<Boolean> status,
      Optional<AgentVersion> data, Map<String, Object> additionalProperties) {
    this.status = status;
    this.data = data;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("status")
  public Optional<Boolean> getStatus() {
    return status;
  }

  @JsonProperty("data")
  public Optional<AgentVersion> getData() {
    return data;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof PublishDraftAgentVersioningDraftsResponse && equalTo((PublishDraftAgentVersioningDraftsResponse) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(PublishDraftAgentVersioningDraftsResponse other) {
    return status.equals(other.status) && data.equals(other.data);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.status, this.data);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<Boolean> status = Optional.empty();

    private Optional<AgentVersion> data = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(PublishDraftAgentVersioningDraftsResponse other) {
      status(other.getStatus());
      data(other.getData());
      return this;
    }

    @JsonSetter(
        value = "status",
        nulls = Nulls.SKIP
    )
    public Builder status(Optional<Boolean> status) {
      this.status = status;
      return this;
    }

    public Builder status(Boolean status) {
      this.status = Optional.ofNullable(status);
      return this;
    }

    @JsonSetter(
        value = "data",
        nulls = Nulls.SKIP
    )
    public Builder data(Optional<AgentVersion> data) {
      this.data = data;
      return this;
    }

    public Builder data(AgentVersion data) {
      this.data = Optional.ofNullable(data);
      return this;
    }

    public PublishDraftAgentVersioningDraftsResponse build() {
      return new PublishDraftAgentVersioningDraftsResponse(status, data, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
