/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.smallest.resources.atoms.concurrency;

import ai.smallest.core.ClientOptions;
import ai.smallest.core.RequestOptions;
import ai.smallest.resources.atoms.concurrency.requests.UpdateConcurrencyReservationsRequest;
import ai.smallest.resources.atoms.concurrency.types.GetConcurrencyResponse;
import ai.smallest.resources.atoms.concurrency.types.UpdateConcurrencyReservationsResponse;
import java.util.concurrent.CompletableFuture;

public class AsyncConcurrencyClient {
  protected final ClientOptions clientOptions;

  private final AsyncRawConcurrencyClient rawClient;

  public AsyncConcurrencyClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new AsyncRawConcurrencyClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public AsyncRawConcurrencyClient withRawResponse() {
    return this.rawClient;
  }

  /**
   * Returns the organization's overall concurrency limit, how much is reserved across all agents, the remaining unreserved pool, and the per-agent reservation breakdown per call channel.
   */
  public CompletableFuture<GetConcurrencyResponse> getConcurrency() {
    return this.rawClient.getConcurrency().thenApply(response -> response.body());
  }

  /**
   * Returns the organization's overall concurrency limit, how much is reserved across all agents, the remaining unreserved pool, and the per-agent reservation breakdown per call channel.
   */
  public CompletableFuture<GetConcurrencyResponse> getConcurrency(RequestOptions requestOptions) {
    return this.rawClient.getConcurrency(requestOptions).thenApply(response -> response.body());
  }

  /**
   * Updates concurrency reservations for one or more agents in a single request. Replaces the existing reservation values for each specified agent. <strong>Admin role required.</strong>
   */
  public CompletableFuture<UpdateConcurrencyReservationsResponse> updateConcurrencyReservations(
      UpdateConcurrencyReservationsRequest request) {
    return this.rawClient.updateConcurrencyReservations(request).thenApply(response -> response.body());
  }

  /**
   * Updates concurrency reservations for one or more agents in a single request. Replaces the existing reservation values for each specified agent. <strong>Admin role required.</strong>
   */
  public CompletableFuture<UpdateConcurrencyReservationsResponse> updateConcurrencyReservations(
      UpdateConcurrencyReservationsRequest request, RequestOptions requestOptions) {
    return this.rawClient.updateConcurrencyReservations(request, requestOptions).thenApply(response -> response.body());
  }
}
