/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.smallest.resources.atoms.concurrency;

import ai.smallest.core.ClientOptions;
import ai.smallest.core.MediaTypes;
import ai.smallest.core.ObjectMappers;
import ai.smallest.core.RequestOptions;
import ai.smallest.core.RetryInterceptor;
import ai.smallest.core.SmallestAIApiException;
import ai.smallest.core.SmallestAIException;
import ai.smallest.core.SmallestAIHttpResponse;
import ai.smallest.resources.atoms.concurrency.requests.UpdateConcurrencyReservationsRequest;
import ai.smallest.resources.atoms.concurrency.types.GetConcurrencyResponse;
import ai.smallest.resources.atoms.concurrency.types.UpdateConcurrencyReservationsResponse;
import ai.smallest.resources.atoms.errors.BadRequestError;
import ai.smallest.resources.atoms.errors.ForbiddenError;
import ai.smallest.resources.atoms.errors.InternalServerError;
import ai.smallest.resources.atoms.errors.UnauthorizedError;
import com.fasterxml.jackson.core.JsonProcessingException;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.util.concurrent.CompletableFuture;
import okhttp3.Call;
import okhttp3.Callback;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;
import org.jetbrains.annotations.NotNull;

public class AsyncRawConcurrencyClient {
  protected final ClientOptions clientOptions;

  public AsyncRawConcurrencyClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
  }

  /**
   * Returns the organization's overall concurrency limit, how much is reserved across all agents, the remaining unreserved pool, and the per-agent reservation breakdown per call channel.
   */
  public CompletableFuture<SmallestAIHttpResponse<GetConcurrencyResponse>> getConcurrency() {
    return getConcurrency(null);
  }

  /**
   * Returns the organization's overall concurrency limit, how much is reserved across all agents, the remaining unreserved pool, and the per-agent reservation breakdown per call channel.
   */
  public CompletableFuture<SmallestAIHttpResponse<GetConcurrencyResponse>> getConcurrency(
      RequestOptions requestOptions) {
    HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getAtomsURL()).newBuilder()

      .addPathSegments("concurrency");if (requestOptions != null) {
        requestOptions.getQueryParameters().forEach((_key, _value) -> {
          httpUrl.addQueryParameter(_key, _value);
        } );
      }
      Request okhttpRequest = new Request.Builder()
        .url(httpUrl.build())
        .method("GET", null)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Accept", "application/json")
        .build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
        okhttpRequest = okhttpRequest.newBuilder().tag(RetryInterceptor.MaxRetriesOverride.class, new RetryInterceptor.MaxRetriesOverride(requestOptions.getMaxRetries().get())).build();
      }
      CompletableFuture<SmallestAIHttpResponse<GetConcurrencyResponse>> future = new CompletableFuture<>();
      client.newCall(okhttpRequest).enqueue(new Callback() {
        @Override
        public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
          try (ResponseBody responseBody = response.body()) {
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
              future.complete(new SmallestAIHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, GetConcurrencyResponse.class), response));
              return;
            }
            try {
              switch (response.code()) {
                case 401:future.completeExceptionally(new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                return;
                case 500:future.completeExceptionally(new InternalServerError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                return;
              }
            }
            catch (JsonProcessingException ignored) {
              // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            future.completeExceptionally(new SmallestAIApiException("Error with status code " + response.code(), response.code(), errorBody, response));
            return;
          }
          catch (JsonProcessingException e) {
            future.completeExceptionally(new SmallestAIException("Failed to deserialize response: " + e.getMessage(), e));
          }
          catch (IOException e) {
            future.completeExceptionally(new SmallestAIException("Network error executing HTTP request", e));
          }
        }

        @Override
        public void onFailure(@NotNull Call call, @NotNull IOException e) {
          future.completeExceptionally(new SmallestAIException("Network error executing HTTP request", e));
        }
      });
      return future;
    }

    /**
     * Updates concurrency reservations for one or more agents in a single request. Replaces the existing reservation values for each specified agent. <strong>Admin role required.</strong>
     */
    public CompletableFuture<SmallestAIHttpResponse<UpdateConcurrencyReservationsResponse>> updateConcurrencyReservations(
        UpdateConcurrencyReservationsRequest request) {
      return updateConcurrencyReservations(request,null);
    }

    /**
     * Updates concurrency reservations for one or more agents in a single request. Replaces the existing reservation values for each specified agent. <strong>Admin role required.</strong>
     */
    public CompletableFuture<SmallestAIHttpResponse<UpdateConcurrencyReservationsResponse>> updateConcurrencyReservations(
        UpdateConcurrencyReservationsRequest request, RequestOptions requestOptions) {
      HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getAtomsURL()).newBuilder()

        .addPathSegments("concurrency/reservations");if (requestOptions != null) {
          requestOptions.getQueryParameters().forEach((_key, _value) -> {
            httpUrl.addQueryParameter(_key, _value);
          } );
        }
        RequestBody body;
        try {
          body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        }
        catch(JsonProcessingException e) {
          throw new SmallestAIException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
          .url(httpUrl.build())
          .method("PUT", body)
          .headers(Headers.of(clientOptions.headers(requestOptions)))
          .addHeader("Content-Type", "application/json")
          .addHeader("Accept", "application/json")
          .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
          client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
          okhttpRequest = okhttpRequest.newBuilder().tag(RetryInterceptor.MaxRetriesOverride.class, new RetryInterceptor.MaxRetriesOverride(requestOptions.getMaxRetries().get())).build();
        }
        CompletableFuture<SmallestAIHttpResponse<UpdateConcurrencyReservationsResponse>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
          @Override
          public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
            try (ResponseBody responseBody = response.body()) {
              String responseBodyString = responseBody != null ? responseBody.string() : "{}";
              if (response.isSuccessful()) {
                future.complete(new SmallestAIHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, UpdateConcurrencyReservationsResponse.class), response));
                return;
              }
              try {
                switch (response.code()) {
                  case 400:future.completeExceptionally(new BadRequestError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                  return;
                  case 401:future.completeExceptionally(new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                  return;
                  case 403:future.completeExceptionally(new ForbiddenError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                  return;
                  case 500:future.completeExceptionally(new InternalServerError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                  return;
                }
              }
              catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
              }
              Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
              future.completeExceptionally(new SmallestAIApiException("Error with status code " + response.code(), response.code(), errorBody, response));
              return;
            }
            catch (JsonProcessingException e) {
              future.completeExceptionally(new SmallestAIException("Failed to deserialize response: " + e.getMessage(), e));
            }
            catch (IOException e) {
              future.completeExceptionally(new SmallestAIException("Network error executing HTTP request", e));
            }
          }

          @Override
          public void onFailure(@NotNull Call call, @NotNull IOException e) {
            future.completeExceptionally(new SmallestAIException("Network error executing HTTP request", e));
          }
        });
        return future;
      }
    }
