/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.smallest.resources.atoms.callactions.requests;

import ai.smallest.core.ObjectMappers;
import ai.smallest.resources.atoms.callactions.types.UpdateCallActionRequestActionType;
import ai.smallest.resources.atoms.callactions.types.UpdateCallActionRequestCategory;
import ai.smallest.resources.atoms.callactions.types.UpdateCallActionRequestConfig;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = UpdateCallActionRequest.Builder.class
)
public final class UpdateCallActionRequest {
  private final Optional<UpdateCallActionRequestCategory> category;

  private final Optional<String> provider;

  private final Optional<UpdateCallActionRequestActionType> actionType;

  private final Optional<String> object;

  private final Optional<UpdateCallActionRequestConfig> config;

  private final Map<String, Object> additionalProperties;

  private UpdateCallActionRequest(Optional<UpdateCallActionRequestCategory> category,
      Optional<String> provider, Optional<UpdateCallActionRequestActionType> actionType,
      Optional<String> object, Optional<UpdateCallActionRequestConfig> config,
      Map<String, Object> additionalProperties) {
    this.category = category;
    this.provider = provider;
    this.actionType = actionType;
    this.object = object;
    this.config = config;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Change when the action fires
   */
  @JsonProperty("category")
  public Optional<UpdateCallActionRequestCategory> getCategory() {
    return category;
  }

  /**
   * @return Change the integration provider
   */
  @JsonProperty("provider")
  public Optional<String> getProvider() {
    return provider;
  }

  /**
   * @return Change the operation type
   */
  @JsonProperty("action_type")
  public Optional<UpdateCallActionRequestActionType> getActionType() {
    return actionType;
  }

  /**
   * @return Change the provider object type
   */
  @JsonProperty("object")
  public Optional<String> getObject() {
    return object;
  }

  @JsonProperty("config")
  public Optional<UpdateCallActionRequestConfig> getConfig() {
    return config;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof UpdateCallActionRequest && equalTo((UpdateCallActionRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(UpdateCallActionRequest other) {
    return category.equals(other.category) && provider.equals(other.provider) && actionType.equals(other.actionType) && object.equals(other.object) && config.equals(other.config);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.category, this.provider, this.actionType, this.object, this.config);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<UpdateCallActionRequestCategory> category = Optional.empty();

    private Optional<String> provider = Optional.empty();

    private Optional<UpdateCallActionRequestActionType> actionType = Optional.empty();

    private Optional<String> object = Optional.empty();

    private Optional<UpdateCallActionRequestConfig> config = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(UpdateCallActionRequest other) {
      category(other.getCategory());
      provider(other.getProvider());
      actionType(other.getActionType());
      object(other.getObject());
      config(other.getConfig());
      return this;
    }

    /**
     * <p>Change when the action fires</p>
     */
    @JsonSetter(
        value = "category",
        nulls = Nulls.SKIP
    )
    public Builder category(Optional<UpdateCallActionRequestCategory> category) {
      this.category = category;
      return this;
    }

    public Builder category(UpdateCallActionRequestCategory category) {
      this.category = Optional.ofNullable(category);
      return this;
    }

    /**
     * <p>Change the integration provider</p>
     */
    @JsonSetter(
        value = "provider",
        nulls = Nulls.SKIP
    )
    public Builder provider(Optional<String> provider) {
      this.provider = provider;
      return this;
    }

    public Builder provider(String provider) {
      this.provider = Optional.ofNullable(provider);
      return this;
    }

    /**
     * <p>Change the operation type</p>
     */
    @JsonSetter(
        value = "action_type",
        nulls = Nulls.SKIP
    )
    public Builder actionType(Optional<UpdateCallActionRequestActionType> actionType) {
      this.actionType = actionType;
      return this;
    }

    public Builder actionType(UpdateCallActionRequestActionType actionType) {
      this.actionType = Optional.ofNullable(actionType);
      return this;
    }

    /**
     * <p>Change the provider object type</p>
     */
    @JsonSetter(
        value = "object",
        nulls = Nulls.SKIP
    )
    public Builder object(Optional<String> object) {
      this.object = object;
      return this;
    }

    public Builder object(String object) {
      this.object = Optional.ofNullable(object);
      return this;
    }

    @JsonSetter(
        value = "config",
        nulls = Nulls.SKIP
    )
    public Builder config(Optional<UpdateCallActionRequestConfig> config) {
      this.config = config;
      return this;
    }

    public Builder config(UpdateCallActionRequestConfig config) {
      this.config = Optional.ofNullable(config);
      return this;
    }

    public UpdateCallActionRequest build() {
      return new UpdateCallActionRequest(category, provider, actionType, object, config, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
