/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.smallest.resources.waves.types;

import ai.smallest.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = ConversationItemContentItem.Builder.class
)
public final class ConversationItemContentItem {
  private final Optional<ConversationItemContentItemType> type;

  private final Optional<String> text;

  private final Map<String, Object> additionalProperties;

  private ConversationItemContentItem(Optional<ConversationItemContentItemType> type,
      Optional<String> text, Map<String, Object> additionalProperties) {
    this.type = type;
    this.text = text;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("type")
  public Optional<ConversationItemContentItemType> getType() {
    return type;
  }

  /**
   * @return For audio message items, <code>text</code> is always <code>null</code> — audio bytes are the payload. The field exists for <code>function_call_output</code> and other text-bearing items.
   */
  @JsonProperty("text")
  public Optional<String> getText() {
    return text;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof ConversationItemContentItem && equalTo((ConversationItemContentItem) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(ConversationItemContentItem other) {
    return type.equals(other.type) && text.equals(other.text);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.type, this.text);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<ConversationItemContentItemType> type = Optional.empty();

    private Optional<String> text = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(ConversationItemContentItem other) {
      type(other.getType());
      text(other.getText());
      return this;
    }

    @JsonSetter(
        value = "type",
        nulls = Nulls.SKIP
    )
    public Builder type(Optional<ConversationItemContentItemType> type) {
      this.type = type;
      return this;
    }

    public Builder type(ConversationItemContentItemType type) {
      this.type = Optional.ofNullable(type);
      return this;
    }

    /**
     * <p>For audio message items, <code>text</code> is always <code>null</code> — audio bytes are the payload. The field exists for <code>function_call_output</code> and other text-bearing items.</p>
     */
    @JsonSetter(
        value = "text",
        nulls = Nulls.SKIP
    )
    public Builder text(Optional<String> text) {
      this.text = text;
      return this;
    }

    public Builder text(String text) {
      this.text = Optional.ofNullable(text);
      return this;
    }

    public ConversationItemContentItem build() {
      return new ConversationItemContentItem(type, text, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
