/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.smallest.resources.waves.types;

import ai.smallest.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = PronunciationItem.Builder.class
)
public final class PronunciationItem {
  private final String word;

  private final String pronunciation;

  private final Map<String, Object> additionalProperties;

  private PronunciationItem(String word, String pronunciation,
      Map<String, Object> additionalProperties) {
    this.word = word;
    this.pronunciation = pronunciation;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return The word to be pronounced
   */
  @JsonProperty("word")
  public String getWord() {
    return word;
  }

  /**
   * @return The phonetic pronunciation of the word
   */
  @JsonProperty("pronunciation")
  public String getPronunciation() {
    return pronunciation;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof PronunciationItem && equalTo((PronunciationItem) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(PronunciationItem other) {
    return word.equals(other.word) && pronunciation.equals(other.pronunciation);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.word, this.pronunciation);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static WordStage builder() {
    return new Builder();
  }

  public interface WordStage {
    /**
     * <p>The word to be pronounced</p>
     */
    PronunciationStage word(@NotNull String word);

    Builder from(PronunciationItem other);
  }

  public interface PronunciationStage {
    /**
     * <p>The phonetic pronunciation of the word</p>
     */
    _FinalStage pronunciation(@NotNull String pronunciation);
  }

  public interface _FinalStage {
    PronunciationItem build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements WordStage, PronunciationStage, _FinalStage {
    private String word;

    private String pronunciation;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(PronunciationItem other) {
      word(other.getWord());
      pronunciation(other.getPronunciation());
      return this;
    }

    /**
     * <p>The word to be pronounced</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("word")
    public PronunciationStage word(@NotNull String word) {
      this.word = Objects.requireNonNull(word, "word must not be null");
      return this;
    }

    /**
     * <p>The phonetic pronunciation of the word</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("pronunciation")
    public _FinalStage pronunciation(@NotNull String pronunciation) {
      this.pronunciation = Objects.requireNonNull(pronunciation, "pronunciation must not be null");
      return this;
    }

    @java.lang.Override
    public PronunciationItem build() {
      return new PronunciationItem(word, pronunciation, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
