/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.smallest.resources.atoms.calls.types;

import ai.smallest.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Boolean;
import java.lang.Double;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = SearchCallsResponseDataLogsItem.Builder.class
)
public final class SearchCallsResponseDataLogsItem {
  private final Optional<String> id;

  private final Optional<String> callId;

  private final Optional<SearchCallsResponseDataLogsItemStatus> status;

  private final Optional<Double> duration;

  private final Optional<String> from;

  private final Optional<String> to;

  private final Optional<SearchCallsResponseDataLogsItemType> type;

  private final Optional<String> agentId;

  private final Optional<String> recordingUrl;

  private final Optional<String> recordingDualUrl;

  private final Optional<String> disconnectionReason;

  private final Optional<Integer> retryCount;

  private final Optional<OffsetDateTime> createdAt;

  private final Optional<String> callFailureReason;

  private final Optional<Double> callCost;

  private final Optional<String> versionId;

  private final Optional<Boolean> isTest;

  private final Optional<String> retryCallId;

  private final Optional<Double> retryAttemptNumber;

  private final Optional<SearchCallsResponseDataLogsItemPostCallAnalytics> postCallAnalytics;

  private final Optional<SearchCallsResponseDataLogsItemTurnLatencyMetrics> turnLatencyMetrics;

  private final Map<String, Object> additionalProperties;

  private SearchCallsResponseDataLogsItem(Optional<String> id, Optional<String> callId,
      Optional<SearchCallsResponseDataLogsItemStatus> status, Optional<Double> duration,
      Optional<String> from, Optional<String> to,
      Optional<SearchCallsResponseDataLogsItemType> type, Optional<String> agentId,
      Optional<String> recordingUrl, Optional<String> recordingDualUrl,
      Optional<String> disconnectionReason, Optional<Integer> retryCount,
      Optional<OffsetDateTime> createdAt, Optional<String> callFailureReason,
      Optional<Double> callCost, Optional<String> versionId, Optional<Boolean> isTest,
      Optional<String> retryCallId, Optional<Double> retryAttemptNumber,
      Optional<SearchCallsResponseDataLogsItemPostCallAnalytics> postCallAnalytics,
      Optional<SearchCallsResponseDataLogsItemTurnLatencyMetrics> turnLatencyMetrics,
      Map<String, Object> additionalProperties) {
    this.id = id;
    this.callId = callId;
    this.status = status;
    this.duration = duration;
    this.from = from;
    this.to = to;
    this.type = type;
    this.agentId = agentId;
    this.recordingUrl = recordingUrl;
    this.recordingDualUrl = recordingDualUrl;
    this.disconnectionReason = disconnectionReason;
    this.retryCount = retryCount;
    this.createdAt = createdAt;
    this.callFailureReason = callFailureReason;
    this.callCost = callCost;
    this.versionId = versionId;
    this.isTest = isTest;
    this.retryCallId = retryCallId;
    this.retryAttemptNumber = retryAttemptNumber;
    this.postCallAnalytics = postCallAnalytics;
    this.turnLatencyMetrics = turnLatencyMetrics;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return The database ID of the call log
   */
  @JsonProperty("_id")
  public Optional<String> getId() {
    return id;
  }

  /**
   * @return The unique call identifier
   */
  @JsonProperty("callId")
  public Optional<String> getCallId() {
    return callId;
  }

  /**
   * @return The status of the call
   */
  @JsonProperty("status")
  public Optional<SearchCallsResponseDataLogsItemStatus> getStatus() {
    return status;
  }

  /**
   * @return The duration of the call in seconds
   */
  @JsonProperty("duration")
  public Optional<Double> getDuration() {
    return duration;
  }

  /**
   * @return The phone number the call was made from
   */
  @JsonProperty("from")
  public Optional<String> getFrom() {
    return from;
  }

  /**
   * @return The phone number the call was made to
   */
  @JsonProperty("to")
  public Optional<String> getTo() {
    return to;
  }

  /**
   * @return The type of call
   */
  @JsonProperty("type")
  public Optional<SearchCallsResponseDataLogsItemType> getType() {
    return type;
  }

  /**
   * @return The ID of the agent that handled the call
   */
  @JsonProperty("agentId")
  public Optional<String> getAgentId() {
    return agentId;
  }

  /**
   * @return URL to the call recording (if available)
   */
  @JsonProperty("recordingUrl")
  public Optional<String> getRecordingUrl() {
    return recordingUrl;
  }

  /**
   * @return URL to the dual-channel call recording (if available)
   */
  @JsonProperty("recordingDualUrl")
  public Optional<String> getRecordingDualUrl() {
    return recordingDualUrl;
  }

  /**
   * @return The reason the call was disconnected
   */
  @JsonProperty("disconnectionReason")
  public Optional<String> getDisconnectionReason() {
    return disconnectionReason;
  }

  /**
   * @return Number of retry attempts for this call
   */
  @JsonProperty("retryCount")
  public Optional<Integer> getRetryCount() {
    return retryCount;
  }

  /**
   * @return When the call was created
   */
  @JsonProperty("createdAt")
  public Optional<OffsetDateTime> getCreatedAt() {
    return createdAt;
  }

  /**
   * @return Reason the call failed, if applicable
   */
  @JsonProperty("callFailureReason")
  public Optional<String> getCallFailureReason() {
    return callFailureReason;
  }

  /**
   * @return Discounted total cost of the call
   */
  @JsonProperty("callCost")
  public Optional<Double> getCallCost() {
    return callCost;
  }

  /**
   * @return ID of the agent version that handled this call
   */
  @JsonProperty("versionId")
  public Optional<String> getVersionId() {
    return versionId;
  }

  /**
   * @return Whether this was a test call
   */
  @JsonProperty("isTest")
  public Optional<Boolean> getIsTest() {
    return isTest;
  }

  /**
   * @return ID of the retry call if this call was retried
   */
  @JsonProperty("retryCallId")
  public Optional<String> getRetryCallId() {
    return retryCallId;
  }

  /**
   * @return Which retry attempt this was (0 = initial)
   */
  @JsonProperty("retryAttemptNumber")
  public Optional<Double> getRetryAttemptNumber() {
    return retryAttemptNumber;
  }

  /**
   * @return Post-call analytics results evaluated against the call transcript
   */
  @JsonProperty("postCallAnalytics")
  public Optional<SearchCallsResponseDataLogsItemPostCallAnalytics> getPostCallAnalytics() {
    return postCallAnalytics;
  }

  /**
   * @return Per-turn latency statistics for the call
   */
  @JsonProperty("turnLatencyMetrics")
  public Optional<SearchCallsResponseDataLogsItemTurnLatencyMetrics> getTurnLatencyMetrics() {
    return turnLatencyMetrics;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof SearchCallsResponseDataLogsItem && equalTo((SearchCallsResponseDataLogsItem) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(SearchCallsResponseDataLogsItem other) {
    return id.equals(other.id) && callId.equals(other.callId) && status.equals(other.status) && duration.equals(other.duration) && from.equals(other.from) && to.equals(other.to) && type.equals(other.type) && agentId.equals(other.agentId) && recordingUrl.equals(other.recordingUrl) && recordingDualUrl.equals(other.recordingDualUrl) && disconnectionReason.equals(other.disconnectionReason) && retryCount.equals(other.retryCount) && createdAt.equals(other.createdAt) && callFailureReason.equals(other.callFailureReason) && callCost.equals(other.callCost) && versionId.equals(other.versionId) && isTest.equals(other.isTest) && retryCallId.equals(other.retryCallId) && retryAttemptNumber.equals(other.retryAttemptNumber) && postCallAnalytics.equals(other.postCallAnalytics) && turnLatencyMetrics.equals(other.turnLatencyMetrics);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.id, this.callId, this.status, this.duration, this.from, this.to, this.type, this.agentId, this.recordingUrl, this.recordingDualUrl, this.disconnectionReason, this.retryCount, this.createdAt, this.callFailureReason, this.callCost, this.versionId, this.isTest, this.retryCallId, this.retryAttemptNumber, this.postCallAnalytics, this.turnLatencyMetrics);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<String> id = Optional.empty();

    private Optional<String> callId = Optional.empty();

    private Optional<SearchCallsResponseDataLogsItemStatus> status = Optional.empty();

    private Optional<Double> duration = Optional.empty();

    private Optional<String> from = Optional.empty();

    private Optional<String> to = Optional.empty();

    private Optional<SearchCallsResponseDataLogsItemType> type = Optional.empty();

    private Optional<String> agentId = Optional.empty();

    private Optional<String> recordingUrl = Optional.empty();

    private Optional<String> recordingDualUrl = Optional.empty();

    private Optional<String> disconnectionReason = Optional.empty();

    private Optional<Integer> retryCount = Optional.empty();

    private Optional<OffsetDateTime> createdAt = Optional.empty();

    private Optional<String> callFailureReason = Optional.empty();

    private Optional<Double> callCost = Optional.empty();

    private Optional<String> versionId = Optional.empty();

    private Optional<Boolean> isTest = Optional.empty();

    private Optional<String> retryCallId = Optional.empty();

    private Optional<Double> retryAttemptNumber = Optional.empty();

    private Optional<SearchCallsResponseDataLogsItemPostCallAnalytics> postCallAnalytics = Optional.empty();

    private Optional<SearchCallsResponseDataLogsItemTurnLatencyMetrics> turnLatencyMetrics = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(SearchCallsResponseDataLogsItem other) {
      id(other.getId());
      callId(other.getCallId());
      status(other.getStatus());
      duration(other.getDuration());
      from(other.getFrom());
      to(other.getTo());
      type(other.getType());
      agentId(other.getAgentId());
      recordingUrl(other.getRecordingUrl());
      recordingDualUrl(other.getRecordingDualUrl());
      disconnectionReason(other.getDisconnectionReason());
      retryCount(other.getRetryCount());
      createdAt(other.getCreatedAt());
      callFailureReason(other.getCallFailureReason());
      callCost(other.getCallCost());
      versionId(other.getVersionId());
      isTest(other.getIsTest());
      retryCallId(other.getRetryCallId());
      retryAttemptNumber(other.getRetryAttemptNumber());
      postCallAnalytics(other.getPostCallAnalytics());
      turnLatencyMetrics(other.getTurnLatencyMetrics());
      return this;
    }

    /**
     * <p>The database ID of the call log</p>
     */
    @JsonSetter(
        value = "_id",
        nulls = Nulls.SKIP
    )
    public Builder id(Optional<String> id) {
      this.id = id;
      return this;
    }

    public Builder id(String id) {
      this.id = Optional.ofNullable(id);
      return this;
    }

    /**
     * <p>The unique call identifier</p>
     */
    @JsonSetter(
        value = "callId",
        nulls = Nulls.SKIP
    )
    public Builder callId(Optional<String> callId) {
      this.callId = callId;
      return this;
    }

    public Builder callId(String callId) {
      this.callId = Optional.ofNullable(callId);
      return this;
    }

    /**
     * <p>The status of the call</p>
     */
    @JsonSetter(
        value = "status",
        nulls = Nulls.SKIP
    )
    public Builder status(Optional<SearchCallsResponseDataLogsItemStatus> status) {
      this.status = status;
      return this;
    }

    public Builder status(SearchCallsResponseDataLogsItemStatus status) {
      this.status = Optional.ofNullable(status);
      return this;
    }

    /**
     * <p>The duration of the call in seconds</p>
     */
    @JsonSetter(
        value = "duration",
        nulls = Nulls.SKIP
    )
    public Builder duration(Optional<Double> duration) {
      this.duration = duration;
      return this;
    }

    public Builder duration(Double duration) {
      this.duration = Optional.ofNullable(duration);
      return this;
    }

    /**
     * <p>The phone number the call was made from</p>
     */
    @JsonSetter(
        value = "from",
        nulls = Nulls.SKIP
    )
    public Builder from(Optional<String> from) {
      this.from = from;
      return this;
    }

    public Builder from(String from) {
      this.from = Optional.ofNullable(from);
      return this;
    }

    /**
     * <p>The phone number the call was made to</p>
     */
    @JsonSetter(
        value = "to",
        nulls = Nulls.SKIP
    )
    public Builder to(Optional<String> to) {
      this.to = to;
      return this;
    }

    public Builder to(String to) {
      this.to = Optional.ofNullable(to);
      return this;
    }

    /**
     * <p>The type of call</p>
     */
    @JsonSetter(
        value = "type",
        nulls = Nulls.SKIP
    )
    public Builder type(Optional<SearchCallsResponseDataLogsItemType> type) {
      this.type = type;
      return this;
    }

    public Builder type(SearchCallsResponseDataLogsItemType type) {
      this.type = Optional.ofNullable(type);
      return this;
    }

    /**
     * <p>The ID of the agent that handled the call</p>
     */
    @JsonSetter(
        value = "agentId",
        nulls = Nulls.SKIP
    )
    public Builder agentId(Optional<String> agentId) {
      this.agentId = agentId;
      return this;
    }

    public Builder agentId(String agentId) {
      this.agentId = Optional.ofNullable(agentId);
      return this;
    }

    /**
     * <p>URL to the call recording (if available)</p>
     */
    @JsonSetter(
        value = "recordingUrl",
        nulls = Nulls.SKIP
    )
    public Builder recordingUrl(Optional<String> recordingUrl) {
      this.recordingUrl = recordingUrl;
      return this;
    }

    public Builder recordingUrl(String recordingUrl) {
      this.recordingUrl = Optional.ofNullable(recordingUrl);
      return this;
    }

    /**
     * <p>URL to the dual-channel call recording (if available)</p>
     */
    @JsonSetter(
        value = "recordingDualUrl",
        nulls = Nulls.SKIP
    )
    public Builder recordingDualUrl(Optional<String> recordingDualUrl) {
      this.recordingDualUrl = recordingDualUrl;
      return this;
    }

    public Builder recordingDualUrl(String recordingDualUrl) {
      this.recordingDualUrl = Optional.ofNullable(recordingDualUrl);
      return this;
    }

    /**
     * <p>The reason the call was disconnected</p>
     */
    @JsonSetter(
        value = "disconnectionReason",
        nulls = Nulls.SKIP
    )
    public Builder disconnectionReason(Optional<String> disconnectionReason) {
      this.disconnectionReason = disconnectionReason;
      return this;
    }

    public Builder disconnectionReason(String disconnectionReason) {
      this.disconnectionReason = Optional.ofNullable(disconnectionReason);
      return this;
    }

    /**
     * <p>Number of retry attempts for this call</p>
     */
    @JsonSetter(
        value = "retryCount",
        nulls = Nulls.SKIP
    )
    public Builder retryCount(Optional<Integer> retryCount) {
      this.retryCount = retryCount;
      return this;
    }

    public Builder retryCount(Integer retryCount) {
      this.retryCount = Optional.ofNullable(retryCount);
      return this;
    }

    /**
     * <p>When the call was created</p>
     */
    @JsonSetter(
        value = "createdAt",
        nulls = Nulls.SKIP
    )
    public Builder createdAt(Optional<OffsetDateTime> createdAt) {
      this.createdAt = createdAt;
      return this;
    }

    public Builder createdAt(OffsetDateTime createdAt) {
      this.createdAt = Optional.ofNullable(createdAt);
      return this;
    }

    /**
     * <p>Reason the call failed, if applicable</p>
     */
    @JsonSetter(
        value = "callFailureReason",
        nulls = Nulls.SKIP
    )
    public Builder callFailureReason(Optional<String> callFailureReason) {
      this.callFailureReason = callFailureReason;
      return this;
    }

    public Builder callFailureReason(String callFailureReason) {
      this.callFailureReason = Optional.ofNullable(callFailureReason);
      return this;
    }

    /**
     * <p>Discounted total cost of the call</p>
     */
    @JsonSetter(
        value = "callCost",
        nulls = Nulls.SKIP
    )
    public Builder callCost(Optional<Double> callCost) {
      this.callCost = callCost;
      return this;
    }

    public Builder callCost(Double callCost) {
      this.callCost = Optional.ofNullable(callCost);
      return this;
    }

    /**
     * <p>ID of the agent version that handled this call</p>
     */
    @JsonSetter(
        value = "versionId",
        nulls = Nulls.SKIP
    )
    public Builder versionId(Optional<String> versionId) {
      this.versionId = versionId;
      return this;
    }

    public Builder versionId(String versionId) {
      this.versionId = Optional.ofNullable(versionId);
      return this;
    }

    /**
     * <p>Whether this was a test call</p>
     */
    @JsonSetter(
        value = "isTest",
        nulls = Nulls.SKIP
    )
    public Builder isTest(Optional<Boolean> isTest) {
      this.isTest = isTest;
      return this;
    }

    public Builder isTest(Boolean isTest) {
      this.isTest = Optional.ofNullable(isTest);
      return this;
    }

    /**
     * <p>ID of the retry call if this call was retried</p>
     */
    @JsonSetter(
        value = "retryCallId",
        nulls = Nulls.SKIP
    )
    public Builder retryCallId(Optional<String> retryCallId) {
      this.retryCallId = retryCallId;
      return this;
    }

    public Builder retryCallId(String retryCallId) {
      this.retryCallId = Optional.ofNullable(retryCallId);
      return this;
    }

    /**
     * <p>Which retry attempt this was (0 = initial)</p>
     */
    @JsonSetter(
        value = "retryAttemptNumber",
        nulls = Nulls.SKIP
    )
    public Builder retryAttemptNumber(Optional<Double> retryAttemptNumber) {
      this.retryAttemptNumber = retryAttemptNumber;
      return this;
    }

    public Builder retryAttemptNumber(Double retryAttemptNumber) {
      this.retryAttemptNumber = Optional.ofNullable(retryAttemptNumber);
      return this;
    }

    /**
     * <p>Post-call analytics results evaluated against the call transcript</p>
     */
    @JsonSetter(
        value = "postCallAnalytics",
        nulls = Nulls.SKIP
    )
    public Builder postCallAnalytics(
        Optional<SearchCallsResponseDataLogsItemPostCallAnalytics> postCallAnalytics) {
      this.postCallAnalytics = postCallAnalytics;
      return this;
    }

    public Builder postCallAnalytics(
        SearchCallsResponseDataLogsItemPostCallAnalytics postCallAnalytics) {
      this.postCallAnalytics = Optional.ofNullable(postCallAnalytics);
      return this;
    }

    /**
     * <p>Per-turn latency statistics for the call</p>
     */
    @JsonSetter(
        value = "turnLatencyMetrics",
        nulls = Nulls.SKIP
    )
    public Builder turnLatencyMetrics(
        Optional<SearchCallsResponseDataLogsItemTurnLatencyMetrics> turnLatencyMetrics) {
      this.turnLatencyMetrics = turnLatencyMetrics;
      return this;
    }

    public Builder turnLatencyMetrics(
        SearchCallsResponseDataLogsItemTurnLatencyMetrics turnLatencyMetrics) {
      this.turnLatencyMetrics = Optional.ofNullable(turnLatencyMetrics);
      return this;
    }

    public SearchCallsResponseDataLogsItem build() {
      return new SearchCallsResponseDataLogsItem(id, callId, status, duration, from, to, type, agentId, recordingUrl, recordingDualUrl, disconnectionReason, retryCount, createdAt, callFailureReason, callCost, versionId, isTest, retryCallId, retryAttemptNumber, postCallAnalytics, turnLatencyMetrics, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
