/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.smallest.resources.waves.pulsesttstreaming.types;

import ai.smallest.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = PulseSpeechStartedEventMessage.Builder.class
)
public final class PulseSpeechStartedEventMessage {
  private final PulseSpeechStartedEventMessageType type;

  private final String sessionId;

  private final double timestamp;

  private final Map<String, Object> additionalProperties;

  private PulseSpeechStartedEventMessage(PulseSpeechStartedEventMessageType type, String sessionId,
      double timestamp, Map<String, Object> additionalProperties) {
    this.type = type;
    this.sessionId = sessionId;
    this.timestamp = timestamp;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Discriminator. Always <code>speech_started</code> for this event.
   */
  @JsonProperty("type")
  public PulseSpeechStartedEventMessageType getType() {
    return type;
  }

  /**
   * @return Matches the <code>session_id</code> returned on <code>transcription</code> messages from the same connection. Use it to correlate VAD events with transcript turns.
   */
  @JsonProperty("session_id")
  public String getSessionId() {
    return sessionId;
  }

  /**
   * @return Acoustic onset of speech, in seconds from the first audio frame sent on this connection.
   */
  @JsonProperty("timestamp")
  public double getTimestamp() {
    return timestamp;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof PulseSpeechStartedEventMessage && equalTo((PulseSpeechStartedEventMessage) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(PulseSpeechStartedEventMessage other) {
    return type.equals(other.type) && sessionId.equals(other.sessionId) && timestamp == other.timestamp;
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.type, this.sessionId, this.timestamp);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static TypeStage builder() {
    return new Builder();
  }

  public interface TypeStage {
    /**
     * <p>Discriminator. Always <code>speech_started</code> for this event.</p>
     */
    SessionIdStage type(@NotNull PulseSpeechStartedEventMessageType type);

    Builder from(PulseSpeechStartedEventMessage other);
  }

  public interface SessionIdStage {
    /**
     * <p>Matches the <code>session_id</code> returned on <code>transcription</code> messages from the same connection. Use it to correlate VAD events with transcript turns.</p>
     */
    TimestampStage sessionId(@NotNull String sessionId);
  }

  public interface TimestampStage {
    /**
     * <p>Acoustic onset of speech, in seconds from the first audio frame sent on this connection.</p>
     */
    _FinalStage timestamp(double timestamp);
  }

  public interface _FinalStage {
    PulseSpeechStartedEventMessage build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements TypeStage, SessionIdStage, TimestampStage, _FinalStage {
    private PulseSpeechStartedEventMessageType type;

    private String sessionId;

    private double timestamp;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(PulseSpeechStartedEventMessage other) {
      type(other.getType());
      sessionId(other.getSessionId());
      timestamp(other.getTimestamp());
      return this;
    }

    /**
     * <p>Discriminator. Always <code>speech_started</code> for this event.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("type")
    public SessionIdStage type(@NotNull PulseSpeechStartedEventMessageType type) {
      this.type = Objects.requireNonNull(type, "type must not be null");
      return this;
    }

    /**
     * <p>Matches the <code>session_id</code> returned on <code>transcription</code> messages from the same connection. Use it to correlate VAD events with transcript turns.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("session_id")
    public TimestampStage sessionId(@NotNull String sessionId) {
      this.sessionId = Objects.requireNonNull(sessionId, "sessionId must not be null");
      return this;
    }

    /**
     * <p>Acoustic onset of speech, in seconds from the first audio frame sent on this connection.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("timestamp")
    public _FinalStage timestamp(double timestamp) {
      this.timestamp = timestamp;
      return this;
    }

    @java.lang.Override
    public PulseSpeechStartedEventMessage build() {
      return new PulseSpeechStartedEventMessage(type, sessionId, timestamp, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
