/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.smallest.resources.atoms.agenttemplates.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class ListAgentTemplatesAgentTemplatesResponseDataItemCallType {
  public static final ListAgentTemplatesAgentTemplatesResponseDataItemCallType INBOUND = new ListAgentTemplatesAgentTemplatesResponseDataItemCallType(Value.INBOUND, "Inbound");

  public static final ListAgentTemplatesAgentTemplatesResponseDataItemCallType OUTBOUND = new ListAgentTemplatesAgentTemplatesResponseDataItemCallType(Value.OUTBOUND, "Outbound");

  public static final ListAgentTemplatesAgentTemplatesResponseDataItemCallType BOTH = new ListAgentTemplatesAgentTemplatesResponseDataItemCallType(Value.BOTH, "Both");

  private final Value value;

  private final String string;

  ListAgentTemplatesAgentTemplatesResponseDataItemCallType(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof ListAgentTemplatesAgentTemplatesResponseDataItemCallType && this.string.equals(((ListAgentTemplatesAgentTemplatesResponseDataItemCallType) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case INBOUND:
        return visitor.visitInbound();
      case OUTBOUND:
        return visitor.visitOutbound();
      case BOTH:
        return visitor.visitBoth();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static ListAgentTemplatesAgentTemplatesResponseDataItemCallType valueOf(String value) {
    switch (value) {
      case "Inbound":
        return INBOUND;
      case "Outbound":
        return OUTBOUND;
      case "Both":
        return BOTH;
      default:
        return new ListAgentTemplatesAgentTemplatesResponseDataItemCallType(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    INBOUND,

    OUTBOUND,

    BOTH,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitInbound();

    T visitOutbound();

    T visitBoth();

    T visitUnknown(String unknownType);
  }
}
